var annotated_dup =
[
    [ "app", null, [
      [ "ImagenetClassifier", "classapp_1_1_imagenet_classifier.html", "classapp_1_1_imagenet_classifier" ]
    ] ],
    [ "caffe", "namespacecaffe.html", "namespacecaffe" ],
    [ "cpp_lint", null, [
      [ "_BlockInfo", "classcpp__lint_1_1___block_info.html", "classcpp__lint_1_1___block_info" ],
      [ "_ClassInfo", "classcpp__lint_1_1___class_info.html", "classcpp__lint_1_1___class_info" ],
      [ "_CppLintState", "classcpp__lint_1_1___cpp_lint_state.html", "classcpp__lint_1_1___cpp_lint_state" ],
      [ "_FunctionState", "classcpp__lint_1_1___function_state.html", "classcpp__lint_1_1___function_state" ],
      [ "_IncludeError", "classcpp__lint_1_1___include_error.html", null ],
      [ "_IncludeState", "classcpp__lint_1_1___include_state.html", "classcpp__lint_1_1___include_state" ],
      [ "_NamespaceInfo", "classcpp__lint_1_1___namespace_info.html", "classcpp__lint_1_1___namespace_info" ],
      [ "_NestingState", "classcpp__lint_1_1___nesting_state.html", "classcpp__lint_1_1___nesting_state" ],
      [ "_PreprocessorInfo", "classcpp__lint_1_1___preprocessor_info.html", "classcpp__lint_1_1___preprocessor_info" ],
      [ "CleansedLines", "classcpp__lint_1_1_cleansed_lines.html", "classcpp__lint_1_1_cleansed_lines" ],
      [ "FileInfo", "classcpp__lint_1_1_file_info.html", "classcpp__lint_1_1_file_info" ]
    ] ],
    [ "google", null, [
      [ "protobuf", null, [
        [ "is_proto_enum< ::caffe::ConvolutionParameter_Engine >", "structgoogle_1_1protobuf_1_1is__proto__enum_3_01_1_1caffe_1_1_convolution_parameter___engine_01_4.html", null ],
        [ "is_proto_enum< ::caffe::DataParameter_DB >", "structgoogle_1_1protobuf_1_1is__proto__enum_3_01_1_1caffe_1_1_data_parameter___d_b_01_4.html", null ],
        [ "is_proto_enum< ::caffe::EltwiseParameter_EltwiseOp >", "structgoogle_1_1protobuf_1_1is__proto__enum_3_01_1_1caffe_1_1_eltwise_parameter___eltwise_op_01_4.html", null ],
        [ "is_proto_enum< ::caffe::FillerParameter_VarianceNorm >", "structgoogle_1_1protobuf_1_1is__proto__enum_3_01_1_1caffe_1_1_filler_parameter___variance_norm_01_4.html", null ],
        [ "is_proto_enum< ::caffe::HingeLossParameter_Norm >", "structgoogle_1_1protobuf_1_1is__proto__enum_3_01_1_1caffe_1_1_hinge_loss_parameter___norm_01_4.html", null ],
        [ "is_proto_enum< ::caffe::LossParameter_NormalizationMode >", "structgoogle_1_1protobuf_1_1is__proto__enum_3_01_1_1caffe_1_1_loss_parameter___normalization_mode_01_4.html", null ],
        [ "is_proto_enum< ::caffe::LRNParameter_Engine >", "structgoogle_1_1protobuf_1_1is__proto__enum_3_01_1_1caffe_1_1_l_r_n_parameter___engine_01_4.html", null ],
        [ "is_proto_enum< ::caffe::LRNParameter_NormRegion >", "structgoogle_1_1protobuf_1_1is__proto__enum_3_01_1_1caffe_1_1_l_r_n_parameter___norm_region_01_4.html", null ],
        [ "is_proto_enum< ::caffe::ParamSpec_DimCheckMode >", "structgoogle_1_1protobuf_1_1is__proto__enum_3_01_1_1caffe_1_1_param_spec___dim_check_mode_01_4.html", null ],
        [ "is_proto_enum< ::caffe::Phase >", "structgoogle_1_1protobuf_1_1is__proto__enum_3_01_1_1caffe_1_1_phase_01_4.html", null ],
        [ "is_proto_enum< ::caffe::PoolingParameter_Engine >", "structgoogle_1_1protobuf_1_1is__proto__enum_3_01_1_1caffe_1_1_pooling_parameter___engine_01_4.html", null ],
        [ "is_proto_enum< ::caffe::PoolingParameter_PoolMethod >", "structgoogle_1_1protobuf_1_1is__proto__enum_3_01_1_1caffe_1_1_pooling_parameter___pool_method_01_4.html", null ],
        [ "is_proto_enum< ::caffe::ReductionParameter_ReductionOp >", "structgoogle_1_1protobuf_1_1is__proto__enum_3_01_1_1caffe_1_1_reduction_parameter___reduction_op_01_4.html", null ],
        [ "is_proto_enum< ::caffe::ReLUParameter_Engine >", "structgoogle_1_1protobuf_1_1is__proto__enum_3_01_1_1caffe_1_1_re_l_u_parameter___engine_01_4.html", null ],
        [ "is_proto_enum< ::caffe::SigmoidParameter_Engine >", "structgoogle_1_1protobuf_1_1is__proto__enum_3_01_1_1caffe_1_1_sigmoid_parameter___engine_01_4.html", null ],
        [ "is_proto_enum< ::caffe::SoftmaxParameter_Engine >", "structgoogle_1_1protobuf_1_1is__proto__enum_3_01_1_1caffe_1_1_softmax_parameter___engine_01_4.html", null ],
        [ "is_proto_enum< ::caffe::SolverParameter_SnapshotFormat >", "structgoogle_1_1protobuf_1_1is__proto__enum_3_01_1_1caffe_1_1_solver_parameter___snapshot_format_01_4.html", null ],
        [ "is_proto_enum< ::caffe::SolverParameter_SolverMode >", "structgoogle_1_1protobuf_1_1is__proto__enum_3_01_1_1caffe_1_1_solver_parameter___solver_mode_01_4.html", null ],
        [ "is_proto_enum< ::caffe::SolverParameter_SolverType >", "structgoogle_1_1protobuf_1_1is__proto__enum_3_01_1_1caffe_1_1_solver_parameter___solver_type_01_4.html", null ],
        [ "is_proto_enum< ::caffe::SPPParameter_Engine >", "structgoogle_1_1protobuf_1_1is__proto__enum_3_01_1_1caffe_1_1_s_p_p_parameter___engine_01_4.html", null ],
        [ "is_proto_enum< ::caffe::SPPParameter_PoolMethod >", "structgoogle_1_1protobuf_1_1is__proto__enum_3_01_1_1caffe_1_1_s_p_p_parameter___pool_method_01_4.html", null ],
        [ "is_proto_enum< ::caffe::TanHParameter_Engine >", "structgoogle_1_1protobuf_1_1is__proto__enum_3_01_1_1caffe_1_1_tan_h_parameter___engine_01_4.html", null ],
        [ "is_proto_enum< ::caffe::V0LayerParameter_PoolMethod >", "structgoogle_1_1protobuf_1_1is__proto__enum_3_01_1_1caffe_1_1_v0_layer_parameter___pool_method_01_4.html", null ],
        [ "is_proto_enum< ::caffe::V1LayerParameter_DimCheckMode >", "structgoogle_1_1protobuf_1_1is__proto__enum_3_01_1_1caffe_1_1_v1_layer_parameter___dim_check_mode_01_4.html", null ],
        [ "is_proto_enum< ::caffe::V1LayerParameter_LayerType >", "structgoogle_1_1protobuf_1_1is__proto__enum_3_01_1_1caffe_1_1_v1_layer_parameter___layer_type_01_4.html", null ]
      ] ]
    ] ],
    [ "pascal_multilabel_datalayers", null, [
      [ "BatchLoader", "classpascal__multilabel__datalayers_1_1_batch_loader.html", "classpascal__multilabel__datalayers_1_1_batch_loader" ],
      [ "PascalMultilabelDataLayerSync", "classpascal__multilabel__datalayers_1_1_pascal_multilabel_data_layer_sync.html", "classpascal__multilabel__datalayers_1_1_pascal_multilabel_data_layer_sync" ]
    ] ],
    [ "pyloss", null, [
      [ "EuclideanLossLayer", "classpyloss_1_1_euclidean_loss_layer.html", "classpyloss_1_1_euclidean_loss_layer" ]
    ] ],
    [ "resize_and_crop_images", null, [
      [ "OpenCVResizeCrop", "classresize__and__crop__images_1_1_open_c_v_resize_crop.html", "classresize__and__crop__images_1_1_open_c_v_resize_crop" ],
      [ "PILResizeCrop", "classresize__and__crop__images_1_1_p_i_l_resize_crop.html", null ],
      [ "ResizeCropImagesMapper", "classresize__and__crop__images_1_1_resize_crop_images_mapper.html", "classresize__and__crop__images_1_1_resize_crop_images_mapper" ]
    ] ],
    [ "std", null, [
      [ "tr1", null, [
        [ "gtest_internal", null, [
          [ "AddRef", "structstd_1_1tr1_1_1gtest__internal_1_1_add_ref.html", "structstd_1_1tr1_1_1gtest__internal_1_1_add_ref" ],
          [ "AddRef< T & >", "structstd_1_1tr1_1_1gtest__internal_1_1_add_ref_3_01_t_01_6_01_4.html", "structstd_1_1tr1_1_1gtest__internal_1_1_add_ref_3_01_t_01_6_01_4" ],
          [ "ByRef", "structstd_1_1tr1_1_1gtest__internal_1_1_by_ref.html", "structstd_1_1tr1_1_1gtest__internal_1_1_by_ref" ],
          [ "ByRef< T & >", "structstd_1_1tr1_1_1gtest__internal_1_1_by_ref_3_01_t_01_6_01_4.html", "structstd_1_1tr1_1_1gtest__internal_1_1_by_ref_3_01_t_01_6_01_4" ],
          [ "Get", "classstd_1_1tr1_1_1gtest__internal_1_1_get.html", null ],
          [ "Get< 0 >", "classstd_1_1tr1_1_1gtest__internal_1_1_get_3_010_01_4.html", null ],
          [ "Get< 1 >", "classstd_1_1tr1_1_1gtest__internal_1_1_get_3_011_01_4.html", null ],
          [ "Get< 2 >", "classstd_1_1tr1_1_1gtest__internal_1_1_get_3_012_01_4.html", null ],
          [ "Get< 3 >", "classstd_1_1tr1_1_1gtest__internal_1_1_get_3_013_01_4.html", null ],
          [ "Get< 4 >", "classstd_1_1tr1_1_1gtest__internal_1_1_get_3_014_01_4.html", null ],
          [ "Get< 5 >", "classstd_1_1tr1_1_1gtest__internal_1_1_get_3_015_01_4.html", null ],
          [ "Get< 6 >", "classstd_1_1tr1_1_1gtest__internal_1_1_get_3_016_01_4.html", null ],
          [ "Get< 7 >", "classstd_1_1tr1_1_1gtest__internal_1_1_get_3_017_01_4.html", null ],
          [ "Get< 8 >", "classstd_1_1tr1_1_1gtest__internal_1_1_get_3_018_01_4.html", null ],
          [ "Get< 9 >", "classstd_1_1tr1_1_1gtest__internal_1_1_get_3_019_01_4.html", null ],
          [ "SameSizeTuplePrefixComparator", "structstd_1_1tr1_1_1gtest__internal_1_1_same_size_tuple_prefix_comparator.html", null ],
          [ "SameSizeTuplePrefixComparator< 0, 0 >", "structstd_1_1tr1_1_1gtest__internal_1_1_same_size_tuple_prefix_comparator_3_010_00_010_01_4.html", null ],
          [ "SameSizeTuplePrefixComparator< k, k >", "structstd_1_1tr1_1_1gtest__internal_1_1_same_size_tuple_prefix_comparator_3_01k_00_01k_01_4.html", null ],
          [ "TupleElement", "structstd_1_1tr1_1_1gtest__internal_1_1_tuple_element.html", null ],
          [ "TupleElement< true, 0, GTEST_10_TUPLE_(T)>", "structstd_1_1tr1_1_1gtest__internal_1_1_tuple_element_3_01true_00_010_00_01_g_t_e_s_t__10___t_u_p_l_e___07_t_08_4.html", "structstd_1_1tr1_1_1gtest__internal_1_1_tuple_element_3_01true_00_010_00_01_g_t_e_s_t__10___t_u_p_l_e___07_t_08_4" ],
          [ "TupleElement< true, 1, GTEST_10_TUPLE_(T)>", "structstd_1_1tr1_1_1gtest__internal_1_1_tuple_element_3_01true_00_011_00_01_g_t_e_s_t__10___t_u_p_l_e___07_t_08_4.html", "structstd_1_1tr1_1_1gtest__internal_1_1_tuple_element_3_01true_00_011_00_01_g_t_e_s_t__10___t_u_p_l_e___07_t_08_4" ],
          [ "TupleElement< true, 2, GTEST_10_TUPLE_(T)>", "structstd_1_1tr1_1_1gtest__internal_1_1_tuple_element_3_01true_00_012_00_01_g_t_e_s_t__10___t_u_p_l_e___07_t_08_4.html", "structstd_1_1tr1_1_1gtest__internal_1_1_tuple_element_3_01true_00_012_00_01_g_t_e_s_t__10___t_u_p_l_e___07_t_08_4" ],
          [ "TupleElement< true, 3, GTEST_10_TUPLE_(T)>", "structstd_1_1tr1_1_1gtest__internal_1_1_tuple_element_3_01true_00_013_00_01_g_t_e_s_t__10___t_u_p_l_e___07_t_08_4.html", "structstd_1_1tr1_1_1gtest__internal_1_1_tuple_element_3_01true_00_013_00_01_g_t_e_s_t__10___t_u_p_l_e___07_t_08_4" ],
          [ "TupleElement< true, 4, GTEST_10_TUPLE_(T)>", "structstd_1_1tr1_1_1gtest__internal_1_1_tuple_element_3_01true_00_014_00_01_g_t_e_s_t__10___t_u_p_l_e___07_t_08_4.html", "structstd_1_1tr1_1_1gtest__internal_1_1_tuple_element_3_01true_00_014_00_01_g_t_e_s_t__10___t_u_p_l_e___07_t_08_4" ],
          [ "TupleElement< true, 5, GTEST_10_TUPLE_(T)>", "structstd_1_1tr1_1_1gtest__internal_1_1_tuple_element_3_01true_00_015_00_01_g_t_e_s_t__10___t_u_p_l_e___07_t_08_4.html", "structstd_1_1tr1_1_1gtest__internal_1_1_tuple_element_3_01true_00_015_00_01_g_t_e_s_t__10___t_u_p_l_e___07_t_08_4" ],
          [ "TupleElement< true, 6, GTEST_10_TUPLE_(T)>", "structstd_1_1tr1_1_1gtest__internal_1_1_tuple_element_3_01true_00_016_00_01_g_t_e_s_t__10___t_u_p_l_e___07_t_08_4.html", "structstd_1_1tr1_1_1gtest__internal_1_1_tuple_element_3_01true_00_016_00_01_g_t_e_s_t__10___t_u_p_l_e___07_t_08_4" ],
          [ "TupleElement< true, 7, GTEST_10_TUPLE_(T)>", "structstd_1_1tr1_1_1gtest__internal_1_1_tuple_element_3_01true_00_017_00_01_g_t_e_s_t__10___t_u_p_l_e___07_t_08_4.html", "structstd_1_1tr1_1_1gtest__internal_1_1_tuple_element_3_01true_00_017_00_01_g_t_e_s_t__10___t_u_p_l_e___07_t_08_4" ],
          [ "TupleElement< true, 8, GTEST_10_TUPLE_(T)>", "structstd_1_1tr1_1_1gtest__internal_1_1_tuple_element_3_01true_00_018_00_01_g_t_e_s_t__10___t_u_p_l_e___07_t_08_4.html", "structstd_1_1tr1_1_1gtest__internal_1_1_tuple_element_3_01true_00_018_00_01_g_t_e_s_t__10___t_u_p_l_e___07_t_08_4" ],
          [ "TupleElement< true, 9, GTEST_10_TUPLE_(T)>", "structstd_1_1tr1_1_1gtest__internal_1_1_tuple_element_3_01true_00_019_00_01_g_t_e_s_t__10___t_u_p_l_e___07_t_08_4.html", "structstd_1_1tr1_1_1gtest__internal_1_1_tuple_element_3_01true_00_019_00_01_g_t_e_s_t__10___t_u_p_l_e___07_t_08_4" ]
        ] ],
        [ "tuple", "classstd_1_1tr1_1_1tuple.html", "classstd_1_1tr1_1_1tuple" ],
        [ "tuple<>", "classstd_1_1tr1_1_1tuple_3_4.html", "classstd_1_1tr1_1_1tuple_3_4" ],
        [ "tuple_element", "structstd_1_1tr1_1_1tuple__element.html", null ],
        [ "tuple_size", "structstd_1_1tr1_1_1tuple__size.html", null ],
        [ "tuple_size< GTEST_0_TUPLE_(T)>", "structstd_1_1tr1_1_1tuple__size_3_01_g_t_e_s_t__0___t_u_p_l_e___07_t_08_4.html", null ],
        [ "tuple_size< GTEST_10_TUPLE_(T)>", "structstd_1_1tr1_1_1tuple__size_3_01_g_t_e_s_t__10___t_u_p_l_e___07_t_08_4.html", null ],
        [ "tuple_size< GTEST_1_TUPLE_(T)>", "structstd_1_1tr1_1_1tuple__size_3_01_g_t_e_s_t__1___t_u_p_l_e___07_t_08_4.html", null ],
        [ "tuple_size< GTEST_2_TUPLE_(T)>", "structstd_1_1tr1_1_1tuple__size_3_01_g_t_e_s_t__2___t_u_p_l_e___07_t_08_4.html", null ],
        [ "tuple_size< GTEST_3_TUPLE_(T)>", "structstd_1_1tr1_1_1tuple__size_3_01_g_t_e_s_t__3___t_u_p_l_e___07_t_08_4.html", null ],
        [ "tuple_size< GTEST_4_TUPLE_(T)>", "structstd_1_1tr1_1_1tuple__size_3_01_g_t_e_s_t__4___t_u_p_l_e___07_t_08_4.html", null ],
        [ "tuple_size< GTEST_5_TUPLE_(T)>", "structstd_1_1tr1_1_1tuple__size_3_01_g_t_e_s_t__5___t_u_p_l_e___07_t_08_4.html", null ],
        [ "tuple_size< GTEST_6_TUPLE_(T)>", "structstd_1_1tr1_1_1tuple__size_3_01_g_t_e_s_t__6___t_u_p_l_e___07_t_08_4.html", null ],
        [ "tuple_size< GTEST_7_TUPLE_(T)>", "structstd_1_1tr1_1_1tuple__size_3_01_g_t_e_s_t__7___t_u_p_l_e___07_t_08_4.html", null ],
        [ "tuple_size< GTEST_8_TUPLE_(T)>", "structstd_1_1tr1_1_1tuple__size_3_01_g_t_e_s_t__8___t_u_p_l_e___07_t_08_4.html", null ],
        [ "tuple_size< GTEST_9_TUPLE_(T)>", "structstd_1_1tr1_1_1tuple__size_3_01_g_t_e_s_t__9___t_u_p_l_e___07_t_08_4.html", null ]
      ] ]
    ] ],
    [ "test_coord_map", null, [
      [ "TestCoordMap", "classtest__coord__map_1_1_test_coord_map.html", "classtest__coord__map_1_1_test_coord_map" ]
    ] ],
    [ "test_draw", null, [
      [ "TestDraw", "classtest__draw_1_1_test_draw.html", "classtest__draw_1_1_test_draw" ]
    ] ],
    [ "test_io", null, [
      [ "TestArrayToDatum", "classtest__io_1_1_test_array_to_datum.html", "classtest__io_1_1_test_array_to_datum" ],
      [ "TestBlobProtoToArray", "classtest__io_1_1_test_blob_proto_to_array.html", "classtest__io_1_1_test_blob_proto_to_array" ]
    ] ],
    [ "test_layer_type_list", null, [
      [ "TestLayerTypeList", "classtest__layer__type__list_1_1_test_layer_type_list.html", "classtest__layer__type__list_1_1_test_layer_type_list" ]
    ] ],
    [ "test_nccl", null, [
      [ "TestNCCL", "classtest__nccl_1_1_test_n_c_c_l.html", "classtest__nccl_1_1_test_n_c_c_l" ]
    ] ],
    [ "test_net", null, [
      [ "TestAllInOne", "classtest__net_1_1_test_all_in_one.html", "classtest__net_1_1_test_all_in_one" ],
      [ "TestLevels", "classtest__net_1_1_test_levels.html", "classtest__net_1_1_test_levels" ],
      [ "TestNet", "classtest__net_1_1_test_net.html", "classtest__net_1_1_test_net" ],
      [ "TestStages", "classtest__net_1_1_test_stages.html", "classtest__net_1_1_test_stages" ]
    ] ],
    [ "test_net_spec", null, [
      [ "TestNetSpec", "classtest__net__spec_1_1_test_net_spec.html", "classtest__net__spec_1_1_test_net_spec" ]
    ] ],
    [ "test_python_layer", null, [
      [ "ExceptionLayer", "classtest__python__layer_1_1_exception_layer.html", "classtest__python__layer_1_1_exception_layer" ],
      [ "ParameterLayer", "classtest__python__layer_1_1_parameter_layer.html", "classtest__python__layer_1_1_parameter_layer" ],
      [ "PhaseLayer", "classtest__python__layer_1_1_phase_layer.html", "classtest__python__layer_1_1_phase_layer" ],
      [ "SimpleLayer", "classtest__python__layer_1_1_simple_layer.html", "classtest__python__layer_1_1_simple_layer" ],
      [ "TestPythonLayer", "classtest__python__layer_1_1_test_python_layer.html", "classtest__python__layer_1_1_test_python_layer" ]
    ] ],
    [ "test_python_layer_with_param_str", null, [
      [ "SimpleParamLayer", "classtest__python__layer__with__param__str_1_1_simple_param_layer.html", "classtest__python__layer__with__param__str_1_1_simple_param_layer" ],
      [ "TestLayerWithParam", "classtest__python__layer__with__param__str_1_1_test_layer_with_param.html", "classtest__python__layer__with__param__str_1_1_test_layer_with_param" ]
    ] ],
    [ "test_solver", null, [
      [ "TestSolver", "classtest__solver_1_1_test_solver.html", "classtest__solver_1_1_test_solver" ]
    ] ],
    [ "testing", null, [
      [ "internal", null, [
        [ "AddReference", "structtesting_1_1internal_1_1_add_reference.html", "structtesting_1_1internal_1_1_add_reference" ],
        [ "AddReference< T & >", "structtesting_1_1internal_1_1_add_reference_3_01_t_01_6_01_4.html", "structtesting_1_1internal_1_1_add_reference_3_01_t_01_6_01_4" ],
        [ "AssertHelper", "classtesting_1_1internal_1_1_assert_helper.html", "classtesting_1_1internal_1_1_assert_helper" ],
        [ "bool_constant", "structtesting_1_1internal_1_1bool__constant.html", "structtesting_1_1internal_1_1bool__constant" ],
        [ "CartesianProductGenerator10", "classtesting_1_1internal_1_1_cartesian_product_generator10.html", "classtesting_1_1internal_1_1_cartesian_product_generator10" ],
        [ "CartesianProductGenerator2", "classtesting_1_1internal_1_1_cartesian_product_generator2.html", "classtesting_1_1internal_1_1_cartesian_product_generator2" ],
        [ "CartesianProductGenerator3", "classtesting_1_1internal_1_1_cartesian_product_generator3.html", "classtesting_1_1internal_1_1_cartesian_product_generator3" ],
        [ "CartesianProductGenerator4", "classtesting_1_1internal_1_1_cartesian_product_generator4.html", "classtesting_1_1internal_1_1_cartesian_product_generator4" ],
        [ "CartesianProductGenerator5", "classtesting_1_1internal_1_1_cartesian_product_generator5.html", "classtesting_1_1internal_1_1_cartesian_product_generator5" ],
        [ "CartesianProductGenerator6", "classtesting_1_1internal_1_1_cartesian_product_generator6.html", "classtesting_1_1internal_1_1_cartesian_product_generator6" ],
        [ "CartesianProductGenerator7", "classtesting_1_1internal_1_1_cartesian_product_generator7.html", "classtesting_1_1internal_1_1_cartesian_product_generator7" ],
        [ "CartesianProductGenerator8", "classtesting_1_1internal_1_1_cartesian_product_generator8.html", "classtesting_1_1internal_1_1_cartesian_product_generator8" ],
        [ "CartesianProductGenerator9", "classtesting_1_1internal_1_1_cartesian_product_generator9.html", "classtesting_1_1internal_1_1_cartesian_product_generator9" ],
        [ "CartesianProductHolder10", "classtesting_1_1internal_1_1_cartesian_product_holder10.html", "classtesting_1_1internal_1_1_cartesian_product_holder10" ],
        [ "CartesianProductHolder2", "classtesting_1_1internal_1_1_cartesian_product_holder2.html", "classtesting_1_1internal_1_1_cartesian_product_holder2" ],
        [ "CartesianProductHolder3", "classtesting_1_1internal_1_1_cartesian_product_holder3.html", "classtesting_1_1internal_1_1_cartesian_product_holder3" ],
        [ "CartesianProductHolder4", "classtesting_1_1internal_1_1_cartesian_product_holder4.html", "classtesting_1_1internal_1_1_cartesian_product_holder4" ],
        [ "CartesianProductHolder5", "classtesting_1_1internal_1_1_cartesian_product_holder5.html", "classtesting_1_1internal_1_1_cartesian_product_holder5" ],
        [ "CartesianProductHolder6", "classtesting_1_1internal_1_1_cartesian_product_holder6.html", "classtesting_1_1internal_1_1_cartesian_product_holder6" ],
        [ "CartesianProductHolder7", "classtesting_1_1internal_1_1_cartesian_product_holder7.html", "classtesting_1_1internal_1_1_cartesian_product_holder7" ],
        [ "CartesianProductHolder8", "classtesting_1_1internal_1_1_cartesian_product_holder8.html", "classtesting_1_1internal_1_1_cartesian_product_holder8" ],
        [ "CartesianProductHolder9", "classtesting_1_1internal_1_1_cartesian_product_holder9.html", "classtesting_1_1internal_1_1_cartesian_product_holder9" ],
        [ "CompileAssert", "structtesting_1_1internal_1_1_compile_assert.html", null ],
        [ "CompileAssertTypesEqual", "structtesting_1_1internal_1_1_compile_assert_types_equal.html", null ],
        [ "CompileAssertTypesEqual< T, T >", "structtesting_1_1internal_1_1_compile_assert_types_equal_3_01_t_00_01_t_01_4.html", null ],
        [ "ConstCharPtr", "structtesting_1_1internal_1_1_const_char_ptr.html", "structtesting_1_1internal_1_1_const_char_ptr" ],
        [ "DefaultGlobalTestPartResultReporter", "classtesting_1_1internal_1_1_default_global_test_part_result_reporter.html", "classtesting_1_1internal_1_1_default_global_test_part_result_reporter" ],
        [ "DefaultPerThreadTestPartResultReporter", "classtesting_1_1internal_1_1_default_per_thread_test_part_result_reporter.html", "classtesting_1_1internal_1_1_default_per_thread_test_part_result_reporter" ],
        [ "EnableIf", "structtesting_1_1internal_1_1_enable_if.html", null ],
        [ "EnableIf< true >", "structtesting_1_1internal_1_1_enable_if_3_01true_01_4.html", "structtesting_1_1internal_1_1_enable_if_3_01true_01_4" ],
        [ "EqHelper", "classtesting_1_1internal_1_1_eq_helper.html", null ],
        [ "EqHelper< true >", "classtesting_1_1internal_1_1_eq_helper_3_01true_01_4.html", null ],
        [ "FilePath", "classtesting_1_1internal_1_1_file_path.html", "classtesting_1_1internal_1_1_file_path" ],
        [ "FloatingPoint", "classtesting_1_1internal_1_1_floating_point.html", "classtesting_1_1internal_1_1_floating_point" ],
        [ "GTestFlagSaver", "classtesting_1_1internal_1_1_g_test_flag_saver.html", "classtesting_1_1internal_1_1_g_test_flag_saver" ],
        [ "GTestLog", "classtesting_1_1internal_1_1_g_test_log.html", "classtesting_1_1internal_1_1_g_test_log" ],
        [ "GTestMutexLock", "classtesting_1_1internal_1_1_g_test_mutex_lock.html", "classtesting_1_1internal_1_1_g_test_mutex_lock" ],
        [ "HasNewFatalFailureHelper", "classtesting_1_1internal_1_1_has_new_fatal_failure_helper.html", "classtesting_1_1internal_1_1_has_new_fatal_failure_helper" ],
        [ "ImplicitlyConvertible", "classtesting_1_1internal_1_1_implicitly_convertible.html", null ],
        [ "is_pointer", "structtesting_1_1internal_1_1is__pointer.html", null ],
        [ "is_pointer< T * >", "structtesting_1_1internal_1_1is__pointer_3_01_t_01_5_01_4.html", null ],
        [ "IsAProtocolMessage", "structtesting_1_1internal_1_1_is_a_protocol_message.html", null ],
        [ "IteratorTraits", "structtesting_1_1internal_1_1_iterator_traits.html", "structtesting_1_1internal_1_1_iterator_traits" ],
        [ "IteratorTraits< const T * >", "structtesting_1_1internal_1_1_iterator_traits_3_01const_01_t_01_5_01_4.html", "structtesting_1_1internal_1_1_iterator_traits_3_01const_01_t_01_5_01_4" ],
        [ "IteratorTraits< T * >", "structtesting_1_1internal_1_1_iterator_traits_3_01_t_01_5_01_4.html", "structtesting_1_1internal_1_1_iterator_traits_3_01_t_01_5_01_4" ],
        [ "linked_ptr", "classtesting_1_1internal_1_1linked__ptr.html", "classtesting_1_1internal_1_1linked__ptr" ],
        [ "linked_ptr_internal", "classtesting_1_1internal_1_1linked__ptr__internal.html", "classtesting_1_1internal_1_1linked__ptr__internal" ],
        [ "Mutex", "classtesting_1_1internal_1_1_mutex.html", "classtesting_1_1internal_1_1_mutex" ],
        [ "NativeArray", "classtesting_1_1internal_1_1_native_array.html", "classtesting_1_1internal_1_1_native_array" ],
        [ "OsStackTraceGetter", "classtesting_1_1internal_1_1_os_stack_trace_getter.html", "classtesting_1_1internal_1_1_os_stack_trace_getter" ],
        [ "OsStackTraceGetterInterface", "classtesting_1_1internal_1_1_os_stack_trace_getter_interface.html", "classtesting_1_1internal_1_1_os_stack_trace_getter_interface" ],
        [ "ParameterizedTestCaseInfo", "classtesting_1_1internal_1_1_parameterized_test_case_info.html", "classtesting_1_1internal_1_1_parameterized_test_case_info" ],
        [ "ParameterizedTestCaseInfoBase", "classtesting_1_1internal_1_1_parameterized_test_case_info_base.html", "classtesting_1_1internal_1_1_parameterized_test_case_info_base" ],
        [ "ParameterizedTestCaseRegistry", "classtesting_1_1internal_1_1_parameterized_test_case_registry.html", "classtesting_1_1internal_1_1_parameterized_test_case_registry" ],
        [ "ParameterizedTestFactory", "classtesting_1_1internal_1_1_parameterized_test_factory.html", "classtesting_1_1internal_1_1_parameterized_test_factory" ],
        [ "ParamGenerator", "classtesting_1_1internal_1_1_param_generator.html", "classtesting_1_1internal_1_1_param_generator" ],
        [ "ParamGeneratorInterface", "classtesting_1_1internal_1_1_param_generator_interface.html", "classtesting_1_1internal_1_1_param_generator_interface" ],
        [ "ParamIterator", "classtesting_1_1internal_1_1_param_iterator.html", "classtesting_1_1internal_1_1_param_iterator" ],
        [ "ParamIteratorInterface", "classtesting_1_1internal_1_1_param_iterator_interface.html", "classtesting_1_1internal_1_1_param_iterator_interface" ],
        [ "PrettyUnitTestResultPrinter", "classtesting_1_1internal_1_1_pretty_unit_test_result_printer.html", "classtesting_1_1internal_1_1_pretty_unit_test_result_printer" ],
        [ "Random", "classtesting_1_1internal_1_1_random.html", "classtesting_1_1internal_1_1_random" ],
        [ "RangeGenerator", "classtesting_1_1internal_1_1_range_generator.html", "classtesting_1_1internal_1_1_range_generator" ],
        [ "RE", "classtesting_1_1internal_1_1_r_e.html", "classtesting_1_1internal_1_1_r_e" ],
        [ "RemoveConst", "structtesting_1_1internal_1_1_remove_const.html", "structtesting_1_1internal_1_1_remove_const" ],
        [ "RemoveConst< const T >", "structtesting_1_1internal_1_1_remove_const_3_01const_01_t_01_4.html", "structtesting_1_1internal_1_1_remove_const_3_01const_01_t_01_4" ],
        [ "RemoveReference", "structtesting_1_1internal_1_1_remove_reference.html", "structtesting_1_1internal_1_1_remove_reference" ],
        [ "RemoveReference< T & >", "structtesting_1_1internal_1_1_remove_reference_3_01_t_01_6_01_4.html", "structtesting_1_1internal_1_1_remove_reference_3_01_t_01_6_01_4" ],
        [ "scoped_ptr", "classtesting_1_1internal_1_1scoped__ptr.html", "classtesting_1_1internal_1_1scoped__ptr" ],
        [ "ScopedTrace", "classtesting_1_1internal_1_1_scoped_trace.html", "classtesting_1_1internal_1_1_scoped_trace" ],
        [ "SingleFailureChecker", "classtesting_1_1internal_1_1_single_failure_checker.html", "classtesting_1_1internal_1_1_single_failure_checker" ],
        [ "StaticAssertTypeEqHelper", "structtesting_1_1internal_1_1_static_assert_type_eq_helper.html", null ],
        [ "StaticAssertTypeEqHelper< T, T >", "structtesting_1_1internal_1_1_static_assert_type_eq_helper_3_01_t_00_01_t_01_4.html", null ],
        [ "String", "classtesting_1_1internal_1_1_string.html", "classtesting_1_1internal_1_1_string" ],
        [ "TestCaseNameIs", "classtesting_1_1internal_1_1_test_case_name_is.html", "classtesting_1_1internal_1_1_test_case_name_is" ],
        [ "TestEventRepeater", "classtesting_1_1internal_1_1_test_event_repeater.html", "classtesting_1_1internal_1_1_test_event_repeater" ],
        [ "TestFactoryBase", "classtesting_1_1internal_1_1_test_factory_base.html", "classtesting_1_1internal_1_1_test_factory_base" ],
        [ "TestFactoryImpl", "classtesting_1_1internal_1_1_test_factory_impl.html", "classtesting_1_1internal_1_1_test_factory_impl" ],
        [ "TestMetaFactory", "classtesting_1_1internal_1_1_test_meta_factory.html", "classtesting_1_1internal_1_1_test_meta_factory" ],
        [ "TestMetaFactoryBase", "classtesting_1_1internal_1_1_test_meta_factory_base.html", "classtesting_1_1internal_1_1_test_meta_factory_base" ],
        [ "TestPropertyKeyIs", "classtesting_1_1internal_1_1_test_property_key_is.html", "classtesting_1_1internal_1_1_test_property_key_is" ],
        [ "TestResultAccessor", "classtesting_1_1internal_1_1_test_result_accessor.html", null ],
        [ "ThreadLocal", "classtesting_1_1internal_1_1_thread_local.html", "classtesting_1_1internal_1_1_thread_local" ],
        [ "TraceInfo", "structtesting_1_1internal_1_1_trace_info.html", "structtesting_1_1internal_1_1_trace_info" ],
        [ "TuplePrefixPrinter", "structtesting_1_1internal_1_1_tuple_prefix_printer.html", null ],
        [ "TuplePrefixPrinter< 0 >", "structtesting_1_1internal_1_1_tuple_prefix_printer_3_010_01_4.html", null ],
        [ "TuplePrefixPrinter< 1 >", "structtesting_1_1internal_1_1_tuple_prefix_printer_3_011_01_4.html", null ],
        [ "TypeIdHelper", "classtesting_1_1internal_1_1_type_id_helper.html", null ],
        [ "TypeWithSize", "classtesting_1_1internal_1_1_type_with_size.html", "classtesting_1_1internal_1_1_type_with_size" ],
        [ "TypeWithSize< 4 >", "classtesting_1_1internal_1_1_type_with_size_3_014_01_4.html", "classtesting_1_1internal_1_1_type_with_size_3_014_01_4" ],
        [ "TypeWithSize< 8 >", "classtesting_1_1internal_1_1_type_with_size_3_018_01_4.html", "classtesting_1_1internal_1_1_type_with_size_3_018_01_4" ],
        [ "UnitTestImpl", "classtesting_1_1internal_1_1_unit_test_impl.html", "classtesting_1_1internal_1_1_unit_test_impl" ],
        [ "UnitTestOptions", "classtesting_1_1internal_1_1_unit_test_options.html", null ],
        [ "UniversalPrinter", "classtesting_1_1internal_1_1_universal_printer.html", null ],
        [ "UniversalPrinter< T & >", "classtesting_1_1internal_1_1_universal_printer_3_01_t_01_6_01_4.html", null ],
        [ "UniversalPrinter< T[N]>", "classtesting_1_1internal_1_1_universal_printer_3_01_t[_n]_4.html", null ],
        [ "ValueArray1", "classtesting_1_1internal_1_1_value_array1.html", "classtesting_1_1internal_1_1_value_array1" ],
        [ "ValueArray10", "classtesting_1_1internal_1_1_value_array10.html", "classtesting_1_1internal_1_1_value_array10" ],
        [ "ValueArray11", "classtesting_1_1internal_1_1_value_array11.html", "classtesting_1_1internal_1_1_value_array11" ],
        [ "ValueArray12", "classtesting_1_1internal_1_1_value_array12.html", "classtesting_1_1internal_1_1_value_array12" ],
        [ "ValueArray13", "classtesting_1_1internal_1_1_value_array13.html", "classtesting_1_1internal_1_1_value_array13" ],
        [ "ValueArray14", "classtesting_1_1internal_1_1_value_array14.html", "classtesting_1_1internal_1_1_value_array14" ],
        [ "ValueArray15", "classtesting_1_1internal_1_1_value_array15.html", "classtesting_1_1internal_1_1_value_array15" ],
        [ "ValueArray16", "classtesting_1_1internal_1_1_value_array16.html", "classtesting_1_1internal_1_1_value_array16" ],
        [ "ValueArray17", "classtesting_1_1internal_1_1_value_array17.html", "classtesting_1_1internal_1_1_value_array17" ],
        [ "ValueArray18", "classtesting_1_1internal_1_1_value_array18.html", "classtesting_1_1internal_1_1_value_array18" ],
        [ "ValueArray19", "classtesting_1_1internal_1_1_value_array19.html", "classtesting_1_1internal_1_1_value_array19" ],
        [ "ValueArray2", "classtesting_1_1internal_1_1_value_array2.html", "classtesting_1_1internal_1_1_value_array2" ],
        [ "ValueArray20", "classtesting_1_1internal_1_1_value_array20.html", "classtesting_1_1internal_1_1_value_array20" ],
        [ "ValueArray21", "classtesting_1_1internal_1_1_value_array21.html", "classtesting_1_1internal_1_1_value_array21" ],
        [ "ValueArray22", "classtesting_1_1internal_1_1_value_array22.html", "classtesting_1_1internal_1_1_value_array22" ],
        [ "ValueArray23", "classtesting_1_1internal_1_1_value_array23.html", "classtesting_1_1internal_1_1_value_array23" ],
        [ "ValueArray24", "classtesting_1_1internal_1_1_value_array24.html", "classtesting_1_1internal_1_1_value_array24" ],
        [ "ValueArray25", "classtesting_1_1internal_1_1_value_array25.html", "classtesting_1_1internal_1_1_value_array25" ],
        [ "ValueArray26", "classtesting_1_1internal_1_1_value_array26.html", "classtesting_1_1internal_1_1_value_array26" ],
        [ "ValueArray27", "classtesting_1_1internal_1_1_value_array27.html", "classtesting_1_1internal_1_1_value_array27" ],
        [ "ValueArray28", "classtesting_1_1internal_1_1_value_array28.html", "classtesting_1_1internal_1_1_value_array28" ],
        [ "ValueArray29", "classtesting_1_1internal_1_1_value_array29.html", "classtesting_1_1internal_1_1_value_array29" ],
        [ "ValueArray3", "classtesting_1_1internal_1_1_value_array3.html", "classtesting_1_1internal_1_1_value_array3" ],
        [ "ValueArray30", "classtesting_1_1internal_1_1_value_array30.html", "classtesting_1_1internal_1_1_value_array30" ],
        [ "ValueArray31", "classtesting_1_1internal_1_1_value_array31.html", "classtesting_1_1internal_1_1_value_array31" ],
        [ "ValueArray32", "classtesting_1_1internal_1_1_value_array32.html", "classtesting_1_1internal_1_1_value_array32" ],
        [ "ValueArray33", "classtesting_1_1internal_1_1_value_array33.html", "classtesting_1_1internal_1_1_value_array33" ],
        [ "ValueArray34", "classtesting_1_1internal_1_1_value_array34.html", "classtesting_1_1internal_1_1_value_array34" ],
        [ "ValueArray35", "classtesting_1_1internal_1_1_value_array35.html", "classtesting_1_1internal_1_1_value_array35" ],
        [ "ValueArray36", "classtesting_1_1internal_1_1_value_array36.html", "classtesting_1_1internal_1_1_value_array36" ],
        [ "ValueArray37", "classtesting_1_1internal_1_1_value_array37.html", "classtesting_1_1internal_1_1_value_array37" ],
        [ "ValueArray38", "classtesting_1_1internal_1_1_value_array38.html", "classtesting_1_1internal_1_1_value_array38" ],
        [ "ValueArray39", "classtesting_1_1internal_1_1_value_array39.html", "classtesting_1_1internal_1_1_value_array39" ],
        [ "ValueArray4", "classtesting_1_1internal_1_1_value_array4.html", "classtesting_1_1internal_1_1_value_array4" ],
        [ "ValueArray40", "classtesting_1_1internal_1_1_value_array40.html", "classtesting_1_1internal_1_1_value_array40" ],
        [ "ValueArray41", "classtesting_1_1internal_1_1_value_array41.html", "classtesting_1_1internal_1_1_value_array41" ],
        [ "ValueArray42", "classtesting_1_1internal_1_1_value_array42.html", "classtesting_1_1internal_1_1_value_array42" ],
        [ "ValueArray43", "classtesting_1_1internal_1_1_value_array43.html", "classtesting_1_1internal_1_1_value_array43" ],
        [ "ValueArray44", "classtesting_1_1internal_1_1_value_array44.html", "classtesting_1_1internal_1_1_value_array44" ],
        [ "ValueArray45", "classtesting_1_1internal_1_1_value_array45.html", "classtesting_1_1internal_1_1_value_array45" ],
        [ "ValueArray46", "classtesting_1_1internal_1_1_value_array46.html", "classtesting_1_1internal_1_1_value_array46" ],
        [ "ValueArray47", "classtesting_1_1internal_1_1_value_array47.html", "classtesting_1_1internal_1_1_value_array47" ],
        [ "ValueArray48", "classtesting_1_1internal_1_1_value_array48.html", "classtesting_1_1internal_1_1_value_array48" ],
        [ "ValueArray49", "classtesting_1_1internal_1_1_value_array49.html", "classtesting_1_1internal_1_1_value_array49" ],
        [ "ValueArray5", "classtesting_1_1internal_1_1_value_array5.html", "classtesting_1_1internal_1_1_value_array5" ],
        [ "ValueArray50", "classtesting_1_1internal_1_1_value_array50.html", "classtesting_1_1internal_1_1_value_array50" ],
        [ "ValueArray6", "classtesting_1_1internal_1_1_value_array6.html", "classtesting_1_1internal_1_1_value_array6" ],
        [ "ValueArray7", "classtesting_1_1internal_1_1_value_array7.html", "classtesting_1_1internal_1_1_value_array7" ],
        [ "ValueArray8", "classtesting_1_1internal_1_1_value_array8.html", "classtesting_1_1internal_1_1_value_array8" ],
        [ "ValueArray9", "classtesting_1_1internal_1_1_value_array9.html", "classtesting_1_1internal_1_1_value_array9" ],
        [ "ValuesInIteratorRangeGenerator", "classtesting_1_1internal_1_1_values_in_iterator_range_generator.html", "classtesting_1_1internal_1_1_values_in_iterator_range_generator" ],
        [ "XmlUnitTestResultPrinter", "classtesting_1_1internal_1_1_xml_unit_test_result_printer.html", "classtesting_1_1internal_1_1_xml_unit_test_result_printer" ]
      ] ],
      [ "internal2", null, [
        [ "TypeWithoutFormatter", "classtesting_1_1internal2_1_1_type_without_formatter.html", null ],
        [ "TypeWithoutFormatter< T, kConvertibleToInteger >", "classtesting_1_1internal2_1_1_type_without_formatter_3_01_t_00_01k_convertible_to_integer_01_4.html", null ],
        [ "TypeWithoutFormatter< T, kProtobuf >", "classtesting_1_1internal2_1_1_type_without_formatter_3_01_t_00_01k_protobuf_01_4.html", null ]
      ] ],
      [ "AssertionResult", "classtesting_1_1_assertion_result.html", "classtesting_1_1_assertion_result" ],
      [ "EmptyTestEventListener", "classtesting_1_1_empty_test_event_listener.html", "classtesting_1_1_empty_test_event_listener" ],
      [ "Environment", "classtesting_1_1_environment.html", "classtesting_1_1_environment" ],
      [ "Message", "classtesting_1_1_message.html", "classtesting_1_1_message" ],
      [ "ScopedFakeTestPartResultReporter", "classtesting_1_1_scoped_fake_test_part_result_reporter.html", "classtesting_1_1_scoped_fake_test_part_result_reporter" ],
      [ "Test", "classtesting_1_1_test.html", "classtesting_1_1_test" ],
      [ "TestCase", "classtesting_1_1_test_case.html", "classtesting_1_1_test_case" ],
      [ "TestEventListener", "classtesting_1_1_test_event_listener.html", "classtesting_1_1_test_event_listener" ],
      [ "TestEventListeners", "classtesting_1_1_test_event_listeners.html", "classtesting_1_1_test_event_listeners" ],
      [ "TestInfo", "classtesting_1_1_test_info.html", "classtesting_1_1_test_info" ],
      [ "TestPartResult", "classtesting_1_1_test_part_result.html", "classtesting_1_1_test_part_result" ],
      [ "TestPartResultArray", "classtesting_1_1_test_part_result_array.html", "classtesting_1_1_test_part_result_array" ],
      [ "TestPartResultReporterInterface", "classtesting_1_1_test_part_result_reporter_interface.html", "classtesting_1_1_test_part_result_reporter_interface" ],
      [ "TestProperty", "classtesting_1_1_test_property.html", "classtesting_1_1_test_property" ],
      [ "TestResult", "classtesting_1_1_test_result.html", "classtesting_1_1_test_result" ],
      [ "TestWithParam", "classtesting_1_1_test_with_param.html", null ],
      [ "UnitTest", "classtesting_1_1_unit_test.html", "classtesting_1_1_unit_test" ],
      [ "WithParamInterface", "classtesting_1_1_with_param_interface.html", "classtesting_1_1_with_param_interface" ]
    ] ],
    [ "tools", null, [
      [ "CaffeSolver", "classtools_1_1_caffe_solver.html", "classtools_1_1_caffe_solver" ],
      [ "SimpleTransformer", "classtools_1_1_simple_transformer.html", "classtools_1_1_simple_transformer" ]
    ] ],
    [ "handler_registry", "structhandler__registry.html", "structhandler__registry" ]
];