var hierarchy =
[
    [ "std::tr1::gtest_internal::AddRef< T >", "structstd_1_1tr1_1_1gtest__internal_1_1_add_ref.html", null ],
    [ "std::tr1::gtest_internal::AddRef< T & >", "structstd_1_1tr1_1_1gtest__internal_1_1_add_ref_3_01_t_01_6_01_4.html", null ],
    [ "testing::internal::AddReference< T >", "structtesting_1_1internal_1_1_add_reference.html", null ],
    [ "testing::internal::AddReference< T & >", "structtesting_1_1internal_1_1_add_reference_3_01_t_01_6_01_4.html", null ],
    [ "caffe::NdarrayConverterGenerator::apply< T >", "structcaffe_1_1_ndarray_converter_generator_1_1apply.html", null ],
    [ "caffe::NdarrayConverterGenerator::apply< Dtype * >", "structcaffe_1_1_ndarray_converter_generator_1_1apply_3_01_dtype_01_5_01_4.html", null ],
    [ "testing::internal::AssertHelper", "classtesting_1_1internal_1_1_assert_helper.html", null ],
    [ "testing::AssertionResult", "classtesting_1_1_assertion_result.html", null ],
    [ "BasicMapper", null, [
      [ "resize_and_crop_images.ResizeCropImagesMapper", "classresize__and__crop__images_1_1_resize_crop_images_mapper.html", null ]
    ] ],
    [ "caffe::Batch< Dtype >", "classcaffe_1_1_batch.html", null ],
    [ "caffe::Blob< Dtype >", "classcaffe_1_1_blob.html", null ],
    [ "caffe::Blob< int >", "classcaffe_1_1_blob.html", null ],
    [ "caffe::Blob< unsigned int >", "classcaffe_1_1_blob.html", null ],
    [ "caffe::BlockingQueue< T >", "classcaffe_1_1_blocking_queue.html", null ],
    [ "caffe::BlockingQueue< caffe::Batch< Dtype > *>", "classcaffe_1_1_blocking_queue.html", null ],
    [ "testing::internal::bool_constant< bool_value >", "structtesting_1_1internal_1_1bool__constant.html", [
      [ "testing::internal::is_pointer< T >", "structtesting_1_1internal_1_1is__pointer.html", null ],
      [ "testing::internal::is_pointer< T * >", "structtesting_1_1internal_1_1is__pointer_3_01_t_01_5_01_4.html", null ]
    ] ],
    [ "testing::internal::bool_constant< ImplicitlyConvertible< const T *, const ::ProtocolMessage *>::value||ImplicitlyConvertible< const T *, const ::proto2::Message *>::value >", "structtesting_1_1internal_1_1bool__constant.html", [
      [ "testing::internal::IsAProtocolMessage< T >", "structtesting_1_1internal_1_1_is_a_protocol_message.html", null ]
    ] ],
    [ "std::tr1::gtest_internal::ByRef< T >", "structstd_1_1tr1_1_1gtest__internal_1_1_by_ref.html", null ],
    [ "std::tr1::gtest_internal::ByRef< T & >", "structstd_1_1tr1_1_1gtest__internal_1_1_by_ref_3_01_t_01_6_01_4.html", null ],
    [ "caffe::Caffe", "classcaffe_1_1_caffe.html", null ],
    [ "tools.CaffeSolver", "classtools_1_1_caffe_solver.html", null ],
    [ "caffe::Net< Dtype >::Callback", "classcaffe_1_1_net_1_1_callback.html", [
      [ "caffe::NetCallback< Dtype >", "classcaffe_1_1_net_callback.html", null ]
    ] ],
    [ "caffe::Solver< Dtype >::Callback", "classcaffe_1_1_solver_1_1_callback.html", [
      [ "caffe::SolverCallback< Dtype >", "classcaffe_1_1_solver_callback.html", null ]
    ] ],
    [ "testing::internal::CartesianProductHolder10< Generator1, Generator2, Generator3, Generator4, Generator5, Generator6, Generator7, Generator8, Generator9, Generator10 >", "classtesting_1_1internal_1_1_cartesian_product_holder10.html", null ],
    [ "testing::internal::CartesianProductHolder2< Generator1, Generator2 >", "classtesting_1_1internal_1_1_cartesian_product_holder2.html", null ],
    [ "testing::internal::CartesianProductHolder3< Generator1, Generator2, Generator3 >", "classtesting_1_1internal_1_1_cartesian_product_holder3.html", null ],
    [ "testing::internal::CartesianProductHolder4< Generator1, Generator2, Generator3, Generator4 >", "classtesting_1_1internal_1_1_cartesian_product_holder4.html", null ],
    [ "testing::internal::CartesianProductHolder5< Generator1, Generator2, Generator3, Generator4, Generator5 >", "classtesting_1_1internal_1_1_cartesian_product_holder5.html", null ],
    [ "testing::internal::CartesianProductHolder6< Generator1, Generator2, Generator3, Generator4, Generator5, Generator6 >", "classtesting_1_1internal_1_1_cartesian_product_holder6.html", null ],
    [ "testing::internal::CartesianProductHolder7< Generator1, Generator2, Generator3, Generator4, Generator5, Generator6, Generator7 >", "classtesting_1_1internal_1_1_cartesian_product_holder7.html", null ],
    [ "testing::internal::CartesianProductHolder8< Generator1, Generator2, Generator3, Generator4, Generator5, Generator6, Generator7, Generator8 >", "classtesting_1_1internal_1_1_cartesian_product_holder8.html", null ],
    [ "testing::internal::CartesianProductHolder9< Generator1, Generator2, Generator3, Generator4, Generator5, Generator6, Generator7, Generator8, Generator9 >", "classtesting_1_1internal_1_1_cartesian_product_holder9.html", null ],
    [ "testing::internal::CompileAssert< bool >", "structtesting_1_1internal_1_1_compile_assert.html", null ],
    [ "testing::internal::CompileAssertTypesEqual< T1, T2 >", "structtesting_1_1internal_1_1_compile_assert_types_equal.html", null ],
    [ "testing::internal::CompileAssertTypesEqual< T, T >", "structtesting_1_1internal_1_1_compile_assert_types_equal_3_01_t_00_01_t_01_4.html", null ],
    [ "testing::internal::ConstCharPtr", "structtesting_1_1internal_1_1_const_char_ptr.html", null ],
    [ "caffe::CPUDevice< TypeParam >", "structcaffe_1_1_c_p_u_device.html", null ],
    [ "caffe::db::Cursor", "classcaffe_1_1db_1_1_cursor.html", null ],
    [ "caffe::DataTransformer< Dtype >", "classcaffe_1_1_data_transformer.html", null ],
    [ "caffe::db::DB", "classcaffe_1_1db_1_1_d_b.html", null ],
    [ "default_call_policies", null, [
      [ "caffe::NdarrayCallPolicies", "structcaffe_1_1_ndarray_call_policies.html", null ]
    ] ],
    [ "dict", null, [
      [ "cpp_lint._IncludeState", "classcpp__lint_1_1___include_state.html", null ]
    ] ],
    [ "testing::internal::EnableIf< bool >", "structtesting_1_1internal_1_1_enable_if.html", null ],
    [ "testing::internal::EnableIf< true >", "structtesting_1_1internal_1_1_enable_if_3_01true_01_4.html", null ],
    [ "testing::Environment", "classtesting_1_1_environment.html", null ],
    [ "testing::internal::EqHelper< lhs_is_null_literal >", "classtesting_1_1internal_1_1_eq_helper.html", null ],
    [ "testing::internal::EqHelper< true >", "classtesting_1_1internal_1_1_eq_helper_3_01true_01_4.html", null ],
    [ "Exception", null, [
      [ "caffe.coord_map.AxisMismatchException", "classcaffe_1_1coord__map_1_1_axis_mismatch_exception.html", null ],
      [ "caffe.coord_map.AxisMismatchException", "classcaffe_1_1coord__map_1_1_axis_mismatch_exception.html", null ],
      [ "caffe.coord_map.UndefinedMapException", "classcaffe_1_1coord__map_1_1_undefined_map_exception.html", null ],
      [ "caffe.coord_map.UndefinedMapException", "classcaffe_1_1coord__map_1_1_undefined_map_exception.html", null ],
      [ "cpp_lint._IncludeError", "classcpp__lint_1_1___include_error.html", null ]
    ] ],
    [ "cpp_lint.FileInfo", "classcpp__lint_1_1_file_info.html", null ],
    [ "testing::internal::FilePath", "classtesting_1_1internal_1_1_file_path.html", null ],
    [ "caffe::Filler< Dtype >", "classcaffe_1_1_filler.html", [
      [ "caffe::BilinearFiller< Dtype >", "classcaffe_1_1_bilinear_filler.html", null ],
      [ "caffe::BilinearFiller< Dtype >", "classcaffe_1_1_bilinear_filler.html", null ],
      [ "caffe::ConstantFiller< Dtype >", "classcaffe_1_1_constant_filler.html", null ],
      [ "caffe::ConstantFiller< Dtype >", "classcaffe_1_1_constant_filler.html", null ],
      [ "caffe::GaussianFiller< Dtype >", "classcaffe_1_1_gaussian_filler.html", null ],
      [ "caffe::GaussianFiller< Dtype >", "classcaffe_1_1_gaussian_filler.html", null ],
      [ "caffe::MSRAFiller< Dtype >", "classcaffe_1_1_m_s_r_a_filler.html", null ],
      [ "caffe::MSRAFiller< Dtype >", "classcaffe_1_1_m_s_r_a_filler.html", null ],
      [ "caffe::PositiveUnitballFiller< Dtype >", "classcaffe_1_1_positive_unitball_filler.html", null ],
      [ "caffe::PositiveUnitballFiller< Dtype >", "classcaffe_1_1_positive_unitball_filler.html", null ],
      [ "caffe::UniformFiller< Dtype >", "classcaffe_1_1_uniform_filler.html", null ],
      [ "caffe::UniformFiller< Dtype >", "classcaffe_1_1_uniform_filler.html", null ],
      [ "caffe::XavierFiller< Dtype >", "classcaffe_1_1_xavier_filler.html", null ],
      [ "caffe::XavierFiller< Dtype >", "classcaffe_1_1_xavier_filler.html", null ]
    ] ],
    [ "testing::internal::FloatingPoint< RawType >", "classtesting_1_1internal_1_1_floating_point.html", null ],
    [ "caffe::Caffe::RNG::Generator", "classcaffe_1_1_caffe_1_1_r_n_g_1_1_generator.html", null ],
    [ "std::tr1::gtest_internal::Get< k >", "classstd_1_1tr1_1_1gtest__internal_1_1_get.html", null ],
    [ "std::tr1::gtest_internal::Get< 0 >", "classstd_1_1tr1_1_1gtest__internal_1_1_get_3_010_01_4.html", null ],
    [ "std::tr1::gtest_internal::Get< 1 >", "classstd_1_1tr1_1_1gtest__internal_1_1_get_3_011_01_4.html", null ],
    [ "std::tr1::gtest_internal::Get< 2 >", "classstd_1_1tr1_1_1gtest__internal_1_1_get_3_012_01_4.html", null ],
    [ "std::tr1::gtest_internal::Get< 3 >", "classstd_1_1tr1_1_1gtest__internal_1_1_get_3_013_01_4.html", null ],
    [ "std::tr1::gtest_internal::Get< 4 >", "classstd_1_1tr1_1_1gtest__internal_1_1_get_3_014_01_4.html", null ],
    [ "std::tr1::gtest_internal::Get< 5 >", "classstd_1_1tr1_1_1gtest__internal_1_1_get_3_015_01_4.html", null ],
    [ "std::tr1::gtest_internal::Get< 6 >", "classstd_1_1tr1_1_1gtest__internal_1_1_get_3_016_01_4.html", null ],
    [ "std::tr1::gtest_internal::Get< 7 >", "classstd_1_1tr1_1_1gtest__internal_1_1_get_3_017_01_4.html", null ],
    [ "std::tr1::gtest_internal::Get< 8 >", "classstd_1_1tr1_1_1gtest__internal_1_1_get_3_018_01_4.html", null ],
    [ "std::tr1::gtest_internal::Get< 9 >", "classstd_1_1tr1_1_1gtest__internal_1_1_get_3_019_01_4.html", null ],
    [ "caffe::GPUDevice< TypeParam >", "structcaffe_1_1_g_p_u_device.html", null ],
    [ "caffe::GradientChecker< Dtype >", "classcaffe_1_1_gradient_checker.html", null ],
    [ "testing::internal::GTestFlagSaver", "classtesting_1_1internal_1_1_g_test_flag_saver.html", null ],
    [ "testing::internal::GTestLog", "classtesting_1_1internal_1_1_g_test_log.html", null ],
    [ "testing::internal::GTestMutexLock", "classtesting_1_1internal_1_1_g_test_mutex_lock.html", null ],
    [ "handler_registry", "structhandler__registry.html", null ],
    [ "testing::internal::ImplicitlyConvertible< From, To >", "classtesting_1_1internal_1_1_implicitly_convertible.html", null ],
    [ "caffe::InternalThread", "classcaffe_1_1_internal_thread.html", [
      [ "caffe::BasePrefetchingDataLayer< Dtype >", "classcaffe_1_1_base_prefetching_data_layer.html", [
        [ "caffe::DataLayer< Dtype >", "classcaffe_1_1_data_layer.html", null ],
        [ "caffe::DataLayer< Dtype >", "classcaffe_1_1_data_layer.html", null ],
        [ "caffe::ImageDataLayer< Dtype >", "classcaffe_1_1_image_data_layer.html", null ],
        [ "caffe::ImageDataLayer< Dtype >", "classcaffe_1_1_image_data_layer.html", null ],
        [ "caffe::WindowDataLayer< Dtype >", "classcaffe_1_1_window_data_layer.html", null ],
        [ "caffe::WindowDataLayer< Dtype >", "classcaffe_1_1_window_data_layer.html", null ]
      ] ],
      [ "caffe::BasePrefetchingDataLayer< Dtype >", "classcaffe_1_1_base_prefetching_data_layer.html", null ],
      [ "caffe::TestThreadA", "classcaffe_1_1_test_thread_a.html", null ],
      [ "caffe::TestThreadB", "classcaffe_1_1_test_thread_b.html", null ]
    ] ],
    [ "testing::internal::IteratorTraits< Iterator >", "structtesting_1_1internal_1_1_iterator_traits.html", null ],
    [ "testing::internal::IteratorTraits< const T * >", "structtesting_1_1internal_1_1_iterator_traits_3_01const_01_t_01_5_01_4.html", null ],
    [ "testing::internal::IteratorTraits< T * >", "structtesting_1_1internal_1_1_iterator_traits_3_01_t_01_5_01_4.html", null ],
    [ "caffe::Layer< Dtype >", "classcaffe_1_1_layer.html", [
      [ "caffe::AccuracyLayer< Dtype >", "classcaffe_1_1_accuracy_layer.html", null ],
      [ "caffe::AccuracyLayer< Dtype >", "classcaffe_1_1_accuracy_layer.html", null ],
      [ "caffe::ArgMaxLayer< Dtype >", "classcaffe_1_1_arg_max_layer.html", null ],
      [ "caffe::ArgMaxLayer< Dtype >", "classcaffe_1_1_arg_max_layer.html", null ],
      [ "caffe::BaseConvolutionLayer< Dtype >", "classcaffe_1_1_base_convolution_layer.html", [
        [ "caffe::ConvolutionLayer< Dtype >", "classcaffe_1_1_convolution_layer.html", null ],
        [ "caffe::ConvolutionLayer< Dtype >", "classcaffe_1_1_convolution_layer.html", null ],
        [ "caffe::DeconvolutionLayer< Dtype >", "classcaffe_1_1_deconvolution_layer.html", null ],
        [ "caffe::DeconvolutionLayer< Dtype >", "classcaffe_1_1_deconvolution_layer.html", null ]
      ] ],
      [ "caffe::BaseConvolutionLayer< Dtype >", "classcaffe_1_1_base_convolution_layer.html", null ],
      [ "caffe::BaseDataLayer< Dtype >", "classcaffe_1_1_base_data_layer.html", [
        [ "caffe::BasePrefetchingDataLayer< Dtype >", "classcaffe_1_1_base_prefetching_data_layer.html", null ],
        [ "caffe::BasePrefetchingDataLayer< Dtype >", "classcaffe_1_1_base_prefetching_data_layer.html", null ],
        [ "caffe::MemoryDataLayer< Dtype >", "classcaffe_1_1_memory_data_layer.html", null ],
        [ "caffe::MemoryDataLayer< Dtype >", "classcaffe_1_1_memory_data_layer.html", null ]
      ] ],
      [ "caffe::BaseDataLayer< Dtype >", "classcaffe_1_1_base_data_layer.html", null ],
      [ "caffe::BatchNormLayer< Dtype >", "classcaffe_1_1_batch_norm_layer.html", null ],
      [ "caffe::BatchNormLayer< Dtype >", "classcaffe_1_1_batch_norm_layer.html", null ],
      [ "caffe::BatchReindexLayer< Dtype >", "classcaffe_1_1_batch_reindex_layer.html", null ],
      [ "caffe::BatchReindexLayer< Dtype >", "classcaffe_1_1_batch_reindex_layer.html", null ],
      [ "caffe::BiasLayer< Dtype >", "classcaffe_1_1_bias_layer.html", null ],
      [ "caffe::BiasLayer< Dtype >", "classcaffe_1_1_bias_layer.html", null ],
      [ "caffe::ConcatLayer< Dtype >", "classcaffe_1_1_concat_layer.html", null ],
      [ "caffe::ConcatLayer< Dtype >", "classcaffe_1_1_concat_layer.html", null ],
      [ "caffe::CropLayer< Dtype >", "classcaffe_1_1_crop_layer.html", null ],
      [ "caffe::CropLayer< Dtype >", "classcaffe_1_1_crop_layer.html", null ],
      [ "caffe::DummyDataLayer< Dtype >", "classcaffe_1_1_dummy_data_layer.html", null ],
      [ "caffe::DummyDataLayer< Dtype >", "classcaffe_1_1_dummy_data_layer.html", null ],
      [ "caffe::EltwiseLayer< Dtype >", "classcaffe_1_1_eltwise_layer.html", null ],
      [ "caffe::EltwiseLayer< Dtype >", "classcaffe_1_1_eltwise_layer.html", null ],
      [ "caffe::EmbedLayer< Dtype >", "classcaffe_1_1_embed_layer.html", null ],
      [ "caffe::EmbedLayer< Dtype >", "classcaffe_1_1_embed_layer.html", null ],
      [ "caffe::FilterLayer< Dtype >", "classcaffe_1_1_filter_layer.html", null ],
      [ "caffe::FilterLayer< Dtype >", "classcaffe_1_1_filter_layer.html", null ],
      [ "caffe::FlattenLayer< Dtype >", "classcaffe_1_1_flatten_layer.html", null ],
      [ "caffe::FlattenLayer< Dtype >", "classcaffe_1_1_flatten_layer.html", null ],
      [ "caffe::HDF5DataLayer< Dtype >", "classcaffe_1_1_h_d_f5_data_layer.html", null ],
      [ "caffe::HDF5DataLayer< Dtype >", "classcaffe_1_1_h_d_f5_data_layer.html", null ],
      [ "caffe::HDF5OutputLayer< Dtype >", "classcaffe_1_1_h_d_f5_output_layer.html", null ],
      [ "caffe::HDF5OutputLayer< Dtype >", "classcaffe_1_1_h_d_f5_output_layer.html", null ],
      [ "caffe::Im2colLayer< Dtype >", "classcaffe_1_1_im2col_layer.html", null ],
      [ "caffe::Im2colLayer< Dtype >", "classcaffe_1_1_im2col_layer.html", null ],
      [ "caffe::InnerProductLayer< Dtype >", "classcaffe_1_1_inner_product_layer.html", null ],
      [ "caffe::InnerProductLayer< Dtype >", "classcaffe_1_1_inner_product_layer.html", null ],
      [ "caffe::InputLayer< Dtype >", "classcaffe_1_1_input_layer.html", null ],
      [ "caffe::InputLayer< Dtype >", "classcaffe_1_1_input_layer.html", null ],
      [ "caffe::LossLayer< Dtype >", "classcaffe_1_1_loss_layer.html", [
        [ "caffe::ContrastiveLossLayer< Dtype >", "classcaffe_1_1_contrastive_loss_layer.html", null ],
        [ "caffe::ContrastiveLossLayer< Dtype >", "classcaffe_1_1_contrastive_loss_layer.html", null ],
        [ "caffe::EuclideanLossLayer< Dtype >", "classcaffe_1_1_euclidean_loss_layer.html", null ],
        [ "caffe::EuclideanLossLayer< Dtype >", "classcaffe_1_1_euclidean_loss_layer.html", null ],
        [ "caffe::HingeLossLayer< Dtype >", "classcaffe_1_1_hinge_loss_layer.html", null ],
        [ "caffe::HingeLossLayer< Dtype >", "classcaffe_1_1_hinge_loss_layer.html", null ],
        [ "caffe::InfogainLossLayer< Dtype >", "classcaffe_1_1_infogain_loss_layer.html", null ],
        [ "caffe::InfogainLossLayer< Dtype >", "classcaffe_1_1_infogain_loss_layer.html", null ],
        [ "caffe::MultinomialLogisticLossLayer< Dtype >", "classcaffe_1_1_multinomial_logistic_loss_layer.html", null ],
        [ "caffe::MultinomialLogisticLossLayer< Dtype >", "classcaffe_1_1_multinomial_logistic_loss_layer.html", null ],
        [ "caffe::SigmoidCrossEntropyLossLayer< Dtype >", "classcaffe_1_1_sigmoid_cross_entropy_loss_layer.html", null ],
        [ "caffe::SigmoidCrossEntropyLossLayer< Dtype >", "classcaffe_1_1_sigmoid_cross_entropy_loss_layer.html", null ],
        [ "caffe::SoftmaxWithLossLayer< Dtype >", "classcaffe_1_1_softmax_with_loss_layer.html", null ],
        [ "caffe::SoftmaxWithLossLayer< Dtype >", "classcaffe_1_1_softmax_with_loss_layer.html", null ],
        [ "caffe::WeightedEuclideanLossLayer< Dtype >", "classcaffe_1_1_weighted_euclidean_loss_layer.html", null ],
        [ "caffe::WeightedEuclideanLossLayer< Dtype >", "classcaffe_1_1_weighted_euclidean_loss_layer.html", null ]
      ] ],
      [ "caffe::LossLayer< Dtype >", "classcaffe_1_1_loss_layer.html", null ],
      [ "caffe::LRNLayer< Dtype >", "classcaffe_1_1_l_r_n_layer.html", null ],
      [ "caffe::LRNLayer< Dtype >", "classcaffe_1_1_l_r_n_layer.html", null ],
      [ "caffe::LSTMUnitLayer< Dtype >", "classcaffe_1_1_l_s_t_m_unit_layer.html", null ],
      [ "caffe::LSTMUnitLayer< Dtype >", "classcaffe_1_1_l_s_t_m_unit_layer.html", null ],
      [ "caffe::MVNLayer< Dtype >", "classcaffe_1_1_m_v_n_layer.html", null ],
      [ "caffe::MVNLayer< Dtype >", "classcaffe_1_1_m_v_n_layer.html", null ],
      [ "caffe::NeuronLayer< Dtype >", "classcaffe_1_1_neuron_layer.html", [
        [ "caffe::AbsValLayer< Dtype >", "classcaffe_1_1_abs_val_layer.html", null ],
        [ "caffe::AbsValLayer< Dtype >", "classcaffe_1_1_abs_val_layer.html", null ],
        [ "caffe::BNLLLayer< Dtype >", "classcaffe_1_1_b_n_l_l_layer.html", null ],
        [ "caffe::BNLLLayer< Dtype >", "classcaffe_1_1_b_n_l_l_layer.html", null ],
        [ "caffe::DropoutLayer< Dtype >", "classcaffe_1_1_dropout_layer.html", null ],
        [ "caffe::DropoutLayer< Dtype >", "classcaffe_1_1_dropout_layer.html", null ],
        [ "caffe::ELULayer< Dtype >", "classcaffe_1_1_e_l_u_layer.html", null ],
        [ "caffe::ELULayer< Dtype >", "classcaffe_1_1_e_l_u_layer.html", null ],
        [ "caffe::ExpLayer< Dtype >", "classcaffe_1_1_exp_layer.html", null ],
        [ "caffe::ExpLayer< Dtype >", "classcaffe_1_1_exp_layer.html", null ],
        [ "caffe::LogLayer< Dtype >", "classcaffe_1_1_log_layer.html", null ],
        [ "caffe::LogLayer< Dtype >", "classcaffe_1_1_log_layer.html", null ],
        [ "caffe::PowerLayer< Dtype >", "classcaffe_1_1_power_layer.html", null ],
        [ "caffe::PowerLayer< Dtype >", "classcaffe_1_1_power_layer.html", null ],
        [ "caffe::PReLULayer< Dtype >", "classcaffe_1_1_p_re_l_u_layer.html", null ],
        [ "caffe::PReLULayer< Dtype >", "classcaffe_1_1_p_re_l_u_layer.html", null ],
        [ "caffe::ReLULayer< Dtype >", "classcaffe_1_1_re_l_u_layer.html", null ],
        [ "caffe::ReLULayer< Dtype >", "classcaffe_1_1_re_l_u_layer.html", null ],
        [ "caffe::SigmoidLayer< Dtype >", "classcaffe_1_1_sigmoid_layer.html", null ],
        [ "caffe::SigmoidLayer< Dtype >", "classcaffe_1_1_sigmoid_layer.html", null ],
        [ "caffe::SwishLayer< Dtype >", "classcaffe_1_1_swish_layer.html", null ],
        [ "caffe::SwishLayer< Dtype >", "classcaffe_1_1_swish_layer.html", null ],
        [ "caffe::TanHLayer< Dtype >", "classcaffe_1_1_tan_h_layer.html", null ],
        [ "caffe::TanHLayer< Dtype >", "classcaffe_1_1_tan_h_layer.html", null ],
        [ "caffe::ThresholdLayer< Dtype >", "classcaffe_1_1_threshold_layer.html", null ],
        [ "caffe::ThresholdLayer< Dtype >", "classcaffe_1_1_threshold_layer.html", null ]
      ] ],
      [ "caffe::NeuronLayer< Dtype >", "classcaffe_1_1_neuron_layer.html", null ],
      [ "caffe::ParameterLayer< Dtype >", "classcaffe_1_1_parameter_layer.html", null ],
      [ "caffe::ParameterLayer< Dtype >", "classcaffe_1_1_parameter_layer.html", null ],
      [ "caffe::PoolingLayer< Dtype >", "classcaffe_1_1_pooling_layer.html", null ],
      [ "caffe::PoolingLayer< Dtype >", "classcaffe_1_1_pooling_layer.html", null ],
      [ "caffe::PythonLayer< Dtype >", "classcaffe_1_1_python_layer.html", null ],
      [ "caffe::PythonLayer< Dtype >", "classcaffe_1_1_python_layer.html", null ],
      [ "caffe::RecurrentLayer< Dtype >", "classcaffe_1_1_recurrent_layer.html", [
        [ "caffe::LSTMLayer< Dtype >", "classcaffe_1_1_l_s_t_m_layer.html", null ],
        [ "caffe::LSTMLayer< Dtype >", "classcaffe_1_1_l_s_t_m_layer.html", null ],
        [ "caffe::RNNLayer< Dtype >", "classcaffe_1_1_r_n_n_layer.html", null ],
        [ "caffe::RNNLayer< Dtype >", "classcaffe_1_1_r_n_n_layer.html", null ]
      ] ],
      [ "caffe::RecurrentLayer< Dtype >", "classcaffe_1_1_recurrent_layer.html", null ],
      [ "caffe::ReductionLayer< Dtype >", "classcaffe_1_1_reduction_layer.html", null ],
      [ "caffe::ReductionLayer< Dtype >", "classcaffe_1_1_reduction_layer.html", null ],
      [ "caffe::ReshapeLayer< Dtype >", "classcaffe_1_1_reshape_layer.html", null ],
      [ "caffe::ReshapeLayer< Dtype >", "classcaffe_1_1_reshape_layer.html", null ],
      [ "caffe::ScaleLayer< Dtype >", "classcaffe_1_1_scale_layer.html", null ],
      [ "caffe::ScaleLayer< Dtype >", "classcaffe_1_1_scale_layer.html", null ],
      [ "caffe::SilenceLayer< Dtype >", "classcaffe_1_1_silence_layer.html", null ],
      [ "caffe::SilenceLayer< Dtype >", "classcaffe_1_1_silence_layer.html", null ],
      [ "caffe::SliceLayer< Dtype >", "classcaffe_1_1_slice_layer.html", null ],
      [ "caffe::SliceLayer< Dtype >", "classcaffe_1_1_slice_layer.html", null ],
      [ "caffe::SoftmaxLayer< Dtype >", "classcaffe_1_1_softmax_layer.html", null ],
      [ "caffe::SoftmaxLayer< Dtype >", "classcaffe_1_1_softmax_layer.html", null ],
      [ "caffe::SplitLayer< Dtype >", "classcaffe_1_1_split_layer.html", null ],
      [ "caffe::SplitLayer< Dtype >", "classcaffe_1_1_split_layer.html", null ],
      [ "caffe::SPPLayer< Dtype >", "classcaffe_1_1_s_p_p_layer.html", null ],
      [ "caffe::SPPLayer< Dtype >", "classcaffe_1_1_s_p_p_layer.html", null ],
      [ "caffe::TileLayer< Dtype >", "classcaffe_1_1_tile_layer.html", null ],
      [ "caffe::TileLayer< Dtype >", "classcaffe_1_1_tile_layer.html", null ],
      [ "pascal_multilabel_datalayers.PascalMultilabelDataLayerSync", "classpascal__multilabel__datalayers_1_1_pascal_multilabel_data_layer_sync.html", null ],
      [ "pyloss.EuclideanLossLayer", "classpyloss_1_1_euclidean_loss_layer.html", null ],
      [ "test_python_layer.ExceptionLayer", "classtest__python__layer_1_1_exception_layer.html", null ],
      [ "test_python_layer.ParameterLayer", "classtest__python__layer_1_1_parameter_layer.html", null ],
      [ "test_python_layer.PhaseLayer", "classtest__python__layer_1_1_phase_layer.html", null ],
      [ "test_python_layer.SimpleLayer", "classtest__python__layer_1_1_simple_layer.html", null ],
      [ "test_python_layer_with_param_str.SimpleParamLayer", "classtest__python__layer__with__param__str_1_1_simple_param_layer.html", null ]
    ] ],
    [ "caffe::LayerRegisterer< Dtype >", "classcaffe_1_1_layer_registerer.html", null ],
    [ "caffe::LayerRegistry< Dtype >", "classcaffe_1_1_layer_registry.html", null ],
    [ "testing::internal::linked_ptr< T >", "classtesting_1_1internal_1_1linked__ptr.html", null ],
    [ "testing::internal::linked_ptr< const testing::internal::ParamGeneratorInterface< T > >", "classtesting_1_1internal_1_1linked__ptr.html", null ],
    [ "testing::internal::linked_ptr< const testing::internal::ParamGeneratorInterface< T1 > >", "classtesting_1_1internal_1_1linked__ptr.html", null ],
    [ "testing::internal::linked_ptr< const testing::internal::ParamGeneratorInterface< T10 > >", "classtesting_1_1internal_1_1linked__ptr.html", null ],
    [ "testing::internal::linked_ptr< const testing::internal::ParamGeneratorInterface< T2 > >", "classtesting_1_1internal_1_1linked__ptr.html", null ],
    [ "testing::internal::linked_ptr< const testing::internal::ParamGeneratorInterface< T3 > >", "classtesting_1_1internal_1_1linked__ptr.html", null ],
    [ "testing::internal::linked_ptr< const testing::internal::ParamGeneratorInterface< T4 > >", "classtesting_1_1internal_1_1linked__ptr.html", null ],
    [ "testing::internal::linked_ptr< const testing::internal::ParamGeneratorInterface< T5 > >", "classtesting_1_1internal_1_1linked__ptr.html", null ],
    [ "testing::internal::linked_ptr< const testing::internal::ParamGeneratorInterface< T6 > >", "classtesting_1_1internal_1_1linked__ptr.html", null ],
    [ "testing::internal::linked_ptr< const testing::internal::ParamGeneratorInterface< T7 > >", "classtesting_1_1internal_1_1linked__ptr.html", null ],
    [ "testing::internal::linked_ptr< const testing::internal::ParamGeneratorInterface< T8 > >", "classtesting_1_1internal_1_1linked__ptr.html", null ],
    [ "testing::internal::linked_ptr< const testing::internal::ParamGeneratorInterface< T9 > >", "classtesting_1_1internal_1_1linked__ptr.html", null ],
    [ "testing::internal::linked_ptr_internal", "classtesting_1_1internal_1_1linked__ptr__internal.html", null ],
    [ "testing::Message", "classtesting_1_1_message.html", null ],
    [ "Message", null, [
      [ "caffe::AccuracyParameter", "classcaffe_1_1_accuracy_parameter.html", null ],
      [ "caffe::AccuracyParameter", "classcaffe_1_1_accuracy_parameter.html", null ],
      [ "caffe::ArgMaxParameter", "classcaffe_1_1_arg_max_parameter.html", null ],
      [ "caffe::ArgMaxParameter", "classcaffe_1_1_arg_max_parameter.html", null ],
      [ "caffe::BatchNormParameter", "classcaffe_1_1_batch_norm_parameter.html", null ],
      [ "caffe::BatchNormParameter", "classcaffe_1_1_batch_norm_parameter.html", null ],
      [ "caffe::BiasParameter", "classcaffe_1_1_bias_parameter.html", null ],
      [ "caffe::BiasParameter", "classcaffe_1_1_bias_parameter.html", null ],
      [ "caffe::BlobProto", "classcaffe_1_1_blob_proto.html", null ],
      [ "caffe::BlobProto", "classcaffe_1_1_blob_proto.html", null ],
      [ "caffe::BlobProtoVector", "classcaffe_1_1_blob_proto_vector.html", null ],
      [ "caffe::BlobProtoVector", "classcaffe_1_1_blob_proto_vector.html", null ],
      [ "caffe::BlobShape", "classcaffe_1_1_blob_shape.html", null ],
      [ "caffe::BlobShape", "classcaffe_1_1_blob_shape.html", null ],
      [ "caffe::ConcatParameter", "classcaffe_1_1_concat_parameter.html", null ],
      [ "caffe::ConcatParameter", "classcaffe_1_1_concat_parameter.html", null ],
      [ "caffe::ContrastiveLossParameter", "classcaffe_1_1_contrastive_loss_parameter.html", null ],
      [ "caffe::ContrastiveLossParameter", "classcaffe_1_1_contrastive_loss_parameter.html", null ],
      [ "caffe::ConvolutionParameter", "classcaffe_1_1_convolution_parameter.html", null ],
      [ "caffe::ConvolutionParameter", "classcaffe_1_1_convolution_parameter.html", null ],
      [ "caffe::CropParameter", "classcaffe_1_1_crop_parameter.html", null ],
      [ "caffe::CropParameter", "classcaffe_1_1_crop_parameter.html", null ],
      [ "caffe::DataParameter", "classcaffe_1_1_data_parameter.html", null ],
      [ "caffe::DataParameter", "classcaffe_1_1_data_parameter.html", null ],
      [ "caffe::Datum", "classcaffe_1_1_datum.html", null ],
      [ "caffe::Datum", "classcaffe_1_1_datum.html", null ],
      [ "caffe::DropoutParameter", "classcaffe_1_1_dropout_parameter.html", null ],
      [ "caffe::DropoutParameter", "classcaffe_1_1_dropout_parameter.html", null ],
      [ "caffe::DummyDataParameter", "classcaffe_1_1_dummy_data_parameter.html", null ],
      [ "caffe::DummyDataParameter", "classcaffe_1_1_dummy_data_parameter.html", null ],
      [ "caffe::EltwiseParameter", "classcaffe_1_1_eltwise_parameter.html", null ],
      [ "caffe::EltwiseParameter", "classcaffe_1_1_eltwise_parameter.html", null ],
      [ "caffe::ELUParameter", "classcaffe_1_1_e_l_u_parameter.html", null ],
      [ "caffe::ELUParameter", "classcaffe_1_1_e_l_u_parameter.html", null ],
      [ "caffe::EmbedParameter", "classcaffe_1_1_embed_parameter.html", null ],
      [ "caffe::EmbedParameter", "classcaffe_1_1_embed_parameter.html", null ],
      [ "caffe::ExpParameter", "classcaffe_1_1_exp_parameter.html", null ],
      [ "caffe::ExpParameter", "classcaffe_1_1_exp_parameter.html", null ],
      [ "caffe::FillerParameter", "classcaffe_1_1_filler_parameter.html", null ],
      [ "caffe::FillerParameter", "classcaffe_1_1_filler_parameter.html", null ],
      [ "caffe::FlattenParameter", "classcaffe_1_1_flatten_parameter.html", null ],
      [ "caffe::FlattenParameter", "classcaffe_1_1_flatten_parameter.html", null ],
      [ "caffe::HDF5DataParameter", "classcaffe_1_1_h_d_f5_data_parameter.html", null ],
      [ "caffe::HDF5DataParameter", "classcaffe_1_1_h_d_f5_data_parameter.html", null ],
      [ "caffe::HDF5OutputParameter", "classcaffe_1_1_h_d_f5_output_parameter.html", null ],
      [ "caffe::HDF5OutputParameter", "classcaffe_1_1_h_d_f5_output_parameter.html", null ],
      [ "caffe::HingeLossParameter", "classcaffe_1_1_hinge_loss_parameter.html", null ],
      [ "caffe::HingeLossParameter", "classcaffe_1_1_hinge_loss_parameter.html", null ],
      [ "caffe::ImageDataParameter", "classcaffe_1_1_image_data_parameter.html", null ],
      [ "caffe::ImageDataParameter", "classcaffe_1_1_image_data_parameter.html", null ],
      [ "caffe::InfogainLossParameter", "classcaffe_1_1_infogain_loss_parameter.html", null ],
      [ "caffe::InfogainLossParameter", "classcaffe_1_1_infogain_loss_parameter.html", null ],
      [ "caffe::InnerProductParameter", "classcaffe_1_1_inner_product_parameter.html", null ],
      [ "caffe::InnerProductParameter", "classcaffe_1_1_inner_product_parameter.html", null ],
      [ "caffe::InputParameter", "classcaffe_1_1_input_parameter.html", null ],
      [ "caffe::InputParameter", "classcaffe_1_1_input_parameter.html", null ],
      [ "caffe::LayerParameter", "classcaffe_1_1_layer_parameter.html", null ],
      [ "caffe::LayerParameter", "classcaffe_1_1_layer_parameter.html", null ],
      [ "caffe::LogParameter", "classcaffe_1_1_log_parameter.html", null ],
      [ "caffe::LogParameter", "classcaffe_1_1_log_parameter.html", null ],
      [ "caffe::LossParameter", "classcaffe_1_1_loss_parameter.html", null ],
      [ "caffe::LossParameter", "classcaffe_1_1_loss_parameter.html", null ],
      [ "caffe::LRNParameter", "classcaffe_1_1_l_r_n_parameter.html", null ],
      [ "caffe::LRNParameter", "classcaffe_1_1_l_r_n_parameter.html", null ],
      [ "caffe::MemoryDataParameter", "classcaffe_1_1_memory_data_parameter.html", null ],
      [ "caffe::MemoryDataParameter", "classcaffe_1_1_memory_data_parameter.html", null ],
      [ "caffe::MVNParameter", "classcaffe_1_1_m_v_n_parameter.html", null ],
      [ "caffe::MVNParameter", "classcaffe_1_1_m_v_n_parameter.html", null ],
      [ "caffe::NetParameter", "classcaffe_1_1_net_parameter.html", null ],
      [ "caffe::NetParameter", "classcaffe_1_1_net_parameter.html", null ],
      [ "caffe::NetState", "classcaffe_1_1_net_state.html", null ],
      [ "caffe::NetState", "classcaffe_1_1_net_state.html", null ],
      [ "caffe::NetStateRule", "classcaffe_1_1_net_state_rule.html", null ],
      [ "caffe::NetStateRule", "classcaffe_1_1_net_state_rule.html", null ],
      [ "caffe::ParameterParameter", "classcaffe_1_1_parameter_parameter.html", null ],
      [ "caffe::ParameterParameter", "classcaffe_1_1_parameter_parameter.html", null ],
      [ "caffe::ParamSpec", "classcaffe_1_1_param_spec.html", null ],
      [ "caffe::ParamSpec", "classcaffe_1_1_param_spec.html", null ],
      [ "caffe::PoolingParameter", "classcaffe_1_1_pooling_parameter.html", null ],
      [ "caffe::PoolingParameter", "classcaffe_1_1_pooling_parameter.html", null ],
      [ "caffe::PowerParameter", "classcaffe_1_1_power_parameter.html", null ],
      [ "caffe::PowerParameter", "classcaffe_1_1_power_parameter.html", null ],
      [ "caffe::PReLUParameter", "classcaffe_1_1_p_re_l_u_parameter.html", null ],
      [ "caffe::PReLUParameter", "classcaffe_1_1_p_re_l_u_parameter.html", null ],
      [ "caffe::PythonParameter", "classcaffe_1_1_python_parameter.html", null ],
      [ "caffe::PythonParameter", "classcaffe_1_1_python_parameter.html", null ],
      [ "caffe::RecurrentParameter", "classcaffe_1_1_recurrent_parameter.html", null ],
      [ "caffe::RecurrentParameter", "classcaffe_1_1_recurrent_parameter.html", null ],
      [ "caffe::ReductionParameter", "classcaffe_1_1_reduction_parameter.html", null ],
      [ "caffe::ReductionParameter", "classcaffe_1_1_reduction_parameter.html", null ],
      [ "caffe::ReLUParameter", "classcaffe_1_1_re_l_u_parameter.html", null ],
      [ "caffe::ReLUParameter", "classcaffe_1_1_re_l_u_parameter.html", null ],
      [ "caffe::ReshapeParameter", "classcaffe_1_1_reshape_parameter.html", null ],
      [ "caffe::ReshapeParameter", "classcaffe_1_1_reshape_parameter.html", null ],
      [ "caffe::ScaleParameter", "classcaffe_1_1_scale_parameter.html", null ],
      [ "caffe::ScaleParameter", "classcaffe_1_1_scale_parameter.html", null ],
      [ "caffe::SigmoidParameter", "classcaffe_1_1_sigmoid_parameter.html", null ],
      [ "caffe::SigmoidParameter", "classcaffe_1_1_sigmoid_parameter.html", null ],
      [ "caffe::SliceParameter", "classcaffe_1_1_slice_parameter.html", null ],
      [ "caffe::SliceParameter", "classcaffe_1_1_slice_parameter.html", null ],
      [ "caffe::SoftmaxParameter", "classcaffe_1_1_softmax_parameter.html", null ],
      [ "caffe::SoftmaxParameter", "classcaffe_1_1_softmax_parameter.html", null ],
      [ "caffe::SolverParameter", "classcaffe_1_1_solver_parameter.html", null ],
      [ "caffe::SolverParameter", "classcaffe_1_1_solver_parameter.html", null ],
      [ "caffe::SolverState", "classcaffe_1_1_solver_state.html", null ],
      [ "caffe::SolverState", "classcaffe_1_1_solver_state.html", null ],
      [ "caffe::SPPParameter", "classcaffe_1_1_s_p_p_parameter.html", null ],
      [ "caffe::SPPParameter", "classcaffe_1_1_s_p_p_parameter.html", null ],
      [ "caffe::SwishParameter", "classcaffe_1_1_swish_parameter.html", null ],
      [ "caffe::SwishParameter", "classcaffe_1_1_swish_parameter.html", null ],
      [ "caffe::TanHParameter", "classcaffe_1_1_tan_h_parameter.html", null ],
      [ "caffe::TanHParameter", "classcaffe_1_1_tan_h_parameter.html", null ],
      [ "caffe::ThresholdParameter", "classcaffe_1_1_threshold_parameter.html", null ],
      [ "caffe::ThresholdParameter", "classcaffe_1_1_threshold_parameter.html", null ],
      [ "caffe::TileParameter", "classcaffe_1_1_tile_parameter.html", null ],
      [ "caffe::TileParameter", "classcaffe_1_1_tile_parameter.html", null ],
      [ "caffe::TransformationParameter", "classcaffe_1_1_transformation_parameter.html", null ],
      [ "caffe::TransformationParameter", "classcaffe_1_1_transformation_parameter.html", null ],
      [ "caffe::V0LayerParameter", "classcaffe_1_1_v0_layer_parameter.html", null ],
      [ "caffe::V0LayerParameter", "classcaffe_1_1_v0_layer_parameter.html", null ],
      [ "caffe::V1LayerParameter", "classcaffe_1_1_v1_layer_parameter.html", null ],
      [ "caffe::V1LayerParameter", "classcaffe_1_1_v1_layer_parameter.html", null ],
      [ "caffe::WindowDataParameter", "classcaffe_1_1_window_data_parameter.html", null ],
      [ "caffe::WindowDataParameter", "classcaffe_1_1_window_data_parameter.html", null ]
    ] ],
    [ "testing::internal::Mutex", "classtesting_1_1internal_1_1_mutex.html", null ],
    [ "testing::internal::NativeArray< Element >", "classtesting_1_1internal_1_1_native_array.html", null ],
    [ "caffe::NCCL< Dtype >", "classcaffe_1_1_n_c_c_l.html", null ],
    [ "caffe::NdarrayConverterGenerator", "structcaffe_1_1_ndarray_converter_generator.html", null ],
    [ "caffe::Net< Dtype >", "classcaffe_1_1_net.html", [
      [ "caffe.classifier.Classifier", "classcaffe_1_1classifier_1_1_classifier.html", null ],
      [ "caffe.classifier.Classifier", "classcaffe_1_1classifier_1_1_classifier.html", null ],
      [ "caffe.detector.Detector", "classcaffe_1_1detector_1_1_detector.html", null ],
      [ "caffe.detector.Detector", "classcaffe_1_1detector_1_1_detector.html", null ]
    ] ],
    [ "object", null, [
      [ "app.ImagenetClassifier", "classapp_1_1_imagenet_classifier.html", null ],
      [ "caffe.net_spec.Function", "classcaffe_1_1net__spec_1_1_function.html", null ],
      [ "caffe.net_spec.Function", "classcaffe_1_1net__spec_1_1_function.html", null ],
      [ "caffe.net_spec.Layers", "classcaffe_1_1net__spec_1_1_layers.html", null ],
      [ "caffe.net_spec.Layers", "classcaffe_1_1net__spec_1_1_layers.html", null ],
      [ "caffe.net_spec.NetSpec", "classcaffe_1_1net__spec_1_1_net_spec.html", null ],
      [ "caffe.net_spec.NetSpec", "classcaffe_1_1net__spec_1_1_net_spec.html", null ],
      [ "caffe.net_spec.Parameters", "classcaffe_1_1net__spec_1_1_parameters.html", null ],
      [ "caffe.net_spec.Parameters", "classcaffe_1_1net__spec_1_1_parameters.html", null ],
      [ "caffe.net_spec.Top", "classcaffe_1_1net__spec_1_1_top.html", null ],
      [ "caffe.net_spec.Top", "classcaffe_1_1net__spec_1_1_top.html", null ],
      [ "cpp_lint._BlockInfo", "classcpp__lint_1_1___block_info.html", [
        [ "cpp_lint._ClassInfo", "classcpp__lint_1_1___class_info.html", null ],
        [ "cpp_lint._NamespaceInfo", "classcpp__lint_1_1___namespace_info.html", null ]
      ] ],
      [ "cpp_lint._CppLintState", "classcpp__lint_1_1___cpp_lint_state.html", null ],
      [ "cpp_lint._FunctionState", "classcpp__lint_1_1___function_state.html", null ],
      [ "cpp_lint._NestingState", "classcpp__lint_1_1___nesting_state.html", null ],
      [ "cpp_lint._PreprocessorInfo", "classcpp__lint_1_1___preprocessor_info.html", null ],
      [ "cpp_lint.CleansedLines", "classcpp__lint_1_1_cleansed_lines.html", null ],
      [ "pascal_multilabel_datalayers.BatchLoader", "classpascal__multilabel__datalayers_1_1_batch_loader.html", null ]
    ] ],
    [ "resize_and_crop_images.OpenCVResizeCrop", "classresize__and__crop__images_1_1_open_c_v_resize_crop.html", null ],
    [ "testing::internal::OsStackTraceGetterInterface", "classtesting_1_1internal_1_1_os_stack_trace_getter_interface.html", [
      [ "testing::internal::OsStackTraceGetter", "classtesting_1_1internal_1_1_os_stack_trace_getter.html", null ]
    ] ],
    [ "testing::internal::ParameterizedTestCaseInfoBase", "classtesting_1_1internal_1_1_parameterized_test_case_info_base.html", [
      [ "testing::internal::ParameterizedTestCaseInfo< TestCase >", "classtesting_1_1internal_1_1_parameterized_test_case_info.html", null ]
    ] ],
    [ "testing::internal::ParameterizedTestCaseRegistry", "classtesting_1_1internal_1_1_parameterized_test_case_registry.html", null ],
    [ "testing::internal::ParamGenerator< T >", "classtesting_1_1internal_1_1_param_generator.html", null ],
    [ "testing::internal::ParamGenerator< T1 >", "classtesting_1_1internal_1_1_param_generator.html", null ],
    [ "testing::internal::ParamGenerator< T10 >", "classtesting_1_1internal_1_1_param_generator.html", null ],
    [ "testing::internal::ParamGenerator< T2 >", "classtesting_1_1internal_1_1_param_generator.html", null ],
    [ "testing::internal::ParamGenerator< T3 >", "classtesting_1_1internal_1_1_param_generator.html", null ],
    [ "testing::internal::ParamGenerator< T4 >", "classtesting_1_1internal_1_1_param_generator.html", null ],
    [ "testing::internal::ParamGenerator< T5 >", "classtesting_1_1internal_1_1_param_generator.html", null ],
    [ "testing::internal::ParamGenerator< T6 >", "classtesting_1_1internal_1_1_param_generator.html", null ],
    [ "testing::internal::ParamGenerator< T7 >", "classtesting_1_1internal_1_1_param_generator.html", null ],
    [ "testing::internal::ParamGenerator< T8 >", "classtesting_1_1internal_1_1_param_generator.html", null ],
    [ "testing::internal::ParamGenerator< T9 >", "classtesting_1_1internal_1_1_param_generator.html", null ],
    [ "testing::internal::ParamGeneratorInterface< T >", "classtesting_1_1internal_1_1_param_generator_interface.html", [
      [ "testing::internal::RangeGenerator< T, IncrementT >", "classtesting_1_1internal_1_1_range_generator.html", null ],
      [ "testing::internal::ValuesInIteratorRangeGenerator< T >", "classtesting_1_1internal_1_1_values_in_iterator_range_generator.html", null ]
    ] ],
    [ "testing::internal::ParamGeneratorInterface< ::std::tr1::tuple< T1, T2 > >", "classtesting_1_1internal_1_1_param_generator_interface.html", [
      [ "testing::internal::CartesianProductGenerator2< T1, T2 >", "classtesting_1_1internal_1_1_cartesian_product_generator2.html", null ]
    ] ],
    [ "testing::internal::ParamGeneratorInterface< ::std::tr1::tuple< T1, T2, T3 > >", "classtesting_1_1internal_1_1_param_generator_interface.html", [
      [ "testing::internal::CartesianProductGenerator3< T1, T2, T3 >", "classtesting_1_1internal_1_1_cartesian_product_generator3.html", null ]
    ] ],
    [ "testing::internal::ParamGeneratorInterface< ::std::tr1::tuple< T1, T2, T3, T4 > >", "classtesting_1_1internal_1_1_param_generator_interface.html", [
      [ "testing::internal::CartesianProductGenerator4< T1, T2, T3, T4 >", "classtesting_1_1internal_1_1_cartesian_product_generator4.html", null ]
    ] ],
    [ "testing::internal::ParamGeneratorInterface< ::std::tr1::tuple< T1, T2, T3, T4, T5 > >", "classtesting_1_1internal_1_1_param_generator_interface.html", [
      [ "testing::internal::CartesianProductGenerator5< T1, T2, T3, T4, T5 >", "classtesting_1_1internal_1_1_cartesian_product_generator5.html", null ]
    ] ],
    [ "testing::internal::ParamGeneratorInterface< ::std::tr1::tuple< T1, T2, T3, T4, T5, T6 > >", "classtesting_1_1internal_1_1_param_generator_interface.html", [
      [ "testing::internal::CartesianProductGenerator6< T1, T2, T3, T4, T5, T6 >", "classtesting_1_1internal_1_1_cartesian_product_generator6.html", null ]
    ] ],
    [ "testing::internal::ParamGeneratorInterface< ::std::tr1::tuple< T1, T2, T3, T4, T5, T6, T7 > >", "classtesting_1_1internal_1_1_param_generator_interface.html", [
      [ "testing::internal::CartesianProductGenerator7< T1, T2, T3, T4, T5, T6, T7 >", "classtesting_1_1internal_1_1_cartesian_product_generator7.html", null ]
    ] ],
    [ "testing::internal::ParamGeneratorInterface< ::std::tr1::tuple< T1, T2, T3, T4, T5, T6, T7, T8 > >", "classtesting_1_1internal_1_1_param_generator_interface.html", [
      [ "testing::internal::CartesianProductGenerator8< T1, T2, T3, T4, T5, T6, T7, T8 >", "classtesting_1_1internal_1_1_cartesian_product_generator8.html", null ]
    ] ],
    [ "testing::internal::ParamGeneratorInterface< ::std::tr1::tuple< T1, T2, T3, T4, T5, T6, T7, T8, T9 > >", "classtesting_1_1internal_1_1_param_generator_interface.html", [
      [ "testing::internal::CartesianProductGenerator9< T1, T2, T3, T4, T5, T6, T7, T8, T9 >", "classtesting_1_1internal_1_1_cartesian_product_generator9.html", null ]
    ] ],
    [ "testing::internal::ParamGeneratorInterface< ::std::tr1::tuple< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10 > >", "classtesting_1_1internal_1_1_param_generator_interface.html", [
      [ "testing::internal::CartesianProductGenerator10< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10 >", "classtesting_1_1internal_1_1_cartesian_product_generator10.html", null ]
    ] ],
    [ "testing::internal::ParamGeneratorInterface< std::tr1::tuple >", "classtesting_1_1internal_1_1_param_generator_interface.html", null ],
    [ "testing::internal::ParamGeneratorInterface< T1 >", "classtesting_1_1internal_1_1_param_generator_interface.html", null ],
    [ "testing::internal::ParamGeneratorInterface< T10 >", "classtesting_1_1internal_1_1_param_generator_interface.html", null ],
    [ "testing::internal::ParamGeneratorInterface< T2 >", "classtesting_1_1internal_1_1_param_generator_interface.html", null ],
    [ "testing::internal::ParamGeneratorInterface< T3 >", "classtesting_1_1internal_1_1_param_generator_interface.html", null ],
    [ "testing::internal::ParamGeneratorInterface< T4 >", "classtesting_1_1internal_1_1_param_generator_interface.html", null ],
    [ "testing::internal::ParamGeneratorInterface< T5 >", "classtesting_1_1internal_1_1_param_generator_interface.html", null ],
    [ "testing::internal::ParamGeneratorInterface< T6 >", "classtesting_1_1internal_1_1_param_generator_interface.html", null ],
    [ "testing::internal::ParamGeneratorInterface< T7 >", "classtesting_1_1internal_1_1_param_generator_interface.html", null ],
    [ "testing::internal::ParamGeneratorInterface< T8 >", "classtesting_1_1internal_1_1_param_generator_interface.html", null ],
    [ "testing::internal::ParamGeneratorInterface< T9 >", "classtesting_1_1internal_1_1_param_generator_interface.html", null ],
    [ "testing::internal::ParamIterator< T >", "classtesting_1_1internal_1_1_param_iterator.html", null ],
    [ "testing::internal::ParamIteratorInterface< T >", "classtesting_1_1internal_1_1_param_iterator_interface.html", null ],
    [ "testing::internal::ParamIteratorInterface< ParamType >", "classtesting_1_1internal_1_1_param_iterator_interface.html", null ],
    [ "resize_and_crop_images.PILResizeCrop", "classresize__and__crop__images_1_1_p_i_l_resize_crop.html", null ],
    [ "testing::internal::Random", "classtesting_1_1internal_1_1_random.html", null ],
    [ "testing::internal::RE", "classtesting_1_1internal_1_1_r_e.html", null ],
    [ "testing::internal::RemoveConst< T >", "structtesting_1_1internal_1_1_remove_const.html", null ],
    [ "testing::internal::RemoveConst< const T >", "structtesting_1_1internal_1_1_remove_const_3_01const_01_t_01_4.html", null ],
    [ "testing::internal::RemoveReference< T >", "structtesting_1_1internal_1_1_remove_reference.html", null ],
    [ "testing::internal::RemoveReference< T & >", "structtesting_1_1internal_1_1_remove_reference_3_01_t_01_6_01_4.html", null ],
    [ "caffe::Caffe::RNG", "classcaffe_1_1_caffe_1_1_r_n_g.html", null ],
    [ "std::tr1::gtest_internal::SameSizeTuplePrefixComparator< kSize1, kSize2 >", "structstd_1_1tr1_1_1gtest__internal_1_1_same_size_tuple_prefix_comparator.html", null ],
    [ "std::tr1::gtest_internal::SameSizeTuplePrefixComparator< 0, 0 >", "structstd_1_1tr1_1_1gtest__internal_1_1_same_size_tuple_prefix_comparator_3_010_00_010_01_4.html", null ],
    [ "std::tr1::gtest_internal::SameSizeTuplePrefixComparator< k, k >", "structstd_1_1tr1_1_1gtest__internal_1_1_same_size_tuple_prefix_comparator_3_01k_00_01k_01_4.html", null ],
    [ "testing::internal::scoped_ptr< T >", "classtesting_1_1internal_1_1scoped__ptr.html", null ],
    [ "testing::internal::scoped_ptr< ::std::string >", "classtesting_1_1internal_1_1scoped__ptr.html", null ],
    [ "testing::internal::scoped_ptr< ::std::stringstream >", "classtesting_1_1internal_1_1scoped__ptr.html", null ],
    [ "testing::internal::scoped_ptr< const ::std::string >", "classtesting_1_1internal_1_1scoped__ptr.html", null ],
    [ "testing::internal::scoped_ptr< const T >", "classtesting_1_1internal_1_1scoped__ptr.html", null ],
    [ "testing::internal::scoped_ptr< testing::internal::ParamIteratorInterface< T > >", "classtesting_1_1internal_1_1scoped__ptr.html", null ],
    [ "testing::internal::scoped_ptr< testing::internal::TestMetaFactoryBase< ParamType > >", "classtesting_1_1internal_1_1scoped__ptr.html", null ],
    [ "testing::internal::ScopedTrace", "classtesting_1_1internal_1_1_scoped_trace.html", null ],
    [ "caffe::SignalHandler", "classcaffe_1_1_signal_handler.html", null ],
    [ "tools.SimpleTransformer", "classtools_1_1_simple_transformer.html", null ],
    [ "testing::internal::SingleFailureChecker", "classtesting_1_1internal_1_1_single_failure_checker.html", null ],
    [ "caffe::Solver< Dtype >", "classcaffe_1_1_solver.html", [
      [ "caffe::SGDSolver< Dtype >", "classcaffe_1_1_s_g_d_solver.html", [
        [ "caffe::AdaDeltaSolver< Dtype >", "classcaffe_1_1_ada_delta_solver.html", null ],
        [ "caffe::AdaDeltaSolver< Dtype >", "classcaffe_1_1_ada_delta_solver.html", null ],
        [ "caffe::AdaGradSolver< Dtype >", "classcaffe_1_1_ada_grad_solver.html", null ],
        [ "caffe::AdaGradSolver< Dtype >", "classcaffe_1_1_ada_grad_solver.html", null ],
        [ "caffe::AdamSolver< Dtype >", "classcaffe_1_1_adam_solver.html", null ],
        [ "caffe::AdamSolver< Dtype >", "classcaffe_1_1_adam_solver.html", null ],
        [ "caffe::NesterovSolver< Dtype >", "classcaffe_1_1_nesterov_solver.html", null ],
        [ "caffe::NesterovSolver< Dtype >", "classcaffe_1_1_nesterov_solver.html", null ],
        [ "caffe::RMSPropSolver< Dtype >", "classcaffe_1_1_r_m_s_prop_solver.html", null ],
        [ "caffe::RMSPropSolver< Dtype >", "classcaffe_1_1_r_m_s_prop_solver.html", null ]
      ] ],
      [ "caffe::SGDSolver< Dtype >", "classcaffe_1_1_s_g_d_solver.html", null ]
    ] ],
    [ "caffe::SolverRegisterer< Dtype >", "classcaffe_1_1_solver_registerer.html", null ],
    [ "caffe::SolverRegistry< Dtype >", "classcaffe_1_1_solver_registry.html", null ],
    [ "testing::internal::StaticAssertTypeEqHelper< T1, T2 >", "structtesting_1_1internal_1_1_static_assert_type_eq_helper.html", null ],
    [ "testing::internal::StaticAssertTypeEqHelper< T, T >", "structtesting_1_1internal_1_1_static_assert_type_eq_helper_3_01_t_00_01_t_01_4.html", null ],
    [ "caffe::StaticDescriptorInitializer_caffe_2eproto", "structcaffe_1_1_static_descriptor_initializer__caffe__2eproto.html", null ],
    [ "testing::internal::String", "classtesting_1_1internal_1_1_string.html", null ],
    [ "caffe::BlockingQueue< T >::sync", "classcaffe_1_1_blocking_queue_1_1sync.html", null ],
    [ "caffe::SyncedMemory", "classcaffe_1_1_synced_memory.html", null ],
    [ "testing::Test", "classtesting_1_1_test.html", [
      [ "caffe::BilinearFillerTest< Dtype >", "classcaffe_1_1_bilinear_filler_test.html", null ],
      [ "caffe::BlobSimpleTest< Dtype >", "classcaffe_1_1_blob_simple_test.html", null ],
      [ "caffe::CommonTest", "classcaffe_1_1_common_test.html", null ],
      [ "caffe::ConstantFillerTest< Dtype >", "classcaffe_1_1_constant_filler_test.html", null ],
      [ "caffe::FilterNetTest", "classcaffe_1_1_filter_net_test.html", null ],
      [ "caffe::GaussianFillerTest< Dtype >", "classcaffe_1_1_gaussian_filler_test.html", null ],
      [ "caffe::GemmTest< TypeParam >", "classcaffe_1_1_gemm_test.html", null ],
      [ "caffe::InternalThreadTest", "classcaffe_1_1_internal_thread_test.html", null ],
      [ "caffe::MSRAFillerTest< Dtype >", "classcaffe_1_1_m_s_r_a_filler_test.html", null ],
      [ "caffe::MultiDeviceTest< TypeParam >", "classcaffe_1_1_multi_device_test.html", [
        [ "caffe::AccuracyLayerTest< TypeParam >", "classcaffe_1_1_accuracy_layer_test.html", null ],
        [ "caffe::BatchNormLayerTest< TypeParam >", "classcaffe_1_1_batch_norm_layer_test.html", null ],
        [ "caffe::BatchReindexLayerTest< TypeParam >", "classcaffe_1_1_batch_reindex_layer_test.html", null ],
        [ "caffe::BenchmarkTest< TypeParam >", "classcaffe_1_1_benchmark_test.html", null ],
        [ "caffe::BiasLayerTest< TypeParam >", "classcaffe_1_1_bias_layer_test.html", null ],
        [ "caffe::BlobMathTest< TypeParam >", "classcaffe_1_1_blob_math_test.html", null ],
        [ "caffe::ConcatLayerTest< TypeParam >", "classcaffe_1_1_concat_layer_test.html", null ],
        [ "caffe::ContrastiveLossLayerTest< TypeParam >", "classcaffe_1_1_contrastive_loss_layer_test.html", null ],
        [ "caffe::ConvolutionLayerTest< TypeParam >", "classcaffe_1_1_convolution_layer_test.html", null ],
        [ "caffe::CropLayerTest< TypeParam >", "classcaffe_1_1_crop_layer_test.html", null ],
        [ "caffe::DeconvolutionLayerTest< TypeParam >", "classcaffe_1_1_deconvolution_layer_test.html", null ],
        [ "caffe::EltwiseLayerTest< TypeParam >", "classcaffe_1_1_eltwise_layer_test.html", null ],
        [ "caffe::EmbedLayerTest< TypeParam >", "classcaffe_1_1_embed_layer_test.html", null ],
        [ "caffe::EuclideanLossLayerTest< TypeParam >", "classcaffe_1_1_euclidean_loss_layer_test.html", null ],
        [ "caffe::FilterLayerTest< TypeParam >", "classcaffe_1_1_filter_layer_test.html", null ],
        [ "caffe::FlattenLayerTest< TypeParam >", "classcaffe_1_1_flatten_layer_test.html", null ],
        [ "caffe::GradientBasedSolverTest< TypeParam >", "classcaffe_1_1_gradient_based_solver_test.html", [
          [ "caffe::AdaDeltaSolverTest< TypeParam >", "classcaffe_1_1_ada_delta_solver_test.html", null ],
          [ "caffe::AdaGradSolverTest< TypeParam >", "classcaffe_1_1_ada_grad_solver_test.html", null ],
          [ "caffe::AdamSolverTest< TypeParam >", "classcaffe_1_1_adam_solver_test.html", null ],
          [ "caffe::NesterovSolverTest< TypeParam >", "classcaffe_1_1_nesterov_solver_test.html", null ],
          [ "caffe::RMSPropSolverTest< TypeParam >", "classcaffe_1_1_r_m_s_prop_solver_test.html", null ],
          [ "caffe::SGDSolverTest< TypeParam >", "classcaffe_1_1_s_g_d_solver_test.html", null ]
        ] ],
        [ "caffe::HDF5DataLayerTest< TypeParam >", "classcaffe_1_1_h_d_f5_data_layer_test.html", null ],
        [ "caffe::HDF5OutputLayerTest< TypeParam >", "classcaffe_1_1_h_d_f5_output_layer_test.html", null ],
        [ "caffe::HingeLossLayerTest< TypeParam >", "classcaffe_1_1_hinge_loss_layer_test.html", null ],
        [ "caffe::Im2colLayerTest< TypeParam >", "classcaffe_1_1_im2col_layer_test.html", null ],
        [ "caffe::InfogainLossLayerTest< TypeParam >", "classcaffe_1_1_infogain_loss_layer_test.html", null ],
        [ "caffe::InnerProductLayerTest< TypeParam >", "classcaffe_1_1_inner_product_layer_test.html", null ],
        [ "caffe::LayerFactoryTest< TypeParam >", "classcaffe_1_1_layer_factory_test.html", null ],
        [ "caffe::LRNLayerTest< TypeParam >", "classcaffe_1_1_l_r_n_layer_test.html", null ],
        [ "caffe::LSTMLayerTest< TypeParam >", "classcaffe_1_1_l_s_t_m_layer_test.html", null ],
        [ "caffe::MathFunctionsTest< TypeParam >", "classcaffe_1_1_math_functions_test.html", null ],
        [ "caffe::MaxPoolingDropoutTest< TypeParam >", "classcaffe_1_1_max_pooling_dropout_test.html", null ],
        [ "caffe::MemoryDataLayerTest< TypeParam >", "classcaffe_1_1_memory_data_layer_test.html", null ],
        [ "caffe::MVNLayerTest< TypeParam >", "classcaffe_1_1_m_v_n_layer_test.html", null ],
        [ "caffe::NetTest< TypeParam >", "classcaffe_1_1_net_test.html", null ],
        [ "caffe::NeuronLayerTest< TypeParam >", "classcaffe_1_1_neuron_layer_test.html", null ],
        [ "caffe::PoolingLayerTest< TypeParam >", "classcaffe_1_1_pooling_layer_test.html", null ],
        [ "caffe::PowerLayerTest< TypeParam >", "classcaffe_1_1_power_layer_test.html", null ],
        [ "caffe::ReductionLayerTest< TypeParam >", "classcaffe_1_1_reduction_layer_test.html", null ],
        [ "caffe::ReshapeLayerTest< TypeParam >", "classcaffe_1_1_reshape_layer_test.html", null ],
        [ "caffe::RNNLayerTest< TypeParam >", "classcaffe_1_1_r_n_n_layer_test.html", null ],
        [ "caffe::ScaleLayerTest< TypeParam >", "classcaffe_1_1_scale_layer_test.html", null ],
        [ "caffe::SigmoidCrossEntropyLossLayerTest< TypeParam >", "classcaffe_1_1_sigmoid_cross_entropy_loss_layer_test.html", null ],
        [ "caffe::SliceLayerTest< TypeParam >", "classcaffe_1_1_slice_layer_test.html", null ],
        [ "caffe::SoftmaxLayerTest< TypeParam >", "classcaffe_1_1_softmax_layer_test.html", null ],
        [ "caffe::SoftmaxWithLossLayerTest< TypeParam >", "classcaffe_1_1_softmax_with_loss_layer_test.html", null ],
        [ "caffe::SolverFactoryTest< TypeParam >", "classcaffe_1_1_solver_factory_test.html", null ],
        [ "caffe::SolverTest< TypeParam >", "classcaffe_1_1_solver_test.html", null ],
        [ "caffe::SplitLayerTest< TypeParam >", "classcaffe_1_1_split_layer_test.html", null ],
        [ "caffe::SPPLayerTest< TypeParam >", "classcaffe_1_1_s_p_p_layer_test.html", null ],
        [ "caffe::StochasticPoolingLayerTest< TypeParam >", "classcaffe_1_1_stochastic_pooling_layer_test.html", null ],
        [ "caffe::TanHLayerTest< TypeParam >", "classcaffe_1_1_tan_h_layer_test.html", null ],
        [ "caffe::ThresholdLayerTest< TypeParam >", "classcaffe_1_1_threshold_layer_test.html", null ],
        [ "caffe::TileLayerTest< TypeParam >", "classcaffe_1_1_tile_layer_test.html", null ]
      ] ],
      [ "caffe::MultiDeviceTest< TypeParam >", "classcaffe_1_1_multi_device_test.html", null ],
      [ "caffe::NetUpgradeTest", "classcaffe_1_1_net_upgrade_test.html", null ],
      [ "caffe::PaddingLayerUpgradeTest", "classcaffe_1_1_padding_layer_upgrade_test.html", null ],
      [ "caffe::PlatformTest", "classcaffe_1_1_platform_test.html", null ],
      [ "caffe::PositiveUnitballFillerTest< Dtype >", "classcaffe_1_1_positive_unitball_filler_test.html", null ],
      [ "caffe::ProtoTest", "classcaffe_1_1_proto_test.html", null ],
      [ "caffe::RandomNumberGeneratorTest< Dtype >", "classcaffe_1_1_random_number_generator_test.html", null ],
      [ "caffe::SolverTypeUpgradeTest", "classcaffe_1_1_solver_type_upgrade_test.html", null ],
      [ "caffe::SplitLayerInsertionTest", "classcaffe_1_1_split_layer_insertion_test.html", null ],
      [ "caffe::SyncedMemoryTest", "classcaffe_1_1_synced_memory_test.html", null ],
      [ "caffe::UniformFillerTest< Dtype >", "classcaffe_1_1_uniform_filler_test.html", null ],
      [ "caffe::XavierFillerTest< Dtype >", "classcaffe_1_1_xavier_filler_test.html", null ],
      [ "caffe::MultiDeviceTest< CPUDevice< Dtype > >", "classcaffe_1_1_multi_device_test.html", [
        [ "caffe::CPUDeviceTest< Dtype >", "classcaffe_1_1_c_p_u_device_test.html", [
          [ "caffe::ArgMaxLayerTest< Dtype >", "classcaffe_1_1_arg_max_layer_test.html", null ],
          [ "caffe::DummyDataLayerTest< Dtype >", "classcaffe_1_1_dummy_data_layer_test.html", null ],
          [ "caffe::MultinomialLogisticLossLayerTest< Dtype >", "classcaffe_1_1_multinomial_logistic_loss_layer_test.html", null ]
        ] ],
        [ "caffe::CPUDeviceTest< Dtype >", "classcaffe_1_1_c_p_u_device_test.html", null ],
        [ "caffe::MathFunctionsTest< CPUDevice< Dtype > >", "classcaffe_1_1_math_functions_test.html", [
          [ "caffe::CPUMathFunctionsTest< Dtype >", "classcaffe_1_1_c_p_u_math_functions_test.html", null ]
        ] ],
        [ "caffe::StochasticPoolingLayerTest< CPUDevice< Dtype > >", "classcaffe_1_1_stochastic_pooling_layer_test.html", [
          [ "caffe::CPUStochasticPoolingLayerTest< Dtype >", "classcaffe_1_1_c_p_u_stochastic_pooling_layer_test.html", null ]
        ] ]
      ] ],
      [ "caffe::MultiDeviceTest< CPUDevice< Dtype > >", "classcaffe_1_1_multi_device_test.html", null ],
      [ "caffe::MultiDeviceTest< CPUDevice< TypeParam > >", "classcaffe_1_1_multi_device_test.html", [
        [ "caffe::CPUDeviceTest< TypeParam >", "classcaffe_1_1_c_p_u_device_test.html", [
          [ "caffe::WeightedEuclideanLossLayerTest< TypeParam >", "classcaffe_1_1_weighted_euclidean_loss_layer_test.html", null ]
        ] ],
        [ "caffe::CPUDeviceTest< TypeParam >", "classcaffe_1_1_c_p_u_device_test.html", null ]
      ] ],
      [ "caffe::MultiDeviceTest< CPUDevice< TypeParam > >", "classcaffe_1_1_multi_device_test.html", null ],
      [ "caffe::MultiDeviceTest< GPUDevice< Dtype > >", "classcaffe_1_1_multi_device_test.html", [
        [ "caffe::GPUDeviceTest< Dtype >", "classcaffe_1_1_g_p_u_device_test.html", null ],
        [ "caffe::GPUDeviceTest< Dtype >", "classcaffe_1_1_g_p_u_device_test.html", null ],
        [ "caffe::MathFunctionsTest< GPUDevice< Dtype > >", "classcaffe_1_1_math_functions_test.html", [
          [ "caffe::GPUMathFunctionsTest< Dtype >", "classcaffe_1_1_g_p_u_math_functions_test.html", null ]
        ] ],
        [ "caffe::StochasticPoolingLayerTest< GPUDevice< Dtype > >", "classcaffe_1_1_stochastic_pooling_layer_test.html", [
          [ "caffe::GPUStochasticPoolingLayerTest< Dtype >", "classcaffe_1_1_g_p_u_stochastic_pooling_layer_test.html", null ]
        ] ]
      ] ],
      [ "caffe::MultiDeviceTest< GPUDevice< Dtype > >", "classcaffe_1_1_multi_device_test.html", null ],
      [ "testing::TestWithParam< T >", "classtesting_1_1_test_with_param.html", null ]
    ] ],
    [ "TestCase", null, [
      [ "test_coord_map.TestCoordMap", "classtest__coord__map_1_1_test_coord_map.html", null ],
      [ "test_draw.TestDraw", "classtest__draw_1_1_test_draw.html", null ],
      [ "test_io.TestArrayToDatum", "classtest__io_1_1_test_array_to_datum.html", null ],
      [ "test_io.TestBlobProtoToArray", "classtest__io_1_1_test_blob_proto_to_array.html", null ],
      [ "test_layer_type_list.TestLayerTypeList", "classtest__layer__type__list_1_1_test_layer_type_list.html", null ],
      [ "test_nccl.TestNCCL", "classtest__nccl_1_1_test_n_c_c_l.html", null ],
      [ "test_net.TestAllInOne", "classtest__net_1_1_test_all_in_one.html", null ],
      [ "test_net.TestLevels", "classtest__net_1_1_test_levels.html", null ],
      [ "test_net.TestNet", "classtest__net_1_1_test_net.html", null ],
      [ "test_net.TestStages", "classtest__net_1_1_test_stages.html", null ],
      [ "test_net_spec.TestNetSpec", "classtest__net__spec_1_1_test_net_spec.html", null ],
      [ "test_python_layer.TestPythonLayer", "classtest__python__layer_1_1_test_python_layer.html", null ],
      [ "test_python_layer_with_param_str.TestLayerWithParam", "classtest__python__layer__with__param__str_1_1_test_layer_with_param.html", null ],
      [ "test_solver.TestSolver", "classtest__solver_1_1_test_solver.html", null ]
    ] ],
    [ "testing::TestCase", "classtesting_1_1_test_case.html", null ],
    [ "testing::internal::TestCaseNameIs", "classtesting_1_1internal_1_1_test_case_name_is.html", null ],
    [ "testing::TestEventListener", "classtesting_1_1_test_event_listener.html", [
      [ "testing::EmptyTestEventListener", "classtesting_1_1_empty_test_event_listener.html", [
        [ "testing::internal::XmlUnitTestResultPrinter", "classtesting_1_1internal_1_1_xml_unit_test_result_printer.html", null ]
      ] ],
      [ "testing::internal::PrettyUnitTestResultPrinter", "classtesting_1_1internal_1_1_pretty_unit_test_result_printer.html", null ],
      [ "testing::internal::TestEventRepeater", "classtesting_1_1internal_1_1_test_event_repeater.html", null ]
    ] ],
    [ "testing::TestEventListeners", "classtesting_1_1_test_event_listeners.html", null ],
    [ "testing::internal::TestFactoryBase", "classtesting_1_1internal_1_1_test_factory_base.html", [
      [ "testing::internal::ParameterizedTestFactory< TestClass >", "classtesting_1_1internal_1_1_parameterized_test_factory.html", null ],
      [ "testing::internal::TestFactoryImpl< TestClass >", "classtesting_1_1internal_1_1_test_factory_impl.html", null ]
    ] ],
    [ "testing::TestInfo", "classtesting_1_1_test_info.html", null ],
    [ "testing::internal::TestMetaFactoryBase< ParamType >", "classtesting_1_1internal_1_1_test_meta_factory_base.html", null ],
    [ "testing::internal::TestMetaFactoryBase< TestCase::ParamType >", "classtesting_1_1internal_1_1_test_meta_factory_base.html", [
      [ "testing::internal::TestMetaFactory< TestCase >", "classtesting_1_1internal_1_1_test_meta_factory.html", null ]
    ] ],
    [ "testing::TestPartResult", "classtesting_1_1_test_part_result.html", null ],
    [ "testing::TestPartResultArray", "classtesting_1_1_test_part_result_array.html", null ],
    [ "testing::TestPartResultReporterInterface", "classtesting_1_1_test_part_result_reporter_interface.html", [
      [ "testing::internal::DefaultGlobalTestPartResultReporter", "classtesting_1_1internal_1_1_default_global_test_part_result_reporter.html", null ],
      [ "testing::internal::DefaultPerThreadTestPartResultReporter", "classtesting_1_1internal_1_1_default_per_thread_test_part_result_reporter.html", null ],
      [ "testing::internal::HasNewFatalFailureHelper", "classtesting_1_1internal_1_1_has_new_fatal_failure_helper.html", null ],
      [ "testing::ScopedFakeTestPartResultReporter", "classtesting_1_1_scoped_fake_test_part_result_reporter.html", null ]
    ] ],
    [ "testing::TestProperty", "classtesting_1_1_test_property.html", null ],
    [ "testing::internal::TestPropertyKeyIs", "classtesting_1_1internal_1_1_test_property_key_is.html", null ],
    [ "testing::TestResult", "classtesting_1_1_test_result.html", null ],
    [ "testing::internal::TestResultAccessor", "classtesting_1_1internal_1_1_test_result_accessor.html", null ],
    [ "testing::internal::ThreadLocal< T >", "classtesting_1_1internal_1_1_thread_local.html", null ],
    [ "testing::internal::ThreadLocal< std::vector< testing::internal::TraceInfo > >", "classtesting_1_1internal_1_1_thread_local.html", null ],
    [ "testing::internal::ThreadLocal< testing::TestPartResultReporterInterface *>", "classtesting_1_1internal_1_1_thread_local.html", null ],
    [ "caffe::Timer", "classcaffe_1_1_timer.html", [
      [ "caffe::CPUTimer", "classcaffe_1_1_c_p_u_timer.html", null ],
      [ "caffe::CPUTimer", "classcaffe_1_1_c_p_u_timer.html", null ]
    ] ],
    [ "testing::internal::TraceInfo", "structtesting_1_1internal_1_1_trace_info.html", null ],
    [ "caffe::db::Transaction", "classcaffe_1_1db_1_1_transaction.html", null ],
    [ "caffe.io.Transformer", "classcaffe_1_1io_1_1_transformer.html", null ],
    [ "true_type", null, [
      [ "google::protobuf::is_proto_enum< ::caffe::ConvolutionParameter_Engine >", "structgoogle_1_1protobuf_1_1is__proto__enum_3_01_1_1caffe_1_1_convolution_parameter___engine_01_4.html", null ],
      [ "google::protobuf::is_proto_enum< ::caffe::ConvolutionParameter_Engine >", "structgoogle_1_1protobuf_1_1is__proto__enum_3_01_1_1caffe_1_1_convolution_parameter___engine_01_4.html", null ],
      [ "google::protobuf::is_proto_enum< ::caffe::DataParameter_DB >", "structgoogle_1_1protobuf_1_1is__proto__enum_3_01_1_1caffe_1_1_data_parameter___d_b_01_4.html", null ],
      [ "google::protobuf::is_proto_enum< ::caffe::DataParameter_DB >", "structgoogle_1_1protobuf_1_1is__proto__enum_3_01_1_1caffe_1_1_data_parameter___d_b_01_4.html", null ],
      [ "google::protobuf::is_proto_enum< ::caffe::EltwiseParameter_EltwiseOp >", "structgoogle_1_1protobuf_1_1is__proto__enum_3_01_1_1caffe_1_1_eltwise_parameter___eltwise_op_01_4.html", null ],
      [ "google::protobuf::is_proto_enum< ::caffe::EltwiseParameter_EltwiseOp >", "structgoogle_1_1protobuf_1_1is__proto__enum_3_01_1_1caffe_1_1_eltwise_parameter___eltwise_op_01_4.html", null ],
      [ "google::protobuf::is_proto_enum< ::caffe::FillerParameter_VarianceNorm >", "structgoogle_1_1protobuf_1_1is__proto__enum_3_01_1_1caffe_1_1_filler_parameter___variance_norm_01_4.html", null ],
      [ "google::protobuf::is_proto_enum< ::caffe::FillerParameter_VarianceNorm >", "structgoogle_1_1protobuf_1_1is__proto__enum_3_01_1_1caffe_1_1_filler_parameter___variance_norm_01_4.html", null ],
      [ "google::protobuf::is_proto_enum< ::caffe::HingeLossParameter_Norm >", "structgoogle_1_1protobuf_1_1is__proto__enum_3_01_1_1caffe_1_1_hinge_loss_parameter___norm_01_4.html", null ],
      [ "google::protobuf::is_proto_enum< ::caffe::HingeLossParameter_Norm >", "structgoogle_1_1protobuf_1_1is__proto__enum_3_01_1_1caffe_1_1_hinge_loss_parameter___norm_01_4.html", null ],
      [ "google::protobuf::is_proto_enum< ::caffe::LossParameter_NormalizationMode >", "structgoogle_1_1protobuf_1_1is__proto__enum_3_01_1_1caffe_1_1_loss_parameter___normalization_mode_01_4.html", null ],
      [ "google::protobuf::is_proto_enum< ::caffe::LossParameter_NormalizationMode >", "structgoogle_1_1protobuf_1_1is__proto__enum_3_01_1_1caffe_1_1_loss_parameter___normalization_mode_01_4.html", null ],
      [ "google::protobuf::is_proto_enum< ::caffe::LRNParameter_Engine >", "structgoogle_1_1protobuf_1_1is__proto__enum_3_01_1_1caffe_1_1_l_r_n_parameter___engine_01_4.html", null ],
      [ "google::protobuf::is_proto_enum< ::caffe::LRNParameter_Engine >", "structgoogle_1_1protobuf_1_1is__proto__enum_3_01_1_1caffe_1_1_l_r_n_parameter___engine_01_4.html", null ],
      [ "google::protobuf::is_proto_enum< ::caffe::LRNParameter_NormRegion >", "structgoogle_1_1protobuf_1_1is__proto__enum_3_01_1_1caffe_1_1_l_r_n_parameter___norm_region_01_4.html", null ],
      [ "google::protobuf::is_proto_enum< ::caffe::LRNParameter_NormRegion >", "structgoogle_1_1protobuf_1_1is__proto__enum_3_01_1_1caffe_1_1_l_r_n_parameter___norm_region_01_4.html", null ],
      [ "google::protobuf::is_proto_enum< ::caffe::ParamSpec_DimCheckMode >", "structgoogle_1_1protobuf_1_1is__proto__enum_3_01_1_1caffe_1_1_param_spec___dim_check_mode_01_4.html", null ],
      [ "google::protobuf::is_proto_enum< ::caffe::ParamSpec_DimCheckMode >", "structgoogle_1_1protobuf_1_1is__proto__enum_3_01_1_1caffe_1_1_param_spec___dim_check_mode_01_4.html", null ],
      [ "google::protobuf::is_proto_enum< ::caffe::Phase >", "structgoogle_1_1protobuf_1_1is__proto__enum_3_01_1_1caffe_1_1_phase_01_4.html", null ],
      [ "google::protobuf::is_proto_enum< ::caffe::Phase >", "structgoogle_1_1protobuf_1_1is__proto__enum_3_01_1_1caffe_1_1_phase_01_4.html", null ],
      [ "google::protobuf::is_proto_enum< ::caffe::PoolingParameter_Engine >", "structgoogle_1_1protobuf_1_1is__proto__enum_3_01_1_1caffe_1_1_pooling_parameter___engine_01_4.html", null ],
      [ "google::protobuf::is_proto_enum< ::caffe::PoolingParameter_Engine >", "structgoogle_1_1protobuf_1_1is__proto__enum_3_01_1_1caffe_1_1_pooling_parameter___engine_01_4.html", null ],
      [ "google::protobuf::is_proto_enum< ::caffe::PoolingParameter_PoolMethod >", "structgoogle_1_1protobuf_1_1is__proto__enum_3_01_1_1caffe_1_1_pooling_parameter___pool_method_01_4.html", null ],
      [ "google::protobuf::is_proto_enum< ::caffe::PoolingParameter_PoolMethod >", "structgoogle_1_1protobuf_1_1is__proto__enum_3_01_1_1caffe_1_1_pooling_parameter___pool_method_01_4.html", null ],
      [ "google::protobuf::is_proto_enum< ::caffe::ReductionParameter_ReductionOp >", "structgoogle_1_1protobuf_1_1is__proto__enum_3_01_1_1caffe_1_1_reduction_parameter___reduction_op_01_4.html", null ],
      [ "google::protobuf::is_proto_enum< ::caffe::ReductionParameter_ReductionOp >", "structgoogle_1_1protobuf_1_1is__proto__enum_3_01_1_1caffe_1_1_reduction_parameter___reduction_op_01_4.html", null ],
      [ "google::protobuf::is_proto_enum< ::caffe::ReLUParameter_Engine >", "structgoogle_1_1protobuf_1_1is__proto__enum_3_01_1_1caffe_1_1_re_l_u_parameter___engine_01_4.html", null ],
      [ "google::protobuf::is_proto_enum< ::caffe::ReLUParameter_Engine >", "structgoogle_1_1protobuf_1_1is__proto__enum_3_01_1_1caffe_1_1_re_l_u_parameter___engine_01_4.html", null ],
      [ "google::protobuf::is_proto_enum< ::caffe::SigmoidParameter_Engine >", "structgoogle_1_1protobuf_1_1is__proto__enum_3_01_1_1caffe_1_1_sigmoid_parameter___engine_01_4.html", null ],
      [ "google::protobuf::is_proto_enum< ::caffe::SigmoidParameter_Engine >", "structgoogle_1_1protobuf_1_1is__proto__enum_3_01_1_1caffe_1_1_sigmoid_parameter___engine_01_4.html", null ],
      [ "google::protobuf::is_proto_enum< ::caffe::SoftmaxParameter_Engine >", "structgoogle_1_1protobuf_1_1is__proto__enum_3_01_1_1caffe_1_1_softmax_parameter___engine_01_4.html", null ],
      [ "google::protobuf::is_proto_enum< ::caffe::SoftmaxParameter_Engine >", "structgoogle_1_1protobuf_1_1is__proto__enum_3_01_1_1caffe_1_1_softmax_parameter___engine_01_4.html", null ],
      [ "google::protobuf::is_proto_enum< ::caffe::SolverParameter_SnapshotFormat >", "structgoogle_1_1protobuf_1_1is__proto__enum_3_01_1_1caffe_1_1_solver_parameter___snapshot_format_01_4.html", null ],
      [ "google::protobuf::is_proto_enum< ::caffe::SolverParameter_SnapshotFormat >", "structgoogle_1_1protobuf_1_1is__proto__enum_3_01_1_1caffe_1_1_solver_parameter___snapshot_format_01_4.html", null ],
      [ "google::protobuf::is_proto_enum< ::caffe::SolverParameter_SolverMode >", "structgoogle_1_1protobuf_1_1is__proto__enum_3_01_1_1caffe_1_1_solver_parameter___solver_mode_01_4.html", null ],
      [ "google::protobuf::is_proto_enum< ::caffe::SolverParameter_SolverMode >", "structgoogle_1_1protobuf_1_1is__proto__enum_3_01_1_1caffe_1_1_solver_parameter___solver_mode_01_4.html", null ],
      [ "google::protobuf::is_proto_enum< ::caffe::SolverParameter_SolverType >", "structgoogle_1_1protobuf_1_1is__proto__enum_3_01_1_1caffe_1_1_solver_parameter___solver_type_01_4.html", null ],
      [ "google::protobuf::is_proto_enum< ::caffe::SolverParameter_SolverType >", "structgoogle_1_1protobuf_1_1is__proto__enum_3_01_1_1caffe_1_1_solver_parameter___solver_type_01_4.html", null ],
      [ "google::protobuf::is_proto_enum< ::caffe::SPPParameter_Engine >", "structgoogle_1_1protobuf_1_1is__proto__enum_3_01_1_1caffe_1_1_s_p_p_parameter___engine_01_4.html", null ],
      [ "google::protobuf::is_proto_enum< ::caffe::SPPParameter_Engine >", "structgoogle_1_1protobuf_1_1is__proto__enum_3_01_1_1caffe_1_1_s_p_p_parameter___engine_01_4.html", null ],
      [ "google::protobuf::is_proto_enum< ::caffe::SPPParameter_PoolMethod >", "structgoogle_1_1protobuf_1_1is__proto__enum_3_01_1_1caffe_1_1_s_p_p_parameter___pool_method_01_4.html", null ],
      [ "google::protobuf::is_proto_enum< ::caffe::SPPParameter_PoolMethod >", "structgoogle_1_1protobuf_1_1is__proto__enum_3_01_1_1caffe_1_1_s_p_p_parameter___pool_method_01_4.html", null ],
      [ "google::protobuf::is_proto_enum< ::caffe::TanHParameter_Engine >", "structgoogle_1_1protobuf_1_1is__proto__enum_3_01_1_1caffe_1_1_tan_h_parameter___engine_01_4.html", null ],
      [ "google::protobuf::is_proto_enum< ::caffe::TanHParameter_Engine >", "structgoogle_1_1protobuf_1_1is__proto__enum_3_01_1_1caffe_1_1_tan_h_parameter___engine_01_4.html", null ],
      [ "google::protobuf::is_proto_enum< ::caffe::V0LayerParameter_PoolMethod >", "structgoogle_1_1protobuf_1_1is__proto__enum_3_01_1_1caffe_1_1_v0_layer_parameter___pool_method_01_4.html", null ],
      [ "google::protobuf::is_proto_enum< ::caffe::V0LayerParameter_PoolMethod >", "structgoogle_1_1protobuf_1_1is__proto__enum_3_01_1_1caffe_1_1_v0_layer_parameter___pool_method_01_4.html", null ],
      [ "google::protobuf::is_proto_enum< ::caffe::V1LayerParameter_DimCheckMode >", "structgoogle_1_1protobuf_1_1is__proto__enum_3_01_1_1caffe_1_1_v1_layer_parameter___dim_check_mode_01_4.html", null ],
      [ "google::protobuf::is_proto_enum< ::caffe::V1LayerParameter_DimCheckMode >", "structgoogle_1_1protobuf_1_1is__proto__enum_3_01_1_1caffe_1_1_v1_layer_parameter___dim_check_mode_01_4.html", null ],
      [ "google::protobuf::is_proto_enum< ::caffe::V1LayerParameter_LayerType >", "structgoogle_1_1protobuf_1_1is__proto__enum_3_01_1_1caffe_1_1_v1_layer_parameter___layer_type_01_4.html", null ],
      [ "google::protobuf::is_proto_enum< ::caffe::V1LayerParameter_LayerType >", "structgoogle_1_1protobuf_1_1is__proto__enum_3_01_1_1caffe_1_1_v1_layer_parameter___layer_type_01_4.html", null ]
    ] ],
    [ "std::tr1::tuple<>", "classstd_1_1tr1_1_1tuple.html", null ],
    [ "std::tr1::tuple< T1, T2 >", "classstd_1_1tr1_1_1tuple.html", null ],
    [ "std::tr1::tuple< T1, T2, T3 >", "classstd_1_1tr1_1_1tuple.html", null ],
    [ "std::tr1::tuple< T1, T2, T3, T4 >", "classstd_1_1tr1_1_1tuple.html", null ],
    [ "std::tr1::tuple< T1, T2, T3, T4, T5 >", "classstd_1_1tr1_1_1tuple.html", null ],
    [ "std::tr1::tuple< T1, T2, T3, T4, T5, T6 >", "classstd_1_1tr1_1_1tuple.html", null ],
    [ "std::tr1::tuple< T1, T2, T3, T4, T5, T6, T7 >", "classstd_1_1tr1_1_1tuple.html", null ],
    [ "std::tr1::tuple< T1, T2, T3, T4, T5, T6, T7, T8 >", "classstd_1_1tr1_1_1tuple.html", null ],
    [ "std::tr1::tuple< T1, T2, T3, T4, T5, T6, T7, T8, T9 >", "classstd_1_1tr1_1_1tuple.html", null ],
    [ "std::tr1::tuple< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10 >", "classstd_1_1tr1_1_1tuple.html", null ],
    [ "std::tr1::tuple<>", "classstd_1_1tr1_1_1tuple_3_4.html", null ],
    [ "std::tr1::tuple_element< k, Tuple >", "structstd_1_1tr1_1_1tuple__element.html", null ],
    [ "std::tr1::tuple_size< Tuple >", "structstd_1_1tr1_1_1tuple__size.html", null ],
    [ "std::tr1::tuple_size< GTEST_0_TUPLE_(T)>", "structstd_1_1tr1_1_1tuple__size_3_01_g_t_e_s_t__0___t_u_p_l_e___07_t_08_4.html", null ],
    [ "std::tr1::tuple_size< GTEST_10_TUPLE_(T)>", "structstd_1_1tr1_1_1tuple__size_3_01_g_t_e_s_t__10___t_u_p_l_e___07_t_08_4.html", null ],
    [ "std::tr1::tuple_size< GTEST_1_TUPLE_(T)>", "structstd_1_1tr1_1_1tuple__size_3_01_g_t_e_s_t__1___t_u_p_l_e___07_t_08_4.html", null ],
    [ "std::tr1::tuple_size< GTEST_2_TUPLE_(T)>", "structstd_1_1tr1_1_1tuple__size_3_01_g_t_e_s_t__2___t_u_p_l_e___07_t_08_4.html", null ],
    [ "std::tr1::tuple_size< GTEST_3_TUPLE_(T)>", "structstd_1_1tr1_1_1tuple__size_3_01_g_t_e_s_t__3___t_u_p_l_e___07_t_08_4.html", null ],
    [ "std::tr1::tuple_size< GTEST_4_TUPLE_(T)>", "structstd_1_1tr1_1_1tuple__size_3_01_g_t_e_s_t__4___t_u_p_l_e___07_t_08_4.html", null ],
    [ "std::tr1::tuple_size< GTEST_5_TUPLE_(T)>", "structstd_1_1tr1_1_1tuple__size_3_01_g_t_e_s_t__5___t_u_p_l_e___07_t_08_4.html", null ],
    [ "std::tr1::tuple_size< GTEST_6_TUPLE_(T)>", "structstd_1_1tr1_1_1tuple__size_3_01_g_t_e_s_t__6___t_u_p_l_e___07_t_08_4.html", null ],
    [ "std::tr1::tuple_size< GTEST_7_TUPLE_(T)>", "structstd_1_1tr1_1_1tuple__size_3_01_g_t_e_s_t__7___t_u_p_l_e___07_t_08_4.html", null ],
    [ "std::tr1::tuple_size< GTEST_8_TUPLE_(T)>", "structstd_1_1tr1_1_1tuple__size_3_01_g_t_e_s_t__8___t_u_p_l_e___07_t_08_4.html", null ],
    [ "std::tr1::tuple_size< GTEST_9_TUPLE_(T)>", "structstd_1_1tr1_1_1tuple__size_3_01_g_t_e_s_t__9___t_u_p_l_e___07_t_08_4.html", null ],
    [ "std::tr1::gtest_internal::TupleElement< kIndexValid, kIndex, Tuple >", "structstd_1_1tr1_1_1gtest__internal_1_1_tuple_element.html", null ],
    [ "std::tr1::gtest_internal::TupleElement< true, 0, GTEST_10_TUPLE_(T)>", "structstd_1_1tr1_1_1gtest__internal_1_1_tuple_element_3_01true_00_010_00_01_g_t_e_s_t__10___t_u_p_l_e___07_t_08_4.html", null ],
    [ "std::tr1::gtest_internal::TupleElement< true, 1, GTEST_10_TUPLE_(T)>", "structstd_1_1tr1_1_1gtest__internal_1_1_tuple_element_3_01true_00_011_00_01_g_t_e_s_t__10___t_u_p_l_e___07_t_08_4.html", null ],
    [ "std::tr1::gtest_internal::TupleElement< true, 2, GTEST_10_TUPLE_(T)>", "structstd_1_1tr1_1_1gtest__internal_1_1_tuple_element_3_01true_00_012_00_01_g_t_e_s_t__10___t_u_p_l_e___07_t_08_4.html", null ],
    [ "std::tr1::gtest_internal::TupleElement< true, 3, GTEST_10_TUPLE_(T)>", "structstd_1_1tr1_1_1gtest__internal_1_1_tuple_element_3_01true_00_013_00_01_g_t_e_s_t__10___t_u_p_l_e___07_t_08_4.html", null ],
    [ "std::tr1::gtest_internal::TupleElement< true, 4, GTEST_10_TUPLE_(T)>", "structstd_1_1tr1_1_1gtest__internal_1_1_tuple_element_3_01true_00_014_00_01_g_t_e_s_t__10___t_u_p_l_e___07_t_08_4.html", null ],
    [ "std::tr1::gtest_internal::TupleElement< true, 5, GTEST_10_TUPLE_(T)>", "structstd_1_1tr1_1_1gtest__internal_1_1_tuple_element_3_01true_00_015_00_01_g_t_e_s_t__10___t_u_p_l_e___07_t_08_4.html", null ],
    [ "std::tr1::gtest_internal::TupleElement< true, 6, GTEST_10_TUPLE_(T)>", "structstd_1_1tr1_1_1gtest__internal_1_1_tuple_element_3_01true_00_016_00_01_g_t_e_s_t__10___t_u_p_l_e___07_t_08_4.html", null ],
    [ "std::tr1::gtest_internal::TupleElement< true, 7, GTEST_10_TUPLE_(T)>", "structstd_1_1tr1_1_1gtest__internal_1_1_tuple_element_3_01true_00_017_00_01_g_t_e_s_t__10___t_u_p_l_e___07_t_08_4.html", null ],
    [ "std::tr1::gtest_internal::TupleElement< true, 8, GTEST_10_TUPLE_(T)>", "structstd_1_1tr1_1_1gtest__internal_1_1_tuple_element_3_01true_00_018_00_01_g_t_e_s_t__10___t_u_p_l_e___07_t_08_4.html", null ],
    [ "std::tr1::gtest_internal::TupleElement< true, 9, GTEST_10_TUPLE_(T)>", "structstd_1_1tr1_1_1gtest__internal_1_1_tuple_element_3_01true_00_019_00_01_g_t_e_s_t__10___t_u_p_l_e___07_t_08_4.html", null ],
    [ "testing::internal::TuplePrefixPrinter< N >", "structtesting_1_1internal_1_1_tuple_prefix_printer.html", null ],
    [ "testing::internal::TuplePrefixPrinter< 0 >", "structtesting_1_1internal_1_1_tuple_prefix_printer_3_010_01_4.html", null ],
    [ "testing::internal::TuplePrefixPrinter< 1 >", "structtesting_1_1internal_1_1_tuple_prefix_printer_3_011_01_4.html", null ],
    [ "caffe::NdarrayConverterGenerator::apply< T >::type", "structcaffe_1_1_ndarray_converter_generator_1_1apply_3_01_dtype_01_5_01_4_1_1type.html", null ],
    [ "testing::internal::TypeIdHelper< T >", "classtesting_1_1internal_1_1_type_id_helper.html", null ],
    [ "testing::internal2::TypeWithoutFormatter< T, kTypeKind >", "classtesting_1_1internal2_1_1_type_without_formatter.html", null ],
    [ "testing::internal2::TypeWithoutFormatter< T, kConvertibleToInteger >", "classtesting_1_1internal2_1_1_type_without_formatter_3_01_t_00_01k_convertible_to_integer_01_4.html", null ],
    [ "testing::internal2::TypeWithoutFormatter< T, kProtobuf >", "classtesting_1_1internal2_1_1_type_without_formatter_3_01_t_00_01k_protobuf_01_4.html", null ],
    [ "testing::internal::TypeWithSize< size >", "classtesting_1_1internal_1_1_type_with_size.html", null ],
    [ "testing::internal::TypeWithSize< 4 >", "classtesting_1_1internal_1_1_type_with_size_3_014_01_4.html", null ],
    [ "testing::internal::TypeWithSize< 8 >", "classtesting_1_1internal_1_1_type_with_size_3_018_01_4.html", null ],
    [ "testing::internal::TypeWithSize< sizeof(RawType)>", "classtesting_1_1internal_1_1_type_with_size.html", null ],
    [ "testing::UnitTest", "classtesting_1_1_unit_test.html", null ],
    [ "testing::internal::UnitTestImpl", "classtesting_1_1internal_1_1_unit_test_impl.html", null ],
    [ "testing::internal::UnitTestOptions", "classtesting_1_1internal_1_1_unit_test_options.html", null ],
    [ "testing::internal::UniversalPrinter< T >", "classtesting_1_1internal_1_1_universal_printer.html", null ],
    [ "testing::internal::UniversalPrinter< T & >", "classtesting_1_1internal_1_1_universal_printer_3_01_t_01_6_01_4.html", null ],
    [ "testing::internal::UniversalPrinter< T[N]>", "classtesting_1_1internal_1_1_universal_printer_3_01_t[_n]_4.html", null ],
    [ "testing::internal::ValueArray1< T1 >", "classtesting_1_1internal_1_1_value_array1.html", null ],
    [ "testing::internal::ValueArray10< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10 >", "classtesting_1_1internal_1_1_value_array10.html", null ],
    [ "testing::internal::ValueArray11< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11 >", "classtesting_1_1internal_1_1_value_array11.html", null ],
    [ "testing::internal::ValueArray12< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12 >", "classtesting_1_1internal_1_1_value_array12.html", null ],
    [ "testing::internal::ValueArray13< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13 >", "classtesting_1_1internal_1_1_value_array13.html", null ],
    [ "testing::internal::ValueArray14< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14 >", "classtesting_1_1internal_1_1_value_array14.html", null ],
    [ "testing::internal::ValueArray15< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15 >", "classtesting_1_1internal_1_1_value_array15.html", null ],
    [ "testing::internal::ValueArray16< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16 >", "classtesting_1_1internal_1_1_value_array16.html", null ],
    [ "testing::internal::ValueArray17< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17 >", "classtesting_1_1internal_1_1_value_array17.html", null ],
    [ "testing::internal::ValueArray18< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18 >", "classtesting_1_1internal_1_1_value_array18.html", null ],
    [ "testing::internal::ValueArray19< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19 >", "classtesting_1_1internal_1_1_value_array19.html", null ],
    [ "testing::internal::ValueArray2< T1, T2 >", "classtesting_1_1internal_1_1_value_array2.html", null ],
    [ "testing::internal::ValueArray20< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20 >", "classtesting_1_1internal_1_1_value_array20.html", null ],
    [ "testing::internal::ValueArray21< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21 >", "classtesting_1_1internal_1_1_value_array21.html", null ],
    [ "testing::internal::ValueArray22< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22 >", "classtesting_1_1internal_1_1_value_array22.html", null ],
    [ "testing::internal::ValueArray23< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23 >", "classtesting_1_1internal_1_1_value_array23.html", null ],
    [ "testing::internal::ValueArray24< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24 >", "classtesting_1_1internal_1_1_value_array24.html", null ],
    [ "testing::internal::ValueArray25< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25 >", "classtesting_1_1internal_1_1_value_array25.html", null ],
    [ "testing::internal::ValueArray26< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26 >", "classtesting_1_1internal_1_1_value_array26.html", null ],
    [ "testing::internal::ValueArray27< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27 >", "classtesting_1_1internal_1_1_value_array27.html", null ],
    [ "testing::internal::ValueArray28< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28 >", "classtesting_1_1internal_1_1_value_array28.html", null ],
    [ "testing::internal::ValueArray29< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29 >", "classtesting_1_1internal_1_1_value_array29.html", null ],
    [ "testing::internal::ValueArray3< T1, T2, T3 >", "classtesting_1_1internal_1_1_value_array3.html", null ],
    [ "testing::internal::ValueArray30< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30 >", "classtesting_1_1internal_1_1_value_array30.html", null ],
    [ "testing::internal::ValueArray31< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31 >", "classtesting_1_1internal_1_1_value_array31.html", null ],
    [ "testing::internal::ValueArray32< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32 >", "classtesting_1_1internal_1_1_value_array32.html", null ],
    [ "testing::internal::ValueArray33< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33 >", "classtesting_1_1internal_1_1_value_array33.html", null ],
    [ "testing::internal::ValueArray34< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33, T34 >", "classtesting_1_1internal_1_1_value_array34.html", null ],
    [ "testing::internal::ValueArray35< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33, T34, T35 >", "classtesting_1_1internal_1_1_value_array35.html", null ],
    [ "testing::internal::ValueArray36< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36 >", "classtesting_1_1internal_1_1_value_array36.html", null ],
    [ "testing::internal::ValueArray37< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36, T37 >", "classtesting_1_1internal_1_1_value_array37.html", null ],
    [ "testing::internal::ValueArray38< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36, T37, T38 >", "classtesting_1_1internal_1_1_value_array38.html", null ],
    [ "testing::internal::ValueArray39< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36, T37, T38, T39 >", "classtesting_1_1internal_1_1_value_array39.html", null ],
    [ "testing::internal::ValueArray4< T1, T2, T3, T4 >", "classtesting_1_1internal_1_1_value_array4.html", null ],
    [ "testing::internal::ValueArray40< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36, T37, T38, T39, T40 >", "classtesting_1_1internal_1_1_value_array40.html", null ],
    [ "testing::internal::ValueArray41< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36, T37, T38, T39, T40, T41 >", "classtesting_1_1internal_1_1_value_array41.html", null ],
    [ "testing::internal::ValueArray42< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36, T37, T38, T39, T40, T41, T42 >", "classtesting_1_1internal_1_1_value_array42.html", null ],
    [ "testing::internal::ValueArray43< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36, T37, T38, T39, T40, T41, T42, T43 >", "classtesting_1_1internal_1_1_value_array43.html", null ],
    [ "testing::internal::ValueArray44< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36, T37, T38, T39, T40, T41, T42, T43, T44 >", "classtesting_1_1internal_1_1_value_array44.html", null ],
    [ "testing::internal::ValueArray45< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36, T37, T38, T39, T40, T41, T42, T43, T44, T45 >", "classtesting_1_1internal_1_1_value_array45.html", null ],
    [ "testing::internal::ValueArray46< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36, T37, T38, T39, T40, T41, T42, T43, T44, T45, T46 >", "classtesting_1_1internal_1_1_value_array46.html", null ],
    [ "testing::internal::ValueArray47< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36, T37, T38, T39, T40, T41, T42, T43, T44, T45, T46, T47 >", "classtesting_1_1internal_1_1_value_array47.html", null ],
    [ "testing::internal::ValueArray48< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36, T37, T38, T39, T40, T41, T42, T43, T44, T45, T46, T47, T48 >", "classtesting_1_1internal_1_1_value_array48.html", null ],
    [ "testing::internal::ValueArray49< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36, T37, T38, T39, T40, T41, T42, T43, T44, T45, T46, T47, T48, T49 >", "classtesting_1_1internal_1_1_value_array49.html", null ],
    [ "testing::internal::ValueArray5< T1, T2, T3, T4, T5 >", "classtesting_1_1internal_1_1_value_array5.html", null ],
    [ "testing::internal::ValueArray50< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31, T32, T33, T34, T35, T36, T37, T38, T39, T40, T41, T42, T43, T44, T45, T46, T47, T48, T49, T50 >", "classtesting_1_1internal_1_1_value_array50.html", null ],
    [ "testing::internal::ValueArray6< T1, T2, T3, T4, T5, T6 >", "classtesting_1_1internal_1_1_value_array6.html", null ],
    [ "testing::internal::ValueArray7< T1, T2, T3, T4, T5, T6, T7 >", "classtesting_1_1internal_1_1_value_array7.html", null ],
    [ "testing::internal::ValueArray8< T1, T2, T3, T4, T5, T6, T7, T8 >", "classtesting_1_1internal_1_1_value_array8.html", null ],
    [ "testing::internal::ValueArray9< T1, T2, T3, T4, T5, T6, T7, T8, T9 >", "classtesting_1_1internal_1_1_value_array9.html", null ],
    [ "testing::WithParamInterface< T >", "classtesting_1_1_with_param_interface.html", [
      [ "testing::TestWithParam< T >", "classtesting_1_1_test_with_param.html", null ]
    ] ]
];