var searchData=
[
  ['ignore_5flabel_5f',['ignore_label_',['../classcaffe_1_1_accuracy_layer.html#a2b8c2d647f43ffd6aa14e81f1c5b2bde',1,'caffe::AccuracyLayer::ignore_label_()'],['../classcaffe_1_1_infogain_loss_layer.html#ad3f7c2efdf32f99510186495ba7c5cff',1,'caffe::InfogainLossLayer::ignore_label_()'],['../classcaffe_1_1_sigmoid_cross_entropy_loss_layer.html#ab99d98ce823df6c90cd4c3cf8b0a793f',1,'caffe::SigmoidCrossEntropyLossLayer::ignore_label_()'],['../classcaffe_1_1_softmax_with_loss_layer.html#a117d31c7ac538dd7851fb493bfc75d95',1,'caffe::SoftmaxWithLossLayer::ignore_label_()']]],
  ['im2collayer',['Im2colLayer',['../classcaffe_1_1_im2col_layer.html',1,'caffe']]],
  ['im2collayertest',['Im2colLayerTest',['../classcaffe_1_1_im2col_layer_test.html',1,'caffe']]],
  ['imagedatalayer',['ImageDataLayer',['../classcaffe_1_1_image_data_layer.html',1,'caffe']]],
  ['imagedataparameter',['ImageDataParameter',['../classcaffe_1_1_image_data_parameter.html',1,'caffe']]],
  ['imagenetclassifier',['ImagenetClassifier',['../classapp_1_1_imagenet_classifier.html',1,'app']]],
  ['implicitlyconvertible',['ImplicitlyConvertible',['../classtesting_1_1internal_1_1_implicitly_convertible.html',1,'testing::internal']]],
  ['incrementerrorcount',['IncrementErrorCount',['../classcpp__lint_1_1___cpp_lint_state.html#a639dac461e7354dcec4b629195758852',1,'cpp_lint::_CppLintState']]],
  ['inferblobshape',['InferBlobShape',['../classcaffe_1_1_data_transformer.html#a1e43b0fb80cded5bb854e1a06004bebf',1,'caffe::DataTransformer::InferBlobShape(const Datum &amp;datum)'],['../classcaffe_1_1_data_transformer.html#ac829dd6448dcce67acb1e22a2554db4b',1,'caffe::DataTransformer::InferBlobShape(const vector&lt; Datum &gt; &amp;datum_vector)'],['../classcaffe_1_1_data_transformer.html#a4a8e7feba153c9c671d0aabc8f12e65b',1,'caffe::DataTransformer::InferBlobShape(const Datum &amp;datum)'],['../classcaffe_1_1_data_transformer.html#ad4e4f3c11822fbe2f37d2d7f82bcc36e',1,'caffe::DataTransformer::InferBlobShape(const vector&lt; Datum &gt; &amp;datum_vector)']]],
  ['inferred_5faxis_5f',['inferred_axis_',['../classcaffe_1_1_reshape_layer.html#a41111d585f1a9a64fd774ca1bf7d4160',1,'caffe::ReshapeLayer']]],
  ['infogainlosslayer',['InfogainLossLayer',['../classcaffe_1_1_infogain_loss_layer.html',1,'caffe']]],
  ['infogainlosslayertest',['InfogainLossLayerTest',['../classcaffe_1_1_infogain_loss_layer_test.html',1,'caffe']]],
  ['infogainlossparameter',['InfogainLossParameter',['../classcaffe_1_1_infogain_loss_parameter.html',1,'caffe']]],
  ['init',['Init',['../classcaffe_1_1_net.html#ae9fcfaabc89165d6c0cb4b14b4c6b584',1,'caffe::Net::Init(const NetParameter &amp;param)'],['../classcaffe_1_1_net.html#ae9fcfaabc89165d6c0cb4b14b4c6b584',1,'caffe::Net::Init(const NetParameter &amp;param)']]],
  ['initrand',['InitRand',['../classcaffe_1_1_data_transformer.html#a6d807c7dc250e66b62d97d9847278e68',1,'caffe::DataTransformer::InitRand()'],['../classcaffe_1_1_data_transformer.html#a6d807c7dc250e66b62d97d9847278e68',1,'caffe::DataTransformer::InitRand()']]],
  ['innamespacebody',['InNamespaceBody',['../classcpp__lint_1_1___nesting_state.html#a8add51b250bd6004e4bb25669d274c3f',1,'cpp_lint::_NestingState']]],
  ['innermostclass',['InnermostClass',['../classcpp__lint_1_1___nesting_state.html#a19adbe5a4b2f7baef867ee9385bf29af',1,'cpp_lint::_NestingState']]],
  ['innerproductlayer',['InnerProductLayer',['../classcaffe_1_1_inner_product_layer.html',1,'caffe']]],
  ['innerproductlayertest',['InnerProductLayerTest',['../classcaffe_1_1_inner_product_layer_test.html',1,'caffe']]],
  ['innerproductparameter',['InnerProductParameter',['../classcaffe_1_1_inner_product_parameter.html',1,'caffe']]],
  ['input_5fshape',['input_shape',['../classcaffe_1_1_base_convolution_layer.html#a6324d4ab918a7b09399aa85a8a03737d',1,'caffe::BaseConvolutionLayer::input_shape(int i)'],['../classcaffe_1_1_base_convolution_layer.html#a6324d4ab918a7b09399aa85a8a03737d',1,'caffe::BaseConvolutionLayer::input_shape(int i)']]],
  ['inputlayer',['InputLayer',['../classcaffe_1_1_input_layer.html',1,'caffe']]],
  ['inputparameter',['InputParameter',['../classcaffe_1_1_input_parameter.html',1,'caffe']]],
  ['internalthread',['InternalThread',['../classcaffe_1_1_internal_thread.html',1,'caffe']]],
  ['internalthreadtest',['InternalThreadTest',['../classcaffe_1_1_internal_thread_test.html',1,'caffe']]],
  ['inverse',['inverse',['../namespacecaffe_1_1coord__map.html#ad03646b133a0a44eb1062c6acf677c8c',1,'caffe::coord_map']]],
  ['is_5fpointer',['is_pointer',['../structtesting_1_1internal_1_1is__pointer.html',1,'testing::internal']]],
  ['is_5fpointer_3c_20t_20_2a_20_3e',['is_pointer&lt; T * &gt;',['../structtesting_1_1internal_1_1is__pointer_3_01_t_01_5_01_4.html',1,'testing::internal']]],
  ['is_5fproto_5fenum_3c_20_3a_3acaffe_3a_3aconvolutionparameter_5fengine_20_3e',['is_proto_enum&lt; ::caffe::ConvolutionParameter_Engine &gt;',['../structgoogle_1_1protobuf_1_1is__proto__enum_3_01_1_1caffe_1_1_convolution_parameter___engine_01_4.html',1,'google::protobuf']]],
  ['is_5fproto_5fenum_3c_20_3a_3acaffe_3a_3adataparameter_5fdb_20_3e',['is_proto_enum&lt; ::caffe::DataParameter_DB &gt;',['../structgoogle_1_1protobuf_1_1is__proto__enum_3_01_1_1caffe_1_1_data_parameter___d_b_01_4.html',1,'google::protobuf']]],
  ['is_5fproto_5fenum_3c_20_3a_3acaffe_3a_3aeltwiseparameter_5feltwiseop_20_3e',['is_proto_enum&lt; ::caffe::EltwiseParameter_EltwiseOp &gt;',['../structgoogle_1_1protobuf_1_1is__proto__enum_3_01_1_1caffe_1_1_eltwise_parameter___eltwise_op_01_4.html',1,'google::protobuf']]],
  ['is_5fproto_5fenum_3c_20_3a_3acaffe_3a_3afillerparameter_5fvariancenorm_20_3e',['is_proto_enum&lt; ::caffe::FillerParameter_VarianceNorm &gt;',['../structgoogle_1_1protobuf_1_1is__proto__enum_3_01_1_1caffe_1_1_filler_parameter___variance_norm_01_4.html',1,'google::protobuf']]],
  ['is_5fproto_5fenum_3c_20_3a_3acaffe_3a_3ahingelossparameter_5fnorm_20_3e',['is_proto_enum&lt; ::caffe::HingeLossParameter_Norm &gt;',['../structgoogle_1_1protobuf_1_1is__proto__enum_3_01_1_1caffe_1_1_hinge_loss_parameter___norm_01_4.html',1,'google::protobuf']]],
  ['is_5fproto_5fenum_3c_20_3a_3acaffe_3a_3alossparameter_5fnormalizationmode_20_3e',['is_proto_enum&lt; ::caffe::LossParameter_NormalizationMode &gt;',['../structgoogle_1_1protobuf_1_1is__proto__enum_3_01_1_1caffe_1_1_loss_parameter___normalization_mode_01_4.html',1,'google::protobuf']]],
  ['is_5fproto_5fenum_3c_20_3a_3acaffe_3a_3alrnparameter_5fengine_20_3e',['is_proto_enum&lt; ::caffe::LRNParameter_Engine &gt;',['../structgoogle_1_1protobuf_1_1is__proto__enum_3_01_1_1caffe_1_1_l_r_n_parameter___engine_01_4.html',1,'google::protobuf']]],
  ['is_5fproto_5fenum_3c_20_3a_3acaffe_3a_3alrnparameter_5fnormregion_20_3e',['is_proto_enum&lt; ::caffe::LRNParameter_NormRegion &gt;',['../structgoogle_1_1protobuf_1_1is__proto__enum_3_01_1_1caffe_1_1_l_r_n_parameter___norm_region_01_4.html',1,'google::protobuf']]],
  ['is_5fproto_5fenum_3c_20_3a_3acaffe_3a_3aparamspec_5fdimcheckmode_20_3e',['is_proto_enum&lt; ::caffe::ParamSpec_DimCheckMode &gt;',['../structgoogle_1_1protobuf_1_1is__proto__enum_3_01_1_1caffe_1_1_param_spec___dim_check_mode_01_4.html',1,'google::protobuf']]],
  ['is_5fproto_5fenum_3c_20_3a_3acaffe_3a_3aphase_20_3e',['is_proto_enum&lt; ::caffe::Phase &gt;',['../structgoogle_1_1protobuf_1_1is__proto__enum_3_01_1_1caffe_1_1_phase_01_4.html',1,'google::protobuf']]],
  ['is_5fproto_5fenum_3c_20_3a_3acaffe_3a_3apoolingparameter_5fengine_20_3e',['is_proto_enum&lt; ::caffe::PoolingParameter_Engine &gt;',['../structgoogle_1_1protobuf_1_1is__proto__enum_3_01_1_1caffe_1_1_pooling_parameter___engine_01_4.html',1,'google::protobuf']]],
  ['is_5fproto_5fenum_3c_20_3a_3acaffe_3a_3apoolingparameter_5fpoolmethod_20_3e',['is_proto_enum&lt; ::caffe::PoolingParameter_PoolMethod &gt;',['../structgoogle_1_1protobuf_1_1is__proto__enum_3_01_1_1caffe_1_1_pooling_parameter___pool_method_01_4.html',1,'google::protobuf']]],
  ['is_5fproto_5fenum_3c_20_3a_3acaffe_3a_3areductionparameter_5freductionop_20_3e',['is_proto_enum&lt; ::caffe::ReductionParameter_ReductionOp &gt;',['../structgoogle_1_1protobuf_1_1is__proto__enum_3_01_1_1caffe_1_1_reduction_parameter___reduction_op_01_4.html',1,'google::protobuf']]],
  ['is_5fproto_5fenum_3c_20_3a_3acaffe_3a_3areluparameter_5fengine_20_3e',['is_proto_enum&lt; ::caffe::ReLUParameter_Engine &gt;',['../structgoogle_1_1protobuf_1_1is__proto__enum_3_01_1_1caffe_1_1_re_l_u_parameter___engine_01_4.html',1,'google::protobuf']]],
  ['is_5fproto_5fenum_3c_20_3a_3acaffe_3a_3asigmoidparameter_5fengine_20_3e',['is_proto_enum&lt; ::caffe::SigmoidParameter_Engine &gt;',['../structgoogle_1_1protobuf_1_1is__proto__enum_3_01_1_1caffe_1_1_sigmoid_parameter___engine_01_4.html',1,'google::protobuf']]],
  ['is_5fproto_5fenum_3c_20_3a_3acaffe_3a_3asoftmaxparameter_5fengine_20_3e',['is_proto_enum&lt; ::caffe::SoftmaxParameter_Engine &gt;',['../structgoogle_1_1protobuf_1_1is__proto__enum_3_01_1_1caffe_1_1_softmax_parameter___engine_01_4.html',1,'google::protobuf']]],
  ['is_5fproto_5fenum_3c_20_3a_3acaffe_3a_3asolverparameter_5fsnapshotformat_20_3e',['is_proto_enum&lt; ::caffe::SolverParameter_SnapshotFormat &gt;',['../structgoogle_1_1protobuf_1_1is__proto__enum_3_01_1_1caffe_1_1_solver_parameter___snapshot_format_01_4.html',1,'google::protobuf']]],
  ['is_5fproto_5fenum_3c_20_3a_3acaffe_3a_3asolverparameter_5fsolvermode_20_3e',['is_proto_enum&lt; ::caffe::SolverParameter_SolverMode &gt;',['../structgoogle_1_1protobuf_1_1is__proto__enum_3_01_1_1caffe_1_1_solver_parameter___solver_mode_01_4.html',1,'google::protobuf']]],
  ['is_5fproto_5fenum_3c_20_3a_3acaffe_3a_3asolverparameter_5fsolvertype_20_3e',['is_proto_enum&lt; ::caffe::SolverParameter_SolverType &gt;',['../structgoogle_1_1protobuf_1_1is__proto__enum_3_01_1_1caffe_1_1_solver_parameter___solver_type_01_4.html',1,'google::protobuf']]],
  ['is_5fproto_5fenum_3c_20_3a_3acaffe_3a_3asppparameter_5fengine_20_3e',['is_proto_enum&lt; ::caffe::SPPParameter_Engine &gt;',['../structgoogle_1_1protobuf_1_1is__proto__enum_3_01_1_1caffe_1_1_s_p_p_parameter___engine_01_4.html',1,'google::protobuf']]],
  ['is_5fproto_5fenum_3c_20_3a_3acaffe_3a_3asppparameter_5fpoolmethod_20_3e',['is_proto_enum&lt; ::caffe::SPPParameter_PoolMethod &gt;',['../structgoogle_1_1protobuf_1_1is__proto__enum_3_01_1_1caffe_1_1_s_p_p_parameter___pool_method_01_4.html',1,'google::protobuf']]],
  ['is_5fproto_5fenum_3c_20_3a_3acaffe_3a_3atanhparameter_5fengine_20_3e',['is_proto_enum&lt; ::caffe::TanHParameter_Engine &gt;',['../structgoogle_1_1protobuf_1_1is__proto__enum_3_01_1_1caffe_1_1_tan_h_parameter___engine_01_4.html',1,'google::protobuf']]],
  ['is_5fproto_5fenum_3c_20_3a_3acaffe_3a_3av0layerparameter_5fpoolmethod_20_3e',['is_proto_enum&lt; ::caffe::V0LayerParameter_PoolMethod &gt;',['../structgoogle_1_1protobuf_1_1is__proto__enum_3_01_1_1caffe_1_1_v0_layer_parameter___pool_method_01_4.html',1,'google::protobuf']]],
  ['is_5fproto_5fenum_3c_20_3a_3acaffe_3a_3av1layerparameter_5fdimcheckmode_20_3e',['is_proto_enum&lt; ::caffe::V1LayerParameter_DimCheckMode &gt;',['../structgoogle_1_1protobuf_1_1is__proto__enum_3_01_1_1caffe_1_1_v1_layer_parameter___dim_check_mode_01_4.html',1,'google::protobuf']]],
  ['is_5fproto_5fenum_3c_20_3a_3acaffe_3a_3av1layerparameter_5flayertype_20_3e',['is_proto_enum&lt; ::caffe::V1LayerParameter_LayerType &gt;',['../structgoogle_1_1protobuf_1_1is__proto__enum_3_01_1_1caffe_1_1_v1_layer_parameter___layer_type_01_4.html',1,'google::protobuf']]],
  ['isaprotocolmessage',['IsAProtocolMessage',['../structtesting_1_1internal_1_1_is_a_protocol_message.html',1,'testing::internal']]],
  ['isinalphabeticalorder',['IsInAlphabeticalOrder',['../classcpp__lint_1_1___include_state.html#a7849c0d95d8f156e7678ff6f76ede724',1,'cpp_lint::_IncludeState']]],
  ['issource',['IsSource',['../classcpp__lint_1_1_file_info.html#aa00d8322dc7ee1b1f523ea5c2a38c36a',1,'cpp_lint::FileInfo']]],
  ['iteratortraits',['IteratorTraits',['../structtesting_1_1internal_1_1_iterator_traits.html',1,'testing::internal']]],
  ['iteratortraits_3c_20const_20t_20_2a_20_3e',['IteratorTraits&lt; const T * &gt;',['../structtesting_1_1internal_1_1_iterator_traits_3_01const_01_t_01_5_01_4.html',1,'testing::internal']]],
  ['iteratortraits_3c_20t_20_2a_20_3e',['IteratorTraits&lt; T * &gt;',['../structtesting_1_1internal_1_1_iterator_traits_3_01_t_01_5_01_4.html',1,'testing::internal']]],
  ['index',['index',['../md_docs_index.html',1,'']]],
  ['install_5fapt',['install_apt',['../md_docs_install_apt.html',1,'']]],
  ['install_5fapt_5fdebian',['install_apt_debian',['../md_docs_install_apt_debian.html',1,'']]],
  ['install_5fosx',['install_osx',['../md_docs_install_osx.html',1,'']]],
  ['install_5fyum',['install_yum',['../md_docs_install_yum.html',1,'']]],
  ['installation',['installation',['../md_docs_installation.html',1,'']]],
  ['index',['index',['../md_docs_tutorial_index.html',1,'']]],
  ['interfaces',['interfaces',['../md_docs_tutorial_interfaces.html',1,'']]],
  ['im2col',['im2col',['../md_docs_tutorial_layers_im2col.html',1,'']]],
  ['imagedata',['imagedata',['../md_docs_tutorial_layers_imagedata.html',1,'']]],
  ['infogainloss',['infogainloss',['../md_docs_tutorial_layers_infogainloss.html',1,'']]],
  ['innerproduct',['innerproduct',['../md_docs_tutorial_layers_innerproduct.html',1,'']]],
  ['input',['input',['../md_docs_tutorial_layers_input.html',1,'']]],
  ['installation',['Installation',['../md__i_n_s_t_a_l_l.html',1,'']]]
];
