var searchData=
[
  ['caffe',['Caffe',['../classcaffe_1_1_caffe.html',1,'caffe::Caffe'],['../namespacecaffe.html',1,'caffe']]],
  ['caffesolver',['CaffeSolver',['../classtools_1_1_caffe_solver.html',1,'tools']]],
  ['callback',['Callback',['../classcaffe_1_1_net_1_1_callback.html',1,'caffe::Net&lt; Dtype &gt;::Callback'],['../classcaffe_1_1_solver_1_1_callback.html',1,'caffe::Solver&lt; Dtype &gt;::Callback']]],
  ['canonicalaxisindex',['CanonicalAxisIndex',['../classcaffe_1_1_blob.html#ad686f5ed9994046f2c741bfa81118509',1,'caffe::Blob::CanonicalAxisIndex(int axis_index) const'],['../classcaffe_1_1_blob.html#ad686f5ed9994046f2c741bfa81118509',1,'caffe::Blob::CanonicalAxisIndex(int axis_index) const']]],
  ['canonicalizealphabeticalorder',['CanonicalizeAlphabeticalOrder',['../classcpp__lint_1_1___include_state.html#a350d25886a03f0291676f533282f7eb8',1,'cpp_lint::_IncludeState']]],
  ['cartesianproductgenerator10',['CartesianProductGenerator10',['../classtesting_1_1internal_1_1_cartesian_product_generator10.html',1,'testing::internal']]],
  ['cartesianproductgenerator2',['CartesianProductGenerator2',['../classtesting_1_1internal_1_1_cartesian_product_generator2.html',1,'testing::internal']]],
  ['cartesianproductgenerator3',['CartesianProductGenerator3',['../classtesting_1_1internal_1_1_cartesian_product_generator3.html',1,'testing::internal']]],
  ['cartesianproductgenerator4',['CartesianProductGenerator4',['../classtesting_1_1internal_1_1_cartesian_product_generator4.html',1,'testing::internal']]],
  ['cartesianproductgenerator5',['CartesianProductGenerator5',['../classtesting_1_1internal_1_1_cartesian_product_generator5.html',1,'testing::internal']]],
  ['cartesianproductgenerator6',['CartesianProductGenerator6',['../classtesting_1_1internal_1_1_cartesian_product_generator6.html',1,'testing::internal']]],
  ['cartesianproductgenerator7',['CartesianProductGenerator7',['../classtesting_1_1internal_1_1_cartesian_product_generator7.html',1,'testing::internal']]],
  ['cartesianproductgenerator8',['CartesianProductGenerator8',['../classtesting_1_1internal_1_1_cartesian_product_generator8.html',1,'testing::internal']]],
  ['cartesianproductgenerator9',['CartesianProductGenerator9',['../classtesting_1_1internal_1_1_cartesian_product_generator9.html',1,'testing::internal']]],
  ['cartesianproductholder10',['CartesianProductHolder10',['../classtesting_1_1internal_1_1_cartesian_product_holder10.html',1,'testing::internal']]],
  ['cartesianproductholder2',['CartesianProductHolder2',['../classtesting_1_1internal_1_1_cartesian_product_holder2.html',1,'testing::internal']]],
  ['cartesianproductholder3',['CartesianProductHolder3',['../classtesting_1_1internal_1_1_cartesian_product_holder3.html',1,'testing::internal']]],
  ['cartesianproductholder4',['CartesianProductHolder4',['../classtesting_1_1internal_1_1_cartesian_product_holder4.html',1,'testing::internal']]],
  ['cartesianproductholder5',['CartesianProductHolder5',['../classtesting_1_1internal_1_1_cartesian_product_holder5.html',1,'testing::internal']]],
  ['cartesianproductholder6',['CartesianProductHolder6',['../classtesting_1_1internal_1_1_cartesian_product_holder6.html',1,'testing::internal']]],
  ['cartesianproductholder7',['CartesianProductHolder7',['../classtesting_1_1internal_1_1_cartesian_product_holder7.html',1,'testing::internal']]],
  ['cartesianproductholder8',['CartesianProductHolder8',['../classtesting_1_1internal_1_1_cartesian_product_holder8.html',1,'testing::internal']]],
  ['cartesianproductholder9',['CartesianProductHolder9',['../classtesting_1_1internal_1_1_cartesian_product_holder9.html',1,'testing::internal']]],
  ['channels',['channels',['../classcaffe_1_1_blob.html#ae48c8e9f0a0b66b041e47bf37ed04471',1,'caffe::Blob::channels() const'],['../classcaffe_1_1_blob.html#ae48c8e9f0a0b66b041e47bf37ed04471',1,'caffe::Blob::channels() const']]],
  ['check',['Check',['../classcpp__lint_1_1___function_state.html#a74430cb0bb43e253f617bba640391d09',1,'cpp_lint::_FunctionState']]],
  ['checkbegin',['CheckBegin',['../classcpp__lint_1_1___block_info.html#a69357fb2efabae1dd77aab9942b90560',1,'cpp_lint::_BlockInfo']]],
  ['checkblobcounts',['CheckBlobCounts',['../classcaffe_1_1_layer.html#a55c8036130225fbc874a986bdf4b27e2',1,'caffe::Layer::CheckBlobCounts(const vector&lt; Blob&lt; Dtype &gt; *&gt; &amp;bottom, const vector&lt; Blob&lt; Dtype &gt; *&gt; &amp;top)'],['../classcaffe_1_1_layer.html#a55c8036130225fbc874a986bdf4b27e2',1,'caffe::Layer::CheckBlobCounts(const vector&lt; Blob&lt; Dtype &gt; *&gt; &amp;bottom, const vector&lt; Blob&lt; Dtype &gt; *&gt; &amp;top)']]],
  ['checkcompletedblocks',['CheckCompletedBlocks',['../classcpp__lint_1_1___nesting_state.html#acacead3c8a88971753e46ac7a054e98f',1,'cpp_lint::_NestingState']]],
  ['checkend',['CheckEnd',['../classcpp__lint_1_1___block_info.html#abc44459ea5e04d6a9a4d816e85998bfc',1,'cpp_lint._BlockInfo.CheckEnd()'],['../classcpp__lint_1_1___namespace_info.html#ad119120161c94fea85e4152b563f15c6',1,'cpp_lint._NamespaceInfo.CheckEnd()']]],
  ['checknextincludeorder',['CheckNextIncludeOrder',['../classcpp__lint_1_1___include_state.html#abe91796a07f2ade774d3ecb934a67f80',1,'cpp_lint::_IncludeState']]],
  ['choose_5fcolor_5fby_5flayertype',['choose_color_by_layertype',['../namespacecaffe_1_1draw.html#ab06e25fd2bbb0166d3c3ff19d9854828',1,'caffe::draw']]],
  ['classifier',['Classifier',['../classcaffe_1_1classifier_1_1_classifier.html',1,'caffe.classifier.Classifier'],['../namespacecaffe_1_1classifier.html',1,'caffe.classifier']]],
  ['classify',['classify',['../namespaceclassify.html',1,'']]],
  ['cleansedlines',['CleansedLines',['../classcpp__lint_1_1_cleansed_lines.html',1,'cpp_lint']]],
  ['clearparamdiffs',['ClearParamDiffs',['../classcaffe_1_1_net.html#a3d251c397f812a6d8e162db3a82bb198',1,'caffe::Net::ClearParamDiffs()'],['../classcaffe_1_1_net.html#a3d251c397f812a6d8e162db3a82bb198',1,'caffe::Net::ClearParamDiffs()']]],
  ['coeff_5f',['coeff_',['../classcaffe_1_1_reduction_layer.html#a7aeb19ec25f01d4df995ba2122fbfeb3',1,'caffe::ReductionLayer']]],
  ['col_5fbuffer_5fshape_5f',['col_buffer_shape_',['../classcaffe_1_1_base_convolution_layer.html#ac60fd8d08cb94edad3dcaa28ff8a9ed8',1,'caffe::BaseConvolutionLayer']]],
  ['commontest',['CommonTest',['../classcaffe_1_1_common_test.html',1,'caffe']]],
  ['compileassert',['CompileAssert',['../structtesting_1_1internal_1_1_compile_assert.html',1,'testing::internal']]],
  ['compileasserttypesequal',['CompileAssertTypesEqual',['../structtesting_1_1internal_1_1_compile_assert_types_equal.html',1,'testing::internal']]],
  ['compileasserttypesequal_3c_20t_2c_20t_20_3e',['CompileAssertTypesEqual&lt; T, T &gt;',['../structtesting_1_1internal_1_1_compile_assert_types_equal_3_01_t_00_01_t_01_4.html',1,'testing::internal']]],
  ['compose',['compose',['../namespacecaffe_1_1coord__map.html#a06830f75738dcbc0b29bfeb30ae4f990',1,'caffe::coord_map']]],
  ['concat_5fbottom_5fvec_5f',['concat_bottom_vec_',['../classcaffe_1_1_s_p_p_layer.html#a17d3d8b3ea6fbcf4db4cefa775dea229',1,'caffe::SPPLayer']]],
  ['concat_5flayer_5f',['concat_layer_',['../classcaffe_1_1_s_p_p_layer.html#a77249333fc51f12914ec68e27b989974',1,'caffe::SPPLayer']]],
  ['concatlayer',['ConcatLayer',['../classcaffe_1_1_concat_layer.html',1,'caffe']]],
  ['concatlayertest',['ConcatLayerTest',['../classcaffe_1_1_concat_layer_test.html',1,'caffe']]],
  ['concatparameter',['ConcatParameter',['../classcaffe_1_1_concat_parameter.html',1,'caffe']]],
  ['configure_5fcrop',['configure_crop',['../classcaffe_1_1detector_1_1_detector.html#a3706bb8bcd04387c065f7bb6b34f4875',1,'caffe.detector.Detector.configure_crop(self, context_pad)'],['../classcaffe_1_1detector_1_1_detector.html#a3706bb8bcd04387c065f7bb6b34f4875',1,'caffe.detector.Detector.configure_crop(self, context_pad)']]],
  ['constant_5fcount_5f',['constant_count_',['../classcaffe_1_1_reshape_layer.html#abbb071bc8398e2b0442302e51c644c28',1,'caffe::ReshapeLayer']]],
  ['constantfiller',['ConstantFiller',['../classcaffe_1_1_constant_filler.html',1,'caffe']]],
  ['constantfillertest',['ConstantFillerTest',['../classcaffe_1_1_constant_filler_test.html',1,'caffe']]],
  ['constcharptr',['ConstCharPtr',['../structtesting_1_1internal_1_1_const_char_ptr.html',1,'testing::internal']]],
  ['contrastivelosslayer',['ContrastiveLossLayer',['../classcaffe_1_1_contrastive_loss_layer.html',1,'caffe']]],
  ['contrastivelosslayertest',['ContrastiveLossLayerTest',['../classcaffe_1_1_contrastive_loss_layer_test.html',1,'caffe']]],
  ['contrastivelossparameter',['ContrastiveLossParameter',['../classcaffe_1_1_contrastive_loss_parameter.html',1,'caffe']]],
  ['conv_5finput_5fshape_5f',['conv_input_shape_',['../classcaffe_1_1_base_convolution_layer.html#a6b07e480f689f28bc064327abbe9e751',1,'caffe::BaseConvolutionLayer']]],
  ['conv_5fparams',['conv_params',['../namespacecaffe_1_1coord__map.html#a1683f31b74339c8ac4c4985132fdecfc',1,'caffe::coord_map']]],
  ['convolutionlayer',['ConvolutionLayer',['../classcaffe_1_1_convolution_layer.html',1,'caffe::ConvolutionLayer&lt; Dtype &gt;'],['../classcaffe_1_1_convolution_layer.html#ad27360afd7729001b9e4f1d8c8401866',1,'caffe::ConvolutionLayer::ConvolutionLayer(const LayerParameter &amp;param)'],['../classcaffe_1_1_convolution_layer.html#ad27360afd7729001b9e4f1d8c8401866',1,'caffe::ConvolutionLayer::ConvolutionLayer(const LayerParameter &amp;param)']]],
  ['convolutionlayertest',['ConvolutionLayerTest',['../classcaffe_1_1_convolution_layer_test.html',1,'caffe']]],
  ['convolutionparameter',['ConvolutionParameter',['../classcaffe_1_1_convolution_parameter.html',1,'caffe']]],
  ['coord_5fmap',['coord_map',['../namespacecaffe_1_1coord__map.html',1,'caffe.coord_map'],['../namespacecaffe_1_1coord__map.html#a0f5ba2053a2fd10038360dea8b2e5b9b',1,'caffe.coord_map.coord_map()']]],
  ['coord_5fmap_5ffrom_5fto',['coord_map_from_to',['../namespacecaffe_1_1coord__map.html#abf9ba4c31e6e4f0bcd3130ea9001514b',1,'caffe::coord_map']]],
  ['copy_5faxes_5f',['copy_axes_',['../classcaffe_1_1_reshape_layer.html#accb52092dc105175a888368e1ded6a12',1,'caffe::ReshapeLayer']]],
  ['copy_5fnotebook',['copy_notebook',['../namespacecopy__notebook.html',1,'']]],
  ['copyfrom',['CopyFrom',['../classcaffe_1_1_blob.html#a64ad51f99e88233f43a21a85ebe10284',1,'caffe::Blob::CopyFrom(const Blob&lt; Dtype &gt; &amp;source, bool copy_diff=false, bool reshape=false)'],['../classcaffe_1_1_blob.html#a64ad51f99e88233f43a21a85ebe10284',1,'caffe::Blob::CopyFrom(const Blob&lt; Dtype &gt; &amp;source, bool copy_diff=false, bool reshape=false)']]],
  ['copytrainedlayersfrom',['CopyTrainedLayersFrom',['../classcaffe_1_1_net.html#a4ac2b69748470f54d530bc5dfa05b9c3',1,'caffe::Net::CopyTrainedLayersFrom(const NetParameter &amp;param)'],['../classcaffe_1_1_net.html#a4ac2b69748470f54d530bc5dfa05b9c3',1,'caffe::Net::CopyTrainedLayersFrom(const NetParameter &amp;param)']]],
  ['count',['count',['../classcaffe_1_1_blob.html#a8674686a97c961b309b4420ead6626b5',1,'caffe::Blob::count(int start_axis, int end_axis) const'],['../classcaffe_1_1_blob.html#aab573b2a70c26bf3b2ae65e42706003e',1,'caffe::Blob::count(int start_axis) const'],['../classcaffe_1_1_blob.html#a8674686a97c961b309b4420ead6626b5',1,'caffe::Blob::count(int start_axis, int end_axis) const'],['../classcaffe_1_1_blob.html#aab573b2a70c26bf3b2ae65e42706003e',1,'caffe::Blob::count(int start_axis) const'],['../classcpp__lint_1_1___function_state.html#a402797f40424f11da27896926362b23f',1,'cpp_lint._FunctionState.Count()']]],
  ['cpudevice',['CPUDevice',['../structcaffe_1_1_c_p_u_device.html',1,'caffe']]],
  ['cpudevicetest',['CPUDeviceTest',['../classcaffe_1_1_c_p_u_device_test.html',1,'caffe']]],
  ['cpudevicetest_3c_20typeparam_20_3e',['CPUDeviceTest&lt; TypeParam &gt;',['../classcaffe_1_1_c_p_u_device_test.html',1,'caffe']]],
  ['cpumathfunctionstest',['CPUMathFunctionsTest',['../classcaffe_1_1_c_p_u_math_functions_test.html',1,'caffe']]],
  ['cpustochasticpoolinglayertest',['CPUStochasticPoolingLayerTest',['../classcaffe_1_1_c_p_u_stochastic_pooling_layer_test.html',1,'caffe']]],
  ['cputimer',['CPUTimer',['../classcaffe_1_1_c_p_u_timer.html',1,'caffe']]],
  ['crop',['crop',['../classcaffe_1_1detector_1_1_detector.html#af71bb7e173a228c2e1577b9125310216',1,'caffe.detector.Detector.crop(self, im, window)'],['../classcaffe_1_1detector_1_1_detector.html#af71bb7e173a228c2e1577b9125310216',1,'caffe.detector.Detector.crop(self, im, window)'],['../namespacecaffe_1_1coord__map.html#aca9f1366a027d686a27d150e054296ee',1,'caffe.coord_map.crop()']]],
  ['crop_5fparams',['crop_params',['../namespacecaffe_1_1coord__map.html#ac97591996ede7cfc368c2e472e0d07b6',1,'caffe::coord_map']]],
  ['croplayer',['CropLayer',['../classcaffe_1_1_crop_layer.html',1,'caffe']]],
  ['croplayertest',['CropLayerTest',['../classcaffe_1_1_crop_layer_test.html',1,'caffe']]],
  ['cropparameter',['CropParameter',['../classcaffe_1_1_crop_parameter.html',1,'caffe']]],
  ['cursor',['Cursor',['../classcaffe_1_1db_1_1_cursor.html',1,'caffe::db']]],
  ['detector',['detector',['../namespacecaffe_1_1detector.html',1,'caffe']]],
  ['draw',['draw',['../namespacecaffe_1_1draw.html',1,'caffe']]],
  ['contributing',['Contributing',['../md__c_o_n_t_r_i_b_u_t_i_n_g.html',1,'']]],
  ['contributors',['Contributors',['../md__c_o_n_t_r_i_b_u_t_o_r_s.html',1,'']]],
  ['caffe_20documentation',['Caffe Documentation',['../md_docs__r_e_a_d_m_e.html',1,'']]],
  ['convolution',['convolution',['../md_docs_tutorial_convolution.html',1,'']]],
  ['concat',['concat',['../md_docs_tutorial_layers_concat.html',1,'']]],
  ['contrastiveloss',['contrastiveloss',['../md_docs_tutorial_layers_contrastiveloss.html',1,'']]],
  ['convolution',['convolution',['../md_docs_tutorial_layers_convolution.html',1,'']]],
  ['crop',['crop',['../md_docs_tutorial_layers_crop.html',1,'']]],
  ['caffe',['Caffe',['../md__r_e_a_d_m_e.html',1,'']]],
  ['net_5fspec',['net_spec',['../namespacecaffe_1_1net__spec.html',1,'caffe']]],
  ['pycaffe',['pycaffe',['../namespacecaffe_1_1pycaffe.html',1,'caffe']]],
  ['solveraction',['SolverAction',['../namespacecaffe_1_1_solver_action.html',1,'caffe']]]
];
