var searchData=
[
  ['baseconvolutionlayer',['BaseConvolutionLayer',['../classcaffe_1_1_base_convolution_layer.html',1,'caffe']]],
  ['basedatalayer',['BaseDataLayer',['../classcaffe_1_1_base_data_layer.html',1,'caffe']]],
  ['baseprefetchingdatalayer',['BasePrefetchingDataLayer',['../classcaffe_1_1_base_prefetching_data_layer.html',1,'caffe']]],
  ['batch',['Batch',['../classcaffe_1_1_batch.html',1,'caffe']]],
  ['batchloader',['BatchLoader',['../classpascal__multilabel__datalayers_1_1_batch_loader.html',1,'pascal_multilabel_datalayers']]],
  ['batchnormlayer',['BatchNormLayer',['../classcaffe_1_1_batch_norm_layer.html',1,'caffe']]],
  ['batchnormlayertest',['BatchNormLayerTest',['../classcaffe_1_1_batch_norm_layer_test.html',1,'caffe']]],
  ['batchnormparameter',['BatchNormParameter',['../classcaffe_1_1_batch_norm_parameter.html',1,'caffe']]],
  ['batchreindexlayer',['BatchReindexLayer',['../classcaffe_1_1_batch_reindex_layer.html',1,'caffe']]],
  ['batchreindexlayertest',['BatchReindexLayerTest',['../classcaffe_1_1_batch_reindex_layer_test.html',1,'caffe']]],
  ['benchmarktest',['BenchmarkTest',['../classcaffe_1_1_benchmark_test.html',1,'caffe']]],
  ['biaslayer',['BiasLayer',['../classcaffe_1_1_bias_layer.html',1,'caffe']]],
  ['biaslayertest',['BiasLayerTest',['../classcaffe_1_1_bias_layer_test.html',1,'caffe']]],
  ['biasparameter',['BiasParameter',['../classcaffe_1_1_bias_parameter.html',1,'caffe']]],
  ['bilinearfiller',['BilinearFiller',['../classcaffe_1_1_bilinear_filler.html',1,'caffe']]],
  ['bilinearfillertest',['BilinearFillerTest',['../classcaffe_1_1_bilinear_filler_test.html',1,'caffe']]],
  ['blob',['Blob',['../classcaffe_1_1_blob.html',1,'caffe']]],
  ['blob_3c_20int_20_3e',['Blob&lt; int &gt;',['../classcaffe_1_1_blob.html',1,'caffe']]],
  ['blob_3c_20unsigned_20int_20_3e',['Blob&lt; unsigned int &gt;',['../classcaffe_1_1_blob.html',1,'caffe']]],
  ['blobmathtest',['BlobMathTest',['../classcaffe_1_1_blob_math_test.html',1,'caffe']]],
  ['blobproto',['BlobProto',['../classcaffe_1_1_blob_proto.html',1,'caffe']]],
  ['blobprotovector',['BlobProtoVector',['../classcaffe_1_1_blob_proto_vector.html',1,'caffe']]],
  ['blobshape',['BlobShape',['../classcaffe_1_1_blob_shape.html',1,'caffe']]],
  ['blobsimpletest',['BlobSimpleTest',['../classcaffe_1_1_blob_simple_test.html',1,'caffe']]],
  ['blockingqueue',['BlockingQueue',['../classcaffe_1_1_blocking_queue.html',1,'caffe']]],
  ['blockingqueue_3c_20caffe_3a_3abatch_3c_20dtype_20_3e_20_2a_3e',['BlockingQueue&lt; caffe::Batch&lt; Dtype &gt; *&gt;',['../classcaffe_1_1_blocking_queue.html',1,'caffe']]],
  ['bnlllayer',['BNLLLayer',['../classcaffe_1_1_b_n_l_l_layer.html',1,'caffe']]],
  ['bool_5fconstant',['bool_constant',['../structtesting_1_1internal_1_1bool__constant.html',1,'testing::internal']]],
  ['bool_5fconstant_3c_20implicitlyconvertible_3c_20const_20t_20_2a_2c_20const_20_3a_3aprotocolmessage_20_2a_3e_3a_3avalue_7c_7cimplicitlyconvertible_3c_20const_20t_20_2a_2c_20const_20_3a_3aproto2_3a_3amessage_20_2a_3e_3a_3avalue_20_3e',['bool_constant&lt; ImplicitlyConvertible&lt; const T *, const ::ProtocolMessage *&gt;::value||ImplicitlyConvertible&lt; const T *, const ::proto2::Message *&gt;::value &gt;',['../structtesting_1_1internal_1_1bool__constant.html',1,'testing::internal']]],
  ['byref',['ByRef',['../structstd_1_1tr1_1_1gtest__internal_1_1_by_ref.html',1,'std::tr1::gtest_internal']]],
  ['byref_3c_20t_20_26_20_3e',['ByRef&lt; T &amp; &gt;',['../structstd_1_1tr1_1_1gtest__internal_1_1_by_ref_3_01_t_01_6_01_4.html',1,'std::tr1::gtest_internal']]]
];
