var searchData=
[
  ['samesizetupleprefixcomparator',['SameSizeTuplePrefixComparator',['../structstd_1_1tr1_1_1gtest__internal_1_1_same_size_tuple_prefix_comparator.html',1,'std::tr1::gtest_internal']]],
  ['samesizetupleprefixcomparator_3c_200_2c_200_20_3e',['SameSizeTuplePrefixComparator&lt; 0, 0 &gt;',['../structstd_1_1tr1_1_1gtest__internal_1_1_same_size_tuple_prefix_comparator_3_010_00_010_01_4.html',1,'std::tr1::gtest_internal']]],
  ['samesizetupleprefixcomparator_3c_20k_2c_20k_20_3e',['SameSizeTuplePrefixComparator&lt; k, k &gt;',['../structstd_1_1tr1_1_1gtest__internal_1_1_same_size_tuple_prefix_comparator_3_01k_00_01k_01_4.html',1,'std::tr1::gtest_internal']]],
  ['scalelayer',['ScaleLayer',['../classcaffe_1_1_scale_layer.html',1,'caffe']]],
  ['scalelayertest',['ScaleLayerTest',['../classcaffe_1_1_scale_layer_test.html',1,'caffe']]],
  ['scaleparameter',['ScaleParameter',['../classcaffe_1_1_scale_parameter.html',1,'caffe']]],
  ['scoped_5fptr',['scoped_ptr',['../classtesting_1_1internal_1_1scoped__ptr.html',1,'testing::internal']]],
  ['scoped_5fptr_3c_20_3a_3astd_3a_3astring_20_3e',['scoped_ptr&lt; ::std::string &gt;',['../classtesting_1_1internal_1_1scoped__ptr.html',1,'testing::internal']]],
  ['scoped_5fptr_3c_20_3a_3astd_3a_3astringstream_20_3e',['scoped_ptr&lt; ::std::stringstream &gt;',['../classtesting_1_1internal_1_1scoped__ptr.html',1,'testing::internal']]],
  ['scoped_5fptr_3c_20const_20_3a_3astd_3a_3astring_20_3e',['scoped_ptr&lt; const ::std::string &gt;',['../classtesting_1_1internal_1_1scoped__ptr.html',1,'testing::internal']]],
  ['scoped_5fptr_3c_20const_20t_20_3e',['scoped_ptr&lt; const T &gt;',['../classtesting_1_1internal_1_1scoped__ptr.html',1,'testing::internal']]],
  ['scoped_5fptr_3c_20testing_3a_3ainternal_3a_3aparamiteratorinterface_3c_20t_20_3e_20_3e',['scoped_ptr&lt; testing::internal::ParamIteratorInterface&lt; T &gt; &gt;',['../classtesting_1_1internal_1_1scoped__ptr.html',1,'testing::internal']]],
  ['scoped_5fptr_3c_20testing_3a_3ainternal_3a_3atestmetafactorybase_3c_20paramtype_20_3e_20_3e',['scoped_ptr&lt; testing::internal::TestMetaFactoryBase&lt; ParamType &gt; &gt;',['../classtesting_1_1internal_1_1scoped__ptr.html',1,'testing::internal']]],
  ['scopedfaketestpartresultreporter',['ScopedFakeTestPartResultReporter',['../classtesting_1_1_scoped_fake_test_part_result_reporter.html',1,'testing']]],
  ['scopedtrace',['ScopedTrace',['../classtesting_1_1internal_1_1_scoped_trace.html',1,'testing::internal']]],
  ['sgdsolver',['SGDSolver',['../classcaffe_1_1_s_g_d_solver.html',1,'caffe']]],
  ['sgdsolvertest',['SGDSolverTest',['../classcaffe_1_1_s_g_d_solver_test.html',1,'caffe']]],
  ['sigmoidcrossentropylosslayer',['SigmoidCrossEntropyLossLayer',['../classcaffe_1_1_sigmoid_cross_entropy_loss_layer.html',1,'caffe']]],
  ['sigmoidcrossentropylosslayertest',['SigmoidCrossEntropyLossLayerTest',['../classcaffe_1_1_sigmoid_cross_entropy_loss_layer_test.html',1,'caffe']]],
  ['sigmoidlayer',['SigmoidLayer',['../classcaffe_1_1_sigmoid_layer.html',1,'caffe']]],
  ['sigmoidparameter',['SigmoidParameter',['../classcaffe_1_1_sigmoid_parameter.html',1,'caffe']]],
  ['signalhandler',['SignalHandler',['../classcaffe_1_1_signal_handler.html',1,'caffe']]],
  ['silencelayer',['SilenceLayer',['../classcaffe_1_1_silence_layer.html',1,'caffe']]],
  ['simplelayer',['SimpleLayer',['../classtest__python__layer_1_1_simple_layer.html',1,'test_python_layer']]],
  ['simpleparamlayer',['SimpleParamLayer',['../classtest__python__layer__with__param__str_1_1_simple_param_layer.html',1,'test_python_layer_with_param_str']]],
  ['simpletransformer',['SimpleTransformer',['../classtools_1_1_simple_transformer.html',1,'tools']]],
  ['singlefailurechecker',['SingleFailureChecker',['../classtesting_1_1internal_1_1_single_failure_checker.html',1,'testing::internal']]],
  ['slicelayer',['SliceLayer',['../classcaffe_1_1_slice_layer.html',1,'caffe']]],
  ['slicelayertest',['SliceLayerTest',['../classcaffe_1_1_slice_layer_test.html',1,'caffe']]],
  ['sliceparameter',['SliceParameter',['../classcaffe_1_1_slice_parameter.html',1,'caffe']]],
  ['softmaxlayer',['SoftmaxLayer',['../classcaffe_1_1_softmax_layer.html',1,'caffe']]],
  ['softmaxlayertest',['SoftmaxLayerTest',['../classcaffe_1_1_softmax_layer_test.html',1,'caffe']]],
  ['softmaxparameter',['SoftmaxParameter',['../classcaffe_1_1_softmax_parameter.html',1,'caffe']]],
  ['softmaxwithlosslayer',['SoftmaxWithLossLayer',['../classcaffe_1_1_softmax_with_loss_layer.html',1,'caffe']]],
  ['softmaxwithlosslayertest',['SoftmaxWithLossLayerTest',['../classcaffe_1_1_softmax_with_loss_layer_test.html',1,'caffe']]],
  ['solver',['Solver',['../classcaffe_1_1_solver.html',1,'caffe']]],
  ['solvercallback',['SolverCallback',['../classcaffe_1_1_solver_callback.html',1,'caffe']]],
  ['solverfactorytest',['SolverFactoryTest',['../classcaffe_1_1_solver_factory_test.html',1,'caffe']]],
  ['solverparameter',['SolverParameter',['../classcaffe_1_1_solver_parameter.html',1,'caffe']]],
  ['solverregisterer',['SolverRegisterer',['../classcaffe_1_1_solver_registerer.html',1,'caffe']]],
  ['solverregistry',['SolverRegistry',['../classcaffe_1_1_solver_registry.html',1,'caffe']]],
  ['solverstate',['SolverState',['../classcaffe_1_1_solver_state.html',1,'caffe']]],
  ['solvertest',['SolverTest',['../classcaffe_1_1_solver_test.html',1,'caffe']]],
  ['solvertypeupgradetest',['SolverTypeUpgradeTest',['../classcaffe_1_1_solver_type_upgrade_test.html',1,'caffe']]],
  ['splitlayer',['SplitLayer',['../classcaffe_1_1_split_layer.html',1,'caffe']]],
  ['splitlayerinsertiontest',['SplitLayerInsertionTest',['../classcaffe_1_1_split_layer_insertion_test.html',1,'caffe']]],
  ['splitlayertest',['SplitLayerTest',['../classcaffe_1_1_split_layer_test.html',1,'caffe']]],
  ['spplayer',['SPPLayer',['../classcaffe_1_1_s_p_p_layer.html',1,'caffe']]],
  ['spplayertest',['SPPLayerTest',['../classcaffe_1_1_s_p_p_layer_test.html',1,'caffe']]],
  ['sppparameter',['SPPParameter',['../classcaffe_1_1_s_p_p_parameter.html',1,'caffe']]],
  ['staticasserttypeeqhelper',['StaticAssertTypeEqHelper',['../structtesting_1_1internal_1_1_static_assert_type_eq_helper.html',1,'testing::internal']]],
  ['staticasserttypeeqhelper_3c_20t_2c_20t_20_3e',['StaticAssertTypeEqHelper&lt; T, T &gt;',['../structtesting_1_1internal_1_1_static_assert_type_eq_helper_3_01_t_00_01_t_01_4.html',1,'testing::internal']]],
  ['staticdescriptorinitializer_5fcaffe_5f2eproto',['StaticDescriptorInitializer_caffe_2eproto',['../structcaffe_1_1_static_descriptor_initializer__caffe__2eproto.html',1,'caffe']]],
  ['stochasticpoolinglayertest',['StochasticPoolingLayerTest',['../classcaffe_1_1_stochastic_pooling_layer_test.html',1,'caffe']]],
  ['stochasticpoolinglayertest_3c_20cpudevice_3c_20dtype_20_3e_20_3e',['StochasticPoolingLayerTest&lt; CPUDevice&lt; Dtype &gt; &gt;',['../classcaffe_1_1_stochastic_pooling_layer_test.html',1,'caffe']]],
  ['stochasticpoolinglayertest_3c_20gpudevice_3c_20dtype_20_3e_20_3e',['StochasticPoolingLayerTest&lt; GPUDevice&lt; Dtype &gt; &gt;',['../classcaffe_1_1_stochastic_pooling_layer_test.html',1,'caffe']]],
  ['string',['String',['../classtesting_1_1internal_1_1_string.html',1,'testing::internal']]],
  ['swishlayer',['SwishLayer',['../classcaffe_1_1_swish_layer.html',1,'caffe']]],
  ['swishparameter',['SwishParameter',['../classcaffe_1_1_swish_parameter.html',1,'caffe']]],
  ['sync',['sync',['../classcaffe_1_1_blocking_queue_1_1sync.html',1,'caffe::BlockingQueue']]],
  ['syncedmemory',['SyncedMemory',['../classcaffe_1_1_synced_memory.html',1,'caffe']]],
  ['syncedmemorytest',['SyncedMemoryTest',['../classcaffe_1_1_synced_memory_test.html',1,'caffe']]]
];
